ENHANCE: Modify decoding logic in collection get api.
naver/arcus-java-client pull request #634
Opened 2023-06-28 07:14 UTC by brido4125

## 관련 PR
https://github.com/jam2in/arcus-works/issues/406

## 변경사항
기존에는 collection get을 호출할 경우 decode 로직이 IO 쓰레드에서 수행됩니다.
이러한 decode 로직을 appilcation의 Worker 쓰레드에서 수행하도록 변경하였습니다.

응용이 get()을 호출할 경우 decode를 진행하여 로직이 변경되도록 하였습니다.
변경된 로직은 아래와 같은 절차를 거칩니다.

1. 응용에서 collection get api 호출한다.
2. api 내에서 CollectionGetFuture 생성을 하고 decode 수행에 필요한 TrancsCoder 주입한다.
3. IO 쓰레드에 의해 callback 함수 gotData() 호출되고 decode 시 필요한 CachedData 인스턴스를 생성하고 이를 CollectionGetFuture 인스턴스에 put 또는 add한다.
4. 응용은 리턴 받은 CollectionFuture의 get() 함수를 호출한다.
5. CollectionGetFuture의 get()이 호출되면 super class로부터 collection의 타입에 맞게 리턴할 value를 받아온다. 이후 tc.decode()를 수행한다. 그 결과로 나온 T타입의 객체를 결과 value(list, map, set 중 하나)에 추가하고 사용자에게 value를 리턴한다.

2023-06-29 06:28 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CollectionGetFuture.java
> +    if (op.getAPIType().equals(APIType.MOP_GET)) {
`op.getAPIType()`를 변수에 담고 그 변수를 사용하도록 하죠.

2023-06-29 06:28 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CollectionGetFuture.java
> +      return (R) map;
응용에서 get() 메소드를 2회 호출하면, transcode 역시 2회 수행됩니다.
이전에 trasncode가 이미 수행되었다면, 그 결과를 저장해두었다가 다시 get() 호출 시 그 결과를 반환하는 것이 좋을 것 같습니다.

2023-06-29 06:28 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CollectionGetFuture.java
> +    }
향후 다른 Collection 추가를 대비해서, 아래와 같은 코드를 넣는 것은 어떨까요?

```java
final ... apiType = op.getAPIType();

...

else {
  assert false : "Unhandled API Type : " + apiType
}
```

2023-06-29 07:25 UTC, brido4125 commented
@uhm0311 
현재까지 리뷰해주신 사항 반영하였습니다.

추가적으로 아래의 단건 조회 api들 또한 반영되어야 하기에 작업 완료 후 다시 noti 하겠습니다.
- asyncBopExtendedGet
- asyncBopFindPositionWithGet
- asyncBTreeInsertAndGet
- asyncBopGetByPosition

2023-07-03 03:36 UTC, brido4125 commented
해당 PR에서는 아래 API까지만 반영하도록 하겠습니다.
- asyncBopExtendedGet 

나머지 3가지의 api는 변경 지점이 많아 질 것 같아 해당 PR 이후에 작업하겠습니다.

리뷰 다시 한번 부탁드리겠습니다.

2023-07-12 08:16 UTC, brido4125 commented
변경된 로직의 inner 클래스들의 get() 메서드에서 아래의 로직이 반복됩니다.
리뷰해 주실 때 아래 로직을 최적화 할 수 있는 방안도 추천해주시면 감사하겠습니다

```java
if (result != null) {
        return result;
      }
      result = super.get(duration, units);
      if (cachedDataList.isEmpty()) {
        return result;
      }
```

2023-07-13 04:02 UTC, uhm0311 requested changes

2023-07-13 04:02 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CollectionGetFuture.java
> +      }
이건 어떨까요?

``` java
if (result == null) {
  result = super.get(duration, units);
  for (CachedData cachedData : this.cachedDataList) {
    ...
  }
}
return result;
```

2023-07-14 05:24 UTC, uhm0311 requested changes

2023-07-14 05:24 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CollectionGetFuture.java
> +    public void addCacheData(CachedData data) {
인자 타입과 맞춰서 addCachedData로 이름을 바꿉시다.
다른 컬렉션의 같은 역할을 하는 메소드도 포함입니다.

2023-07-14 05:24 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CollectionGetFuture.java
> +            throws InterruptedException, TimeoutException, ExecutionException {
Multiline method signature 다음에 Empty line을 추가합시다.
다른 컬렉션도 포함입니다.

2023-07-14 05:24 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CollectionGetFuture.java
> +        List<byte[]> elementFlag = collectionGetOperation.getGet().getElementFlag();
getGet().getElementFlag()로 간접 호출하지 말고 collectionGetOperation.getElementFlag() 메소드를 추가하여 내부적으로 get.getElementFlag() 반환하도록 합시다.

2023-07-14 06:39 UTC, uhm0311 approved these changes

2023-07-14 06:39 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +
Empty line 제거

2023-07-31 03:22 UTC, brido4125 commented
@jhpark816 
최종리뷰 부탁드립니다.

2023-08-01 04:43 UTC, jhpark816 reviewed
1차 리뷰

2023-08-01 04:43 UTC, jhpark816 commented on src/main/java/net/spy/memcached/collection/Element.java
> +  }
byte array bkey에 해당하는 아래 메소드가 있습니다.
ByteArrayBKey 타입의 bkey 사용해야 하나요?
```java
  public Element(byte[] bkey, T value, byte[] eflag) {
    this.bKeyObject = new BKeyObject(bkey);
    this.value = value;
    this.eflag = eflag;
    this.elementFlagUpdate = null;
  }
```

2023-08-01 04:43 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +            rv.putCachedData(Long.parseLong(bkey), new CachedData(flags, data, tc.getMaxSize()));
기존대로 element 객체를 생성하여 저장하는 방식이 나은 것 같습니다.

2023-08-01 04:43 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +            rv.addCachedData(new CachedData(flags, data, tc.getMaxSize()));
기존 list 객체는 위 코드를 제외한 기존 코드에서 그대로 사용하고 있는 데, 문제가 없나요?

기존대로 list에 CachedData를 저장해 두고, 이를 future에 그대로 넘기고, 
Future.get() 시에 CacheData를 real data 변환하는 작업만 수행하는 것이 더 간단하지 않는 지 ?
이 부분은 검토 바랍니다.

2023-08-01 06:09 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +            rv.putCachedData(Long.parseLong(bkey), new CachedData(flags, data, tc.getMaxSize()));
element 객체를 생성하려면 
decode된 결과값이 필요하여 
위와 같이 구현하였습니다.

2023-08-01 06:20 UTC, brido4125 commented on src/main/java/net/spy/memcached/collection/Element.java
> +  }
응용이 전달받는 Map의 key 타입이
ByteArrayBKey이라서 
ByteArrayBKey 타입을 사용해야합니다.

2023-08-01 06:26 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +            rv.addCachedData(new CachedData(flags, data, tc.getMaxSize()));
> 기존 list 객체는 위 코드를 제외한 기존 코드에서 그대로 사용하고 있는 데, 문제가 없나요?

응용에서 get 호출 시 기존 list의 reference에 
decode된 T를 추가해주고 있어서
로직적으로 문제는 없습니다.

다만, 구현은 말씀하신 방향으로 변경하는것이 효율적일것 같습니다.

2023-08-01 07:48 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +            rv.addCachedData(new CachedData(flags, data, tc.getMaxSize()));
구현을 검토해본 결과입니다.

기존에 존재하는 List의 타입은
`List<T> list` 입니다.

**즉, 응용에게 전달되는 T 타입의 elem들이 포함**됩니다.
결과적으로 type miss match 때문에
CachedData 인스턴스들은 기존의 list에 저장할 수 없습니다.
그래서 별도의 List<CachedData>의 리스트에 cachedData를 저장해야합니다.

2023-08-02 05:11 UTC, brido4125 commented
@jhpark816 
오프라인에서 논의한대로
위 PR을 통해 eflag 값을 CollectionGet의 참조가 통해서가 아닌
콜백 함수인 gotData를 통해 받아오도록 변경할 수 있습니다.

리뷰 부탁드립니다.

2023-08-04 02:12 UTC, jhpark816 reviewed
리뷰 완료

2023-08-04 02:12 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/CollectionGetFuture.java
> +    private final List<CachedData> cachedDataList = new ArrayList<CachedData>();
반대로, CollectionFuture에서 cachedDataList를 가지고,
CollectionGetFuture에서 최종 결과를 가지도록 하는 것이 좋겠습니다.

2023-08-04 02:12 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +            new CollectionGetFuture.BTreeGetFuture<Long, T>(latch, operationTimeout, tc);
최종 결과를 CollectionGetFuture에서 유지하기 위하여 `reverse` 인자를 넘기거나
아니면 중간 결과를 TreeMap으로 넘기고,
최종 결과의 TreeMap은 comparator를 중간 결과의 TreeMap compartor와 동일하게 맞추면 됩니다.
후자가 나을 것 같긴 합니다.

2023-08-04 05:50 UTC, brido4125 commented
현재 PR은 중간 결과를 연산의 자료구조에 상관없이
모두 List 타입에 담을 수 있도록 로직 최적화했습니다.

위 코멘트 중 다음과 같은 사항들이 이해가 가지 않아 의견 남깁니다.

> CachedData 리스트를 중간 결과로 보관하는 것은
기존 방식과 같이 callback 내의 list로 유지하고, 마지막에 Future에 넘겨주면 좋겠습니다.

콜백에서 중간 결과에 대한 reference를 가져야할 이유가 무엇인가요?
무조건 콜백의 중간 결과 또한 Future에게 refernece를 주입해줘야하는데
가지고 있을 필요가 없다고 생각합니다.

> 반대로, CollectionFuture에서 cachedDataList를 가지고,
CollectionGetFuture에서 최종 결과를 가지도록 하는 것이 좋겠습니다.

CollectionFuture가 CollectionGet api의 
연산의 cachedDataList Field를 가지게 하는것은 다음과 같은 단점이 있습니다.
CollectionFuture를 통해 연산되 api가 사용도 하지 않는 Field를 매번 생성해야합니다.
또한  CollectionFuture의 코드를 읽을 때에도 상관 없는 Field가 존재하니
일관성을 해친다고 생각합니다.

> 최종 결과를 CollectionGetFuture에서 유지하기 위하여 reverse 인자를 넘기거나
아니면 중간 결과를 TreeMap으로 넘기고, ...

현재 리팩토링의 대상인 asyncBopGet, asyncBopExtendGet의 경우
최종 결과의 타입이 TreeMap, ByteArrayTreeMap으로 서로 상이합니다.
타입이 다른 두 자료구조를 동일한 생성자에서 만들어내려면
CollectionGetFuture의 Inner 클래스를 추가하거나
다른 방안은 고려해보아야합니다.

결론적으로는 현재 로직에서 최종 결과를 
receiveStatus()라는 콜백 함수에서 
Future에 주입하고 있습니다.
receiveStatus 함수의 의미를 생각해보면
연산의 최종 결과의 상태를 인자로 받아 이를 Future에 반영하는 함수라고 생각합니다.
결국 최종 결과와 관련된 메서드인 만큼 Future에 최종 결과를 주입하는것이
자연스럽지 않나 생각합니다.

2023-08-07 06:48 UTC, brido4125 commented
말씀하신대로 아래와 같이 get 함수내에서
콜백을 통해 Decode를 worker thread가 수행하도록 변경가능합니다.

```java
    @Override
    public Set<T> get(long duration, TimeUnit units)
            throws InterruptedException, TimeoutException, ExecutionException {

      CollectionGetOperation.Callback callback = (CollectionGetOperation.Callback) op.getCallback();
      callback.decoedData(cachedData);
      // ...
    }
```

```java
public void decodeData(CachedData cachedData) {
            set.add(tc.decode(cachedData));
          }
```

다만, Future에서 리턴 타입에 대한 정보를 가지지 않으려면
콜백에서 중간결과와 최종결과에 대한 자료구조를 모두 가져야합니다.
sop 기준 아래의 field 두개를 가져야합니다.
```java
new CollectionGetOperation.Callback() {
          private final Set<T> set = new HashSet<T>();
          private final Set<T> temp = new HashSet<T>();

```

즉, CollectionGetOperation 콜백마다 서로다른 자료구조 Field를 
가지게 될 것이고 추후에 callback을 익명 클래스가 아닌 구체 클래스로
변경할 경우 현재 CollectionGetFuture와 동일하게 4개의 구현체를 가져야합니다.

callback을 익명클래스로 사용할 경우엔 위 방법이 더 간결합니다.

2023-08-08 03:13 UTC, jhpark816 reviewed
리뷰 완료

2023-08-08 03:13 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +            }
아래 코드가 간단해 보입니다.
```java
            if (result.isEmpty() && !cachedData.isEmpty()) {
              for (CachedData data : cachedData) {
                result.add(tc.decode(data));
              }
            }
```

2023-08-08 03:13 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/CollectionGetFuture.java
> +    return result;
아래 코드가 간단해 보입니다.
```java
    T result = super.get(duration, units);
    if (result != null && result.isEmpty()) {
      Callback callback = (Callback) op.getCallback();
      callback.addResult();
    }
    return result;
```

2023-08-08 03:13 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/CollectionGetFuture.java
> +          throws InterruptedException, TimeoutException, ExecutionException {
인자 없는 get() 메소드 추가 필요

2023-08-08 03:14 UTC, jhpark816 commented
@uhm0311 @oliviarla 리뷰 바랍니다.

2023-08-08 03:18 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/CollectionGetFuture.java
> +          throws InterruptedException, TimeoutException, ExecutionException {
CollectionGetFuture의 get() 호출로 인해 super 클래스의 get()을 호출되어도
오버라이드된 CollectionGetFuture의 get(long, TimeUnit)을 호출하기에
인자가 없는 get() 메서드는 구현하지 않아도 됩니다.

2023-08-08 03:28 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/CollectionGetFuture.java
> +          throws InterruptedException, TimeoutException, ExecutionException {
@brido4125 
응용에게 OperationFuture 리턴하므로, OperationFuture.get() 호출됩니다.
이 경우에도 CollectionGetFuture.get(long, TimeUnit) 호출되나요?

2023-08-08 03:33 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/CollectionGetFuture.java
> +          throws InterruptedException, TimeoutException, ExecutionException {
넵 오버라이드된 메서드가 호출됩니다.
아래는 테스트 코드입니다.

```java
public class Parent {

  public void doSomething() {
    doSomething("without parameter");
  }

  public void doSomething(String text) {
    System.out.println("doSomething in parent" + text);
  }
}
```

```java
public class Child extends Parent {

  @Override
  public void doSomething(String text) {
    System.out.println("doSomething in child" + text);
  }
}
```
아래 테스트 실행 시 `doSomething in child without parameter`가 출력됩니다.
```java
@Test
  void mainTest() {
    Parent child = new Child();
    child.doSomething();
  }
```

2023-08-08 03:40 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/CollectionGetFuture.java
> +    return result;
result의 경우 제네릭 T 타입이라 isEmtpy를 사용할 수 없습니다.
해당 사항 제외하고 반영하겠습니다.
제외하여도 콜백에서 Empty 검사를 진행합니다.

2023-08-08 04:37 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +              for (CachedData cd : cachedData) {
일관적인 변수명이 필요한 것 같습니다.
1. for (CachedData cachedData : `cachedDataList | cachedDataSet | cachedDataMap`)
2. for (CachedData data : cachedData)

2023-08-08 04:37 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          public void addResult() {
가장 마지막에 호출되는 콜백이라는 의미에서 addResult() 메소드를 가장 아래쪽에 위치시키는 것은 어떨까요?

2023-08-08 10:55 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +              for (CachedData data : cachedDataList) {
왼쪽 변수명을 의미했던 것입니다. 어디는 cd이고 어디는 data이고 어디는 cachedData입니다.

2023-08-09 01:41 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +              for (CachedData data : cachedDataList) {
list,set의 경우는 cachedData
Map의 경우는 cachedDataEntry로 통일했습니다.

2023-08-09 02:04 UTC, jhpark816 reviewed
리뷰 완료

2023-08-09 02:13 UTC, brido4125 commented on src/main/java/net/spy/memcached/CachedData.java
> +   * @param data        the data
반영완료하였습니다.

2023-08-09 02:26 UTC, merged