FIX: change cancel method logic in OperationFuture.
naver/arcus-java-client pull request #639
Opened 2023-07-14 07:27 UTC by brido4125

## 관련 이슈
https://github.com/jam2in/arcus-works/issues/419

## Motivation
기존의 단일 Op를 가지는 Future의 cancel 로직은 아래와 같은 문제가 있다.

아래의 세가지 경우를 고려하지 않고 
모든 case에 대해 op.cancel()을 호출시킨다.
그리고 `OperationState.WRITE_QUEUED`를 기준으로
cancel()의 성공 및 실패 여부를 알려준다.

- op 진행 전 cancel() 요청
- op 진행 중 cancel() 요청
- op 완료 후 cancel() 요청

만약 op가 완료 된 후, cancel() 요청이 들어올 경우
응답값은 false로 정상적으로 돌려준다.
하지만 cancel() 요청 후, get() 메서드를 호출할 경우엔 
`ExecutionException`을 발생시킨다.
**즉, 작업의 완료로 인해 cancel이 실패하였음에도 
cancel에 의한 예외가 발생한다.**

## 변경 후 로직
- op 진행 전 cancel() 요청 : return True, ExecutionException 발생
    - op의 state : `OperationState.WRITE_QUEUED`
- op 진행 중 cancel() 요청 : return True, ExecutionException 발생
    - op의 state : `OperationState.READING` , `OperationState.WRITING`
- op 완료 후 cancel() 요청 : return False, Future의 get() 호출 시 정상 응답
    - op의 state : `OperationState.COMPLETE`

2023-07-14 08:31 UTC, uhm0311 requested changes

2023-07-14 08:31 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/OperationFuture.java
> +    if (op.getState().equals(OperationState.COMPLETE)) {
enum이니까 == 연산으로 비교해도 됩니다.

2023-07-14 08:31 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/OperationFuture.java
> +            op.isCancelled() || op.getState() == OperationState.COMPLETE;
두 메소드에 변경 사항이 없어 보입니다. 원래 있던 위치에 놓아주세요.

2023-07-14 08:35 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/OperationFuture.java
> +            op.isCancelled() || op.getState() == OperationState.COMPLETE;
생성자 -> 오버라이드된 메서드 -> 인스턴스 메서드 순으로
다른 Future에서도 메서드 정렬 방식을 가져가고 있어서 유지하려고 합니다.

2023-07-14 08:51 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/OperationFuture.java
> +            op.isCancelled() || op.getState() == OperationState.COMPLETE;
그 변경사항은 현재 커밋 메세지에 어울리지 않으니, 다른 PR로 반영하도록 합시다.

2023-07-17 09:38 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/OperationFuture.java
> +            op.isCancelled() || op.getState() == OperationState.COMPLETE;
변경 완료하였습니다.

2023-07-17 09:44 UTC, uhm0311 approved these changes

2023-07-17 09:45 UTC, jhpark816 reviewed
리뷰 완료

2023-07-17 09:45 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/OperationFuture.java
> +    return op.getState() != OperationState.COMPLETE;
`return true;` 해도 될 것 같은 데, getState() 다시 확인하는 이유가 있나요?

2023-07-17 10:07 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/OperationFuture.java
> +    return op.getState() != OperationState.COMPLETE;
`return true`로 변경하는게 더 이해하기 쉬울것 같습니다

2023-07-17 11:05 UTC, merged