INTERNAL: Change parsing itemHeader logic in CollectionGetOpImpl.
naver/arcus-java-client pull request #661
Opened 2023-08-25 07:32 UTC by brido4125

## 관련 이슈
https://github.com/jam2in/arcus-works/issues/433

## Motivation
기존 item Header를 파싱하는 로직은
handleRead 내에서 eFlag 유무와 eachRecordParseCompleted()의 여부에 따라
decodeItemHeader를 2번 호출하는 복잡한 로직이다.
이러한 로직을 버퍼로부터 데이터를 받고 space를 만날 때 마다
파싱 대상을 String 단위로 `List<String>`에 추가해주고
해당 List의 길이를 통해 eFlag 여부를 확인하도록 변경한다.

## 주요 변경 사항
- 슈퍼 클래스인 CollectionGet에 추상 메서드 `decodeItemHeader(List<String>)` 생성
- 이의 구현체들 중 sopGet,bopGet,lopGet,MopGet은 위 함수를 통해 handleRead() 로직 수행
- 나머지 BTreeFPG 등은 위 함수의 구현 없이 기존 `decodeItemHeader(String)`를 통해 로직 수행
- BTreeFPG 등은 컴파일 에러 방지를 위해 함수 선언과 비어있는 body로 구현되어 있음
- 이는 해당 PR이 merge되고 나서 점진적으로 변경 예정

2023-08-25 11:38 UTC, uhm0311 requested changes

2023-08-25 11:38 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +  protected final List<String> args = new ArrayList<String>();
전체적으로 arg와 args라는 변수명 대신 token과 tokens라는 변수명을 사용합시다.

2023-08-25 11:38 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +    boolean hasEFlag = false;
if (lookingFor == '\0' && data == null) 문 내에서만 쓰이므로 그 안으로 넣읍시다.

2023-08-25 11:38 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> -
Empty Line 복구

2023-08-25 11:38 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +        // Doesn't write space to byteBuffer
위에 Empty Line 추가해주세요.
"Space is not needed when decoding item header"가 더 맞는 표현인 것 같습니다.

2023-08-25 11:38 UTC, uhm0311 commented on src/main/java/net/spy/memcached/collection/ListGet.java
> +  @Override
위에 Empty Line 추가

2023-08-25 11:38 UTC, uhm0311 commented on src/main/java/net/spy/memcached/collection/SetGet.java
> +  @Override
위에 Empty Line 추가

2023-08-30 00:57 UTC, jhpark816 reviewed
일부 리뷰

2023-08-30 00:57 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +          args.add(arg);
기본적으로 여기서 tokenize하는 방식이 좋네요.
```
tokens.add(byteBuffer.toString());
byteBuffer.reset();
```

tokens.size()가 있으니, spaceCount도 필요 없을 것 같습니다.

여기 코드를 간결히 잘 정리해 보면 좋겠습니다.

그리고, get by position, find position with get, ... 등도 함께 수정하여 decodeItemHeader(Stirng)  메소드는 제거하는 것이 좋겠습니다.

2023-09-01 01:55 UTC, brido4125 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +          args.add(arg);
get by position 등의 나머지 연산들은 해당 로직 merge되면 반영하겠습니다.

2023-09-04 02:06 UTC, jhpark816 reviewed
리뷰 완료

2023-09-04 02:06 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +          if (collectionGet.headerReady(tokens.size())) {
headerReady()  메소드에  eflag 존재 여부를 나타내는 인자를 추가하는 것이 자연스러운 형태가 되지 않나 생각해요.

필요하다면, 용어 변경
- headerReady() =>  elemHeaderReady()  or isElemHeaderReady()
- decodeItemHeader() => decodeElemHeader()

2023-09-04 02:06 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +            break;
위의  element header  파싱 로직이
다른 경우들에도  동일히게 적용할 수 있는 지를 확인해 주기 바랍니다.
-  get by position
- ...

2023-09-04 03:00 UTC, uhm0311 requested changes

2023-09-04 03:00 UTC, uhm0311 commented on src/main/java/net/spy/memcached/collection/BTreeGet.java
> +  public void decodeItemHeader(List<String> args) {
decodeItemHeader()의 인자 명 `args` -> `tokens`로 변경합시다.

2023-09-04 03:25 UTC, brido4125 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +            break;
아래 두가지 api는 동일하게 적용 가능합니다.
- get by position
- find position with get

2023-09-04 05:47 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +          if (!tokens.isEmpty() && token.startsWith("0x")) {
코드로 표현해 보면 아래와 같습니다.
2가지 데이터가 추가되어야 하며, op 생성 시에 초기화되어야 합니다.
- eFlagPosition
   - `-1`: eflag 지원하지 않는 경우
   - `>= 0` : eflag 지원하는 경우 element 응답애서 eflag 위치
- elem header count
   - curElemHeaderCount : 현재 element 응답에서 확인한 elem header count
   - dftElemHeaderCount : eflag 없을 경우의 elem header count

```java
        if (b == ' ') {
          tokens.add(byteBuffer.toString());
          byteBuffer.reset();

          if (eFlagPosition >= 0 && eFlagPosition+1 == tokens.size()) {
             if (tokens.get(eFlagPosition).startsWith("0x")) {
               curElemHeaderCount++;
             }
          }

          if (tokens.stize() == curElemHeaderCount) {
            collectionGet.decodeItemHeader(tokens);
            data = new byte[collectionGet.getDataLength()];
            curElemHeaderCount = dftElemHeaderCount; // reset curElemHeaderCount
            break;
          }
        }
```

2023-09-04 07:37 UTC, uhm0311 commented on src/main/java/net/spy/memcached/collection/BTreeGet.java
> +  public void decodeItemHeader(List<String> args) {
다른 클래스의 메소드에도 모두 적용해주세요.

2023-09-04 07:47 UTC, jhpark816 reviewed
리뷰 완료

2023-09-04 07:47 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +            break;
다른  api  들도 동일하게 적용 가능한 지를 함께 검토해 주시죠.
기존 decodeItemHeader() 호출한 모든 경우를 살펴보면 됩니다.

2023-09-04 07:47 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +    this.currElemCount = collectionGet.getDefaultElemCount();
ElemCount 는  `# of elements` 의미하므로, 혼돈되는 용어입니다.

아래 용어가 어떤가요 ?
- eHeadCount  : element  응답에서  header token count
- eFlagIndex : eHeadCount 에서 eflag  값의  index

 결국,  아래와 같이 수정하면 좋겠습니다.

```java
this.eHeadCount = collectionGet.getEHeadCount();
```

2023-09-04 07:47 UTC, jhpark816 commented on src/main/java/net/spy/memcached/collection/BTreeGet.java
> +    this.eFlagIndex = 1;
eHeadCount 필드가 eFlagIndex 위에 위치하면 좋겠습니다.

2023-09-04 07:47 UTC, jhpark816 commented on src/main/java/net/spy/memcached/collection/CollectionGet.java
> +  protected int eFlagIndex;
eHeadCount를 eFlagIndex  위로 이동

2023-09-04 07:47 UTC, jhpark816 commented on src/main/java/net/spy/memcached/collection/CollectionGet.java
> +    return defaultElemCount == spaceCount;
headerReady() 함수도 필요없지 않나 생각해요.

2023-09-04 07:47 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +          }
여기서  continue 하면 될 것 같습니다.

2023-09-04 08:46 UTC, brido4125 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +            break;
모든 경우 가능합니다.
현재 PR 구조 동의하시면
위 코멘트의 두 api에도 적용하겠습니다.

2023-09-04 08:56 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +            break;
아래  api도 힘께 검토해야 하지 않나요?
- btree get bulk
- btree insert and get
- btree smget

2023-09-04 09:11 UTC, jhpark816 reviewed
리뷰 완료

2023-09-04 09:11 UTC, jhpark816 commented on src/main/java/net/spy/memcached/collection/CollectionGet.java
> +  public int geteHeadCount() {
메소드 명을 getEHeadCount()로 하시죠.

2023-09-04 09:11 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +          }
이 위치에서 `continue;` 문장을 넣어, 아래 수정을 하지 않는 것이 좋겠다는 말입니다.

```java
        // Space is not needed when decoding item header
        if (b != ' ') {
          byteBuffer.write(b);
        }
```

2023-09-04 09:11 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> -
1개  empty line 그대로 유지

2023-09-04 09:11 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +            break;
나머지  api 도 함께 수정하는 것이 consistent 수정 내역을 유지하기에 나은 것 같습니다.

2023-09-04 23:53 UTC, brido4125 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +            break;
위 3가지 api는 collectionGet 클래스를 상속받는 클래스를 사용하지 않습니다.

2023-09-04 23:54 UTC, brido4125 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +            break;
별개의 Get클래스라 별도의 PR로 진행하겠습니다.

2023-09-05 03:24 UTC, jhpark816 reviewed
리뷰 완료

2023-09-05 03:24 UTC, jhpark816 commented on src/main/java/net/spy/memcached/collection/BTreeGetByPosition.java
>    private int bytes;
여기 bytes 데이터도 필요 없으면 제거하시죠.

2023-09-05 03:24 UTC, jhpark816 commented on src/main/java/net/spy/memcached/collection/ListGet.java
> +  public void decodeElemHeader(String itemHeader) {
String 인자를 가지는 메소드가 아직 필요한 상태인가요?

2023-09-05 09:48 UTC, jhpark816 commented
@brido4125 
준비 다 되었으면 @uhm0311 님에게 리뷰 요청하시죠.

2023-09-06 05:31 UTC, jhpark816 reviewed
리뷰 완료

2023-09-06 05:31 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionWithGetOperationImpl.java
> +          if (eFlagIndex > 0) {
조건이 `eFlagIndex >= 0` 이면 좋겠습니다.

2023-09-06 05:31 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
> +        // Space is not needed when decoding item header
위의 주석은 없어도 알 것 같습니다.

2023-09-06 05:31 UTC, jhpark816 commented on src/main/java/net/spy/memcached/collection/CollectionGet.java
> +  public abstract void decodeElemHeader(List<String> itemHeader);
인자명을 tokens로 변경합시다.

2023-09-06 05:31 UTC, jhpark816 commented on src/test/manual/net/spy/memcached/MultibyteKeyTest.java
> +        public void decodeElemHeader(List<String> itemHeader) {
인자명을 tokens로 변경합시다.

2023-09-06 07:02 UTC, jhpark816 commented
@uhm0311 
현재 merge합니다. 수정 코드 확인하고 문제 있으면 알려주세요.

2023-09-06 07:02 UTC, merged