INTERNAL: Refactor bopBulkGet API logic.
naver/arcus-java-client pull request #675
Opened 2023-09-15 08:01 UTC by brido4125

## Motivation
btreeGetBulk API의 내부 패턴이 다른 API들과 통일 되도록 변경한다.
기존에는 rv를 생성하지 않고 return문에서 Future를 생성하여 리턴하는 패턴이다.

2023-09-15 08:48 UTC, jhpark816 commented
구현 패턴 논의가 먼저 결정되어야 할 것 같습니다.

2023-09-17 23:58 UTC, brido4125 commented
https://github.com/jam2in/arcus-works/issues/428

위 코멘트에서 논의된 아래와 같은 패턴을 사용하지 않나요?
```java
void asyncSomeApi(//...){
	SomeFuture<Result> rv = new SomeFuture<Result>(//Parameters need to rv);
	Operation op = opFact.someOp(
		new SomeCallback(){
			@Override
			public void recevivedStatus(OperationStatus status){
				//...
			}

			// implementaion other abstract method ...
		}
	)
	rv.setOperation(op);
	addOp(k, op); //Allocation op to MemcachedNode by Key.
	return rv;
}

```

2023-12-20 08:13 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java
> +  private final Collection<Operation> ops =  new LinkedList<Operation>();
ops.add()의 성능은 ArrayList가 더 낫지 않을까요?

2024-01-02 11:52 UTC, jhpark816 commented
@brido4125 @uhm0311 PR 리뷰 및 처리 바랍니다.

2024-01-05 02:26 UTC, uhm0311 requested changes

2024-01-05 02:26 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    CollectionGetBulkFuture<Map<String, BTreeGetResult<Long, T>>> rv
final을 붙이지 않은 이유는 final을 붙이면 변수 선언만 해도 너무 길어져서 Checkstyle 오류가 나기 때문인가요?

2024-01-05 02:26 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java
> +  private final Collection<Operation> ops =  new ArrayList<Operation>();
ArrayList 객체 생성을 이 클래스의 생성자 내에서 latch.getCount() 인자를 주어 생성하면 Operation이 많이 들어올 때 ArrayList 크기를 늘리는 로직을 수행하지 않아도 됩니다.

2024-01-05 07:29 UTC, uhm0311 requested changes

2024-01-05 07:29 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java
> +    ops = new ArrayList<Operation>((int) latch.getCount());
this.ops로 this를 붙여줍시다.

2024-01-05 07:50 UTC, uhm0311 approved these changes

2024-01-08 04:29 UTC, jhpark816 commented
@brido4125 
기존 구현 패턴이 읽기 나은 것 같습니다.

@oliviarla @uhm0311 
구현 패턴에 대해 의견이 어떤가요?

2024-01-08 05:09 UTC, uhm0311 commented
@jhpark816 

기존 구현 패턴으로 유지한다고 하면 어느 한 쪽으로 통일하지 않고 원래 패턴과 현재 PR의 패턴이 혼용된 상태로 API들이 존재하게 되는 것인가요?

2024-01-08 05:27 UTC, jhpark816 commented
@uhm0311 
현재까지 괜찮다고 정리된 구현 패턴은 2가지가 있으며,
2가지를 모두 유지할 지 아니면 1가지로 통일할 지는 검토할 대상입니다.
대표 연산에 대해 구현 패턴의 가능성, 장단점을 살펴보면 되지 않나 생각합니다.

참고로, bopBulkGet과 bopSortMergeGet에서 
latch, ops, result, timeout 인자로 future 생성하여 리턴하는 패턴은 
result 생성에서 futue 연관성이 없어 읽기가 쉽습니다.

2024-01-08 05:49 UTC, oliviarla commented
@jhpark816 
`현재까지 괜찮다고 정리된 구현 패턴은 2가지`를 어디에서 확인할 수 있나요?

2024-01-08 06:12 UTC, jhpark816 commented
@oliviarla 
아래 이슈를 참고하면 되는 데, 지금 보니 현재 정리 및 논의 중인 것 같습니다.
https://github.com/jam2in/arcus-works/issues/428

@brido4125 
위의 이슈를 확인하고, 추가 정리할 부분이 있다면 정리 바랍니다.

2024-01-10 02:07 UTC, jhpark816 commented
latch, ops, result로 Future 객체를 만들어 리턴하는 패턴을 그대로 유지하기로 했습니다.

2024-01-10 02:07 UTC, closed without merging