INTERNAL: Refactor transcoder compress logic.
naver/arcus-java-client pull request #691
Opened 2023-11-10 04:47 UTC by brido4125

## Motivation
https://github.com/jam2in/arcus-works/issues/453
위 이슈에 언급된 것처럼 현재 Transcoder는 너무 많은 관심사를
하나의 클래스가 가지고 있습니다.
점진적으로 관심사들을 분리하는 작업을 진행할 예정입니다.

해당 PR은 compress 로직을 
Compressior라는 클래스가 수행하도록 변경하였습니다.

2023-11-10 05:22 UTC, uhm0311 requested changes

2023-11-10 05:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/BaseSerializingTranscoder.java
> +    compressor = new Compressor();
확장성을 위해서 compressor를 생성자에서 항상 할당하지 말고, 생성자로 받는 오버로딩을 하나 둡시다.
BaseSerializingTranscoder 클래스를 상속 받는 클래스에서도 오버로딩 생성자를 두고요.

```java
public BaseSerializingTranscoder(int max, Compressor compressor) {
  ...
}

public BaseSerializingTranscoder(int max) {
  this(max, new Compressor());
}
```

2023-11-10 05:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/SerializingTranscoder.java
> +    if (compressor.getCompressionThreshold() < b.length) {
`데이터 크기가 기준보다 클 때`라는 관점에서 기존의 비교 순서가 더 낫습니다.

2023-11-10 05:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/Compressor.java
> +    System.out.println("Compressor.compress");
디버그용 코드가 들어갔습니다.

2023-11-10 05:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/Compressor.java
> +public class Compressor extends SpyObject {
Compressor도 확장 가능한 형태로 합시다.
```java
public interface Compressor {
  ...
}

public class DefaultCompressor or GZIPCompressor implements Compressor {
  ...
}
```

2023-11-10 05:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/SerializingTranscoder.java
> -        getLogger().debug("Compressed %s from %d to %d",
기존의 로그도 그대로 두시죠.
다만 if문을 3단계로 나누어야 할 것 같습니다.

```java
if (compressed.length < b.length) {
  ...
} else if (compressed.length > b.length) {
  ...
} else { // compressed.length == b.length
  ...
}
```

2023-11-10 05:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/Compressor.java
> +  public byte[] compress(byte[] in, String objectType) {
objectType은 Compressor가 관여할 일이 아니라고 생각합니다.
기존 위치에서 압축 관련 로그를 출력하도록 하면 objectType을 받을 필요가 없게 됩니다.

2023-11-10 05:41 UTC, brido4125 commented on src/main/java/net/spy/memcached/transcoders/SerializingTranscoder.java
> -        getLogger().debug("Compressed %s from %d to %d",
`compressed`가 작은 경우와
그렇지 않은 경우(압축을 해도 크기 감소에 효과가 없는 경우) 둘로만 나누어도 되지 않나요?

2023-11-10 05:44 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/SerializingTranscoder.java
> -        getLogger().debug("Compressed %s from %d to %d",
```java
getLogger().info(
                "Compression increased the size of %s from %d to %d",
                o.getClass().getName(), b.length, compressed.length);
```

실제로는 늘어나지 않았는데 늘어났다고 로깅하는 것보단 늘어난 경우엔 늘어났다고, 그대로인 경우엔 그대로라고 로깅하는 게 나을 것 같습니다.

2023-11-10 06:22 UTC, uhm0311 requested changes

2023-11-10 06:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/BaseSerializingTranscoder.java
> +    this.compressor = compressor;
사용자가 null을 넘겨줄 수도 있습니다.
이 경우 2가지 선택이 가능합니다.
1. NullPointerException 발생
2. null이면 압축 하지 않음

2023-11-10 06:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/WhalinV1Transcoder.java
> +    if (b.length > compressor.getCompressionThreshold()) {
동일 로직이 3개의 클래스에 분리되어 있으므로, BaseSerializingTranscoder 클래스에 공통 처리할 메소드를 만듭시다.
```java
protected byte[] compress(byte[], Class<?> type)
```

2023-11-10 06:26 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/WhalinV1Transcoder.java
> +    if (b.length > compressor.getCompressionThreshold()) {
이게 더 낫겠네요.

```java
protected CachedData compress(byte[] data, int flags, Class<?> type)
```

2023-11-10 06:45 UTC, brido4125 commented on src/main/java/net/spy/memcached/transcoders/BaseSerializingTranscoder.java
> +    this.compressor = compressor;
압축 관련 로직을 수행하지 않도록 변경하였습니다.

2023-11-10 06:51 UTC, uhm0311 requested changes

2023-11-10 06:51 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/BaseSerializingTranscoder.java
> +    this.compressor = compressor;
BaseSerializingTranscoder 클래스를 상속 받는 클래스에서 compressor.decompress()를 null 체크 없이 호출하고 있습니다.
BaseSerializingTranscoder 클래스에 `protected byte[] decompress(byte[] data)`를 추가해서 null 체크를 하고 압축 해제를 하도록 합시다.
그러면서 compressor는 private 필드로 만들어서 하위 클래스에서 null 체크를 할 필요가 없도록 만들고요.
setCompressionThreshold() 메소드에서도 null 체크가 필요합니다.

2023-11-10 06:51 UTC, uhm0311 commented on src/test/java/net/spy/memcached/transcoders/BaseSerializingTranscoderTest.java
> +      ex.compressor.compress(null);
compressor를 private 필드로 바꾸면 직접 접근이 불가능할테니, 테스트 코드도 Exposer 객체의 compressor 필드를 테스트하는 것이 아니라, Compressor 객체의 메소드를 테스트하는 것으로 바꾸어야 합니다.

2023-11-10 08:08 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/BaseSerializingTranscoder.java
> +      return;
이 정도면 충분할 것 같습니다.

```java
if (compressor != null) {
  compressor.setCompressionThreshold(to);
}
```

2023-11-10 08:08 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/BaseSerializingTranscoder.java
> +    maxSize = max;
`this(max, new GzipCompressor())`로 하지 않은 이유가 특별히 있나요?

2023-11-10 08:08 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/GzipCompressor.java
> +  private int compressionThreshold = DEFAULT_COMPRESSION_THRESHOLD;
생성자로 값을 받을 수 있도록 합시다.
인자가 없는 생성자에선 DEFAULT_COMPRESSION_THRESHOLD로 대입하고, 인자가 있는 생성자에선 인자를 대입하면 되겠죠.

2023-11-13 02:32 UTC, uhm0311 approved these changes

2023-11-13 06:16 UTC, uhm0311 requested changes

2023-11-13 06:16 UTC, uhm0311 commented on src/main/java/net/spy/memcached/transcoders/SerializingTranscoder.java
> +  public SerializingTranscoder(Compressor compressor) {
SerializingTranscoder 클래스를 상속 받는 클래스에도 Compressor 관련 생성자 오버로딩을 추가합시다.
BaseSerializingTranscoder 클래스가 조상 클래스인 경우가 있다면 모두 Compressor 관련 생성자 오버로딩을 추가해주세요.

2023-11-14 00:29 UTC, brido4125 commented on src/main/java/net/spy/memcached/transcoders/SerializingTranscoder.java
> +  public SerializingTranscoder(Compressor compressor) {
`InspectObjectSizeTranscoder`와 `CollectionTranscoder`에도 Compressior를 인자로 받는 생성자 추가하였습니다.

2023-11-14 02:03 UTC, uhm0311 approved these changes

2025-06-13 01:35 UTC, oliviarla commented
https://github.com/naver/arcus-java-client/pull/922 여기서 merge되었으므로 close하겠습니다.

2025-06-13 01:35 UTC, closed without merging