INTERNAL: Remove transcoder service logic in bulkGet apis.
naver/arcus-java-client pull request #710
Opened 2023-12-28 07:47 UTC by brido4125

## 변경 사항
asyncGetBulk, asyncGetsBulk 연산에서 TranscoderService를 사용하지 않고
decode()를 WAS의 worker thread 수행하도록 변경하였습니다.

기존 테스트 코드에서는 테스트 코드의 메인 쓰레드가 decode될 동안 Blocking이 되어 IO 스레드로부터`ExecutionException e`이 발생하였고, 
현재 구현에서는 테스트 메인 쓰레드에서 AssertionError가 발생하기 때문에 Throwable를 인자로 받도록 변경하였습니다.

2023-12-28 08:31 UTC, uhm0311 requested changes

2023-12-28 08:31 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/GetResult.java
> +  public GetResult() {
이 생성자를 지우고 CASGetResult 클래스의 생성자에서 super(tc)를 호출합시다.

2023-12-28 08:31 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/GetResult.java
> +  private Transcoder<T> transcoder;
그러면 여기도 final을 다시 붙여야겠죠.

2023-12-28 08:31 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +  private final Transcoder<T> tc;
super 클래스의 필드가 protected로 변경되었으므로 super 클래스의 tc를 사용합시다.

2023-12-28 08:31 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +    if (decodedValue == null) {
super 클래스와 동일한 Empty Line을 넣어주세요.
이 라인 아래에도 마찬가지입니다.

2023-12-28 08:31 UTC, uhm0311 commented on src/test/java/net/spy/memcached/ProtocolBaseCase.java
> +    } catch (Throwable t) {
TestWithKeyTranscoder 클래스가 어떤 역할을 하는 클래스이고, 왜 AssertError가 발생하는지 설명 바랍니다.

그리고 단순히 Throwable로 퉁치는 것은 AssertError가 아닌 다른 종류의 Exception(예를 들면 NullPointerException)이 발생했을 때 실제로는 테스트 코드가 실패한 것이지만 Throwable은 모든 Exception과 Error를 포함하는 타입이므로 테스트 성공으로 간주될 수 있습니다.
어떤 종류의 AssertError가 발생하는지 확인하고, 최대한 자세한 타입으로 변경하도록 합시다.

2023-12-28 08:31 UTC, uhm0311 commented on src/test/java/net/spy/memcached/ProtocolBaseCase.java
>        fail("Expected ExecutionException caused by key mismatch");
발생하는 Exception의 종류가 달라졌다면 이 메세지도 변경되어야 합니다.
이 테스트 메소드 뿐만 아니라, 다른 하나의 테스트 메소드도 마찬가지입니다.

2023-12-28 23:37 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/GetResult.java
> +  public GetResult() {
슈퍼 클래스의 생성자를 호출하지 않은 이유는 아래와 같습니다.
현재 `CASGetResult<T>`는 `GetResult<CASValue<T>>` 타입을 상속 받습니다.
`super(tc)`를 호출 할 경우, `Transcoder<T>` 타입이 아니라, `Transcoder<CASValue<T>>` 타입으로 tc의 타입이 정해집니다.
즉, 사용자가 정의한 타입이 아닌 트랜스코더 타입이 필요해집니다.
결국 말씀하신 변경은 CASGetResult 생성자가 주입 받는 tc 인자 타입과 실제로 슈퍼 클래스가 필요한 인자 타입이 서로 달라 컴파일 에러가 발생하게 됩니다.

이를 방지하기 위해, 슈퍼 클래스의 tc를 사용하지 않고 CASGetResult에 별도의 tc를 두어 사용하였습니다.

2024-01-02 02:14 UTC, uhm0311 requested changes

2024-01-02 02:14 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/GetResult.java
> +  private Transcoder<T> transcoder;
final을 다시 붙일 3가지 방법이 있습니다.

1. 자식 클래스 생성자에서 super(null)을 호출
2. `GetResult<T, V>`로 Transcoder에 들어갈 타입과 getDecodedValue()가 반환할 타입을 따로 받는 방법
3. cas 값과 원래 tc를 생성자로 받고 `CASValue<T>` 타입을 반환하는 커스텀 Transcoder 객체 생성하여 super(tc)의 인자로 주는 방법

2024-01-02 02:14 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/GetResult.java
> +  public GetResult() {
final을 다시 붙이면 이 생성자는 필요 없게 됩니다.

2024-01-02 02:14 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/GetResult.java
>    private volatile T decodedValue = null;
decodedValue를 protected로 변경합시다.

2024-01-02 02:14 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +  private volatile T decodedValue = null;
그러면 여기 decodedValue는 필요 없게 됩니다.

2024-01-02 02:14 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +    return new CASValue<T>(cas, decodedValue);
이러한 형태는 사용자가 Future.get()을 호출할 때마다 새로운 CASValue 객체가 생성되게 됩니다.
super.decodedValue가 protected로 변경되면, `decodedValue == null`인 경우에 한해 `decodedValue = new CASValue<T>(...)`를 할당하고 반환하면 됩니다.

2024-01-02 02:14 UTC, uhm0311 commented on src/test/java/net/spy/memcached/ProtocolBaseCase.java
> +    } catch (AssertionFailedError e) {
AssertionFailedError가 가장 구체적인 클래스인가요?
AssertionFailedError 클래스의 자식 클래스가 2개 있는데, 이 둘 중 하나는 아닌가요?

2024-01-02 02:59 UTC, brido4125 commented on src/test/java/net/spy/memcached/ProtocolBaseCase.java
> +    } catch (AssertionFailedError e) {
리뷰사항 및 `super(null)`을 호출하는 방안을 반영하였습니다.

2024-01-02 03:07 UTC, uhm0311 requested changes

2024-01-02 03:07 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +    this.cas = cas;
위에 Empty Line 추가

2024-01-02 03:07 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +
Empty Line 제거

2024-01-02 03:07 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/GetResult.java
> -
원래 있던 Empty Line 복구

2024-01-02 03:32 UTC, uhm0311 approved these changes

2024-01-02 06:47 UTC, jhpark816 reviewed
리뷰 완료

2024-01-02 06:47 UTC, jhpark816 commented on src/main/java/net/spy/memcached/MemcachedClient.java
> +        result.setCachedData(cachedData);
아래와 같이 하시죠.
```java
result.setCachedData(new CachedData(flags, data, tc.getMaxSize()));
```

질문입니다. 이렇게 result 만드는 것은 어떤가요?

```
new GetReuslt<T>(flags, data, tc);
```

2024-01-02 06:47 UTC, jhpark816 commented on src/main/java/net/spy/memcached/MemcachedClient.java
> +        rvMap.put(k, result);
본 PR 이전에 asyncGets() 메소드 로직에서 transcoder service 제거하는 PR이 먼저 있어야 하지 않는 지?

2024-01-02 06:47 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +    super(null);
transcoder 넘기지 않는 이유는 무엇인가요?

2024-01-02 06:47 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +}
`CASGetResult` 없이 GetResult로 나타낼 방안이 있나요?

2024-01-02 08:54 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +    super(null);
https://github.com/naver/arcus-java-client/pull/710#discussion_r1437921170

참고하시면 됩니다.

2024-01-02 08:58 UTC, brido4125 commented on src/main/java/net/spy/memcached/MemcachedClient.java
> +        rvMap.put(k, result);
확인해보니 asyncGets는 TcService를 사용하지 않고, decode() 수행합니다.
추후 별도 PR로 처리하겠습니다.

2024-01-02 09:06 UTC, brido4125 commented on src/main/java/net/spy/memcached/MemcachedClient.java
> +        result.setCachedData(cachedData);
> 질문입니다. 이렇게 result 만드는 것은 어떤가요?

XXXResult 라는 객체가 asyncGet,BulkGet,smGet에서만 구현이 되어 사용되고 있습니다.
현재 단계에서는 최소한의 정보만 해당 클래스에 남겨두고
추후에 공통적으로 필요한 정보가 생기면 생성자의 인자로 두는게 좋을것 같습니다.

2024-01-02 10:10 UTC, jhpark816 reviewed
리뷰 완료

2024-01-02 10:10 UTC, jhpark816 commented on src/main/java/net/spy/memcached/MemcachedClient.java
> +        rvMap.put(k, result);
ok. tcService 사용하지 않으며, decode()를 IO thread가 수행하고 있네요.

Worker thread가 decode() 작업을 수행하도록 변경하는 PR을 먼저 보내주시죠.
이를 먼저 요청한 이유는 get 외에 
gets 결과를 리턴하는 방식을 일관되게 먼저 정리하고 나서,
bulk 연산을 다루는 것이 순서일 거라고 생각하기 때문입니다.

2024-01-02 10:10 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +}
GetResult 하나로 get, gets 결과를 모두 표현하는 코드를 예로 만들어 보고 판단하시죠.
get, gets 이든 get 연산이기 때문에 GetResult 하나로 표현하는 것이 낫다고 봅니다.

2024-01-03 07:53 UTC, brido4125 commented on src/main/java/net/spy/memcached/MemcachedClient.java
> +        rvMap.put(k, result);
`asyncGets`은 확인해보니 `asyncGet`과 달리 `OperationFuture` 타입을 리턴합니다.
현재는 아래와 같이 구현되어있습니다.
```java
public class OperationFuture<T> extends SpyObject implements Future<T> {
    //...
    protected final AtomicReference<T> objRef;
}
```


이를 아래처럼 변경하거나, asyncGets에서 GetFuture를 리턴하도록하는 방법도 존재합니다.
참고로 `AtomicReference<T> objRef`는 다른 api 연산들에서도 활용되기에 제거 할 수는 없습니다.
```java
public class OperationFuture<T> extends SpyObject implements Future<T> {
    //...
    protected final AtomicReference<T> objRef;
    protected final AtomicReference<GetResult<T>> result;
}
```

위 처럼 변경하면 다른 api들에서는 사용되지 않는 필드가 생기는것이고,
다른 선택지는 하위 호환성이 유지되지 않습니다.

저는 asyncGets가 `GetFuture`를 반환하는게 맞지않나 생각합니다.

@jhpark816 @uhm0311 
의견 부탁드립니다. 또는 다른 접근방법도 있으면 공유해주세요

2024-01-03 08:03 UTC, uhm0311 commented on src/main/java/net/spy/memcached/MemcachedClient.java
> +        rvMap.put(k, result);
CASValue 클래스를 GetResult 클래스처럼 사용할 수 있도록 수정하는 방법이 있습니다.

```java
public CASValue(long cas, Transcoder<T> tc)
```

이렇게 하면 CASGetResult 클래스는 제거해도 됩니다.
asyncGetsBulk 메소드 내의 결과를 담는 Map 객체를 다음과 같이 선언하면 됩니다.

```java
    final Map<String, CASValue<T>> rvMap
            = new ConcurrentHashMap<String, CASValue<T>>();
```

2024-01-04 00:42 UTC, brido4125 commented on src/main/java/net/spy/memcached/MemcachedClient.java
> +        rvMap.put(k, result);
@uhm0311 
asyncGets()의 경우 말씀하신 방안으로 변경하여도,
리턴하는 Future의 타입이 `OperationFuture`라서 앞선 코멘트의 문제가 해결되진 않습니다.

좀 더 자세히 설명드리면 아래와 같습니다.
`OperationFuture`의 get()을 호출할 경우 worker thread가 decode()가 수행되도록 변경이 필요합니다.
이를 위해 CASValue 또는 GetResult의 decode() 로직을 수행해야합니다.
즉, `OperationFuture` 내부에서 `CASValue` 또는 `GetResult`에 타입을 가지고 있어야 해당 메서드호출이 가능해집니다. (현재 `GetFuture` 구현처럼)
위와 같은 변경이 `OperationFuture`에 발생할 경우, `OperationFuture`을 사용하는 다른 API에서 사용되지 않는 필드 및 메서드 오버로딩이 이루어집니다.

또한 asyncBulkGets()가 아닌 asyncGets()로 한번 확인해주시면 감사하겠습니다.

2024-01-23 03:38 UTC, jhpark816 commented
@brido4125 수정 중인가요?

2024-01-23 04:23 UTC, brido4125 commented
넵 완료되면 노티 드리겠습니다.

2024-01-23 06:38 UTC, uhm0311 approved these changes

2024-01-23 08:41 UTC, jhpark816 commented on src/test/java/net/spy/memcached/ProtocolBaseCase.java
> +    } catch (ComparisonFailure e) {
@brido4125 
여기 수정은 tcService 제거와 무관하지 않나요?

2024-01-23 09:25 UTC, uhm0311 commented on src/test/java/net/spy/memcached/ProtocolBaseCase.java
> +    } catch (ComparisonFailure e) {
https://github.com/naver/arcus-java-client/pull/710#discussion_r1439112447

위 코멘트 참조 바랍니다.

2024-01-23 09:49 UTC, jhpark816 commented on src/test/java/net/spy/memcached/ProtocolBaseCase.java
> +    } catch (ComparisonFailure e) {
https://github.com/naver/arcus-java-client/pull/710#discussion_r1439112447

위 코멘트 설명이 관련되어 있는 것 같으면서도 조금 다른 것 같습니다.
`ComparisonFailure`에 관한 언급은 없는 것 같습니다.

2024-01-23 09:50 UTC, uhm0311 commented on src/test/java/net/spy/memcached/ProtocolBaseCase.java
> +    } catch (ComparisonFailure e) {
https://github.com/naver/arcus-java-client/pull/710#discussion_r1439121030

ComparisonFailure는 위 코멘트에 따라 변경되었습니다.
기존 테스트 코드와 다른 에러가 발생하여 수정한 것입니다.

2024-01-23 09:53 UTC, jhpark816 commented on src/test/java/net/spy/memcached/ProtocolBaseCase.java
> +    } catch (ComparisonFailure e) {
기존 unit testing에 문제가 없는 상태로 알고 있고,
이번 tcService 제거하는 PR에 의해 기존 테스트가 실패하게 된 것인가요?

2024-01-23 10:23 UTC, uhm0311 commented on src/test/java/net/spy/memcached/ProtocolBaseCase.java
> +    } catch (ComparisonFailure e) {
> tcService 제거하는 PR에 의해 기존 테스트가 실패하게 된 것인가요?

네 맞습니다.

2024-01-23 11:32 UTC, jhpark816 commented on src/test/java/net/spy/memcached/ProtocolBaseCase.java
> +    } catch (ComparisonFailure e) {
@uhm0311 @brido4125 
어떤 내용인지 확인했고, 대략 아래와 같이 이해합니다.
- 예전엔 tcService thread에 의해 decoding되고 AssertionError 발생하면 
  ExecutionException 던진 것으로 예상되고,
- 현재는 worker thread가 직접 decoding하기 때문에 AssertionError를 직접 받게 되는 것이군요.

아래는 assertEuqals() 설명 내용입니다.
여기에 나온대로 ComparisonFailure 대신에 AssertionError를 사용합시다.
AssertionError 사용해야 이해하기가 쉽습니다.

#############

assertEquals
public static void assertEquals([String](http://java.sun.com/javase/6/docs/api/java/lang/String.html) message,
                                long expected,
                                long actual)
Asserts that two longs are equal. If they are not, an [AssertionError](http://java.sun.com/javase/6/docs/api/java/lang/AssertionError.html) is thrown with the given message.

Parameters:
message - the identifying message for the [AssertionError](http://java.sun.com/javase/6/docs/api/java/lang/AssertionError.html) (null okay)
expected - long expected value.
actual - long actual value

2024-01-24 01:28 UTC, merged

2024-01-30 08:16 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/BulkGetFuture.java
> +    for (Map.Entry<String, GetResult<T>> me : rvMap.entrySet()) {
@oliviarla 

asyncGets가 아닌 asyncBulkGets 또는 asyncBulkGet 에서의 상황을 말씀하신거죠?
맞다면 코멘트 수정 부탁드려요

2024-01-30 08:17 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/BulkGetFuture.java
> +    for (Map.Entry<String, GetResult<T>> me : rvMap.entrySet()) {
아 맞습니다. gets를 헷갈렸네요. asyncBulkGet 이 맞습니다.
기존 tcService를 쓰면 여러 데이터를 순차적으로 decode하는 것이 아니라, 스레드풀의 스레드에 태스크를 맡기고 비동기적으로 여러 데이터를 decode할 수 있는 것이 맞나요?
만약 그렇다면 tomcat 스레드풀의 스레드가 지금과 같이 for문을 돌며 여러 데이터를 decode하게 되면 동기와 비슷한 형태가 되지 않을까 싶어서요.

2024-01-30 08:31 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/BulkGetFuture.java
> +    for (Map.Entry<String, GetResult<T>> me : rvMap.entrySet()) {
> 기존 tcService를 쓰면 여러 데이터를 순차적으로 decode하는 것이 아니라, 스레드풀의 스레드에 태스크를 맡기고 비동기적으로 여러 데이터를 decode할 수 있는 것이 맞나요?

스레드풀을 이용하니까 동시에 여러 decode 작업이 가능합니다.

제 의견은 다음과 같습니다.

bulkGet과 같은 요청이 만약 100개가 넘어가게 온다면, 
현재 쓰레드풀의 수(10)으로는 한번에 감당하지 못하고 대기가 발생하게 됩니다.
이 상황에서 asyngGet 요청이 발생하여 큐에서 디코딩 작업이 대기하면
해당 연산 자체가 타임아웃이 발생할 확률이 증가합니다.

TcService를 사용하지 않으면 말씀하것처럼 bulk 연산의 효율은 떨어지지만, 
최소한 bulk 요청을 진행 중일 때, 들어온 asyncGet 요청이 
타임아웃이 발생할 확률은 훨씬 줄일 수 있다고 볼 수 있습니다.

**즉, 연산이 늦어지는것과 타임아웃이 발생하는 것 중
선택해야한다면 전자를 선택해야하지 않나 생각합니다.**

그러면 bulk 연산을 위해 tcService의 쓰레드풀의 수를 늘리는게 어떠냐? 라는 반문의 경우
자주 사용되지 않는 스레드를 항시 유지하는 리소스 또한 크기 때문에 추천되지 않는다고 생각합니다. 
아무래도 asyncGet 연산이 asyncBulkGet 보다는 많이 사용될테니까요

2024-01-30 09:37 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/BulkGetFuture.java
> +    for (Map.Entry<String, GetResult<T>> me : rvMap.entrySet()) {
나중에 사용자가 직접 Executor를 만들어 인자로 입력하는 API 제공하는 등 더 나은 방법을 논의하면 좋을 것 같습니다.

2024-01-30 11:27 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/BulkGetFuture.java
> +    for (Map.Entry<String, GetResult<T>> me : rvMap.entrySet()) {
@oliviarla @brido4125 @uhm0311 
OK. 이에 대해 별도로 offline 논의하시죠.