INTERNAL: Change asycnGets return future type.
naver/arcus-java-client pull request #711
Opened 2024-01-04 08:36 UTC by brido4125

## 변경 사항
- 오전에 오프라인으로 논의된 asyncGets API의 Future 리턴 타입을 `OperationFuture` -> `GetFuture`로 변경하였습니다.
- 아래의 코멘트의 Transcoder 문제 때문에 `CASGetResult<T>`를 사용해서 구현하였습니다.
  - https://github.com/naver/arcus-java-client/pull/710#discussion_r1437921170
- 이를 해결하기 위해 해당 PR은 생성자 내에서 `super(null)`을 사용하였습니다. 아래 코멘트는 다른 방안들입니다.
  - https://github.com/naver/arcus-java-client/pull/710#discussion_r1439119905
- `@Deprecated`를 사용하려면 `asyncGetsNew()` 와 같은 새로운 함수를 정의하고 `asyncGets()`에 어노테이션을 붙여줘야합니다. 메서드의 리턴값만 다를 경우 오버로딩이 적용되지 않기 때문입니다. 우선은 로직에 대한 리뷰를 먼저 받기 위해 기존 메서드의 리턴값을 바로 변경하였습니다. 

- GetResult 생성자에서 CachedData를 외부로부터 주입 받는 로직은 별도의 PR로 반영하겠습니다.

2024-01-04 09:12 UTC, uhm0311 requested changes

2024-01-04 09:12 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +public class CASGetResult<T> extends GetResult<CASValue<T>> {
CASGetResult를 사용하지 말고 GetResult에 적용되어야 할 변경 사항을 같이 적용해주세요.

2024-01-04 09:27 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +public class CASGetResult<T> extends GetResult<CASValue<T>> {
GetResult만 사용하면, Transcoder<T>가 아닌 Transcoder<CASValue<T>> 타입이 GetResult의 생성자에서 필요해집니다.

GetResult만 사용하기 위해 아래 두가지 방안이 있습니다.
1. CASValue 전용 Transcoder를 생성
2. GetResult<T, R> 처럼 제네릭을 추가

1번의 경우보다 현재 CASGetResult를 생성하는게 간결하다고 생각하고
2번은 현재 사용되는 asyncGet()에 영향을 주기에 CASGetResult을 사용하는게 좋다고 생각합니다.

2024-01-04 09:57 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +public class CASGetResult<T> extends GetResult<CASValue<T>> {
다른 방안도 있습니다.

- 함수형 프로그래밍을 활용하는 방법
  - 1번과 비슷하되, CachedData 객체를 인자로 받아 `CASValue<T>` 타입을 반환하는 메소드만 가진 콜백 객체를 만들어서 GetResult에 넘기는 방식입니다.
  - 이 콜백 안에서는 CachedData 객체를 T 타입으로 디코딩 가능한 tc 객체를 참조할 수 있으므로, `new CASValue(cas, tc.decode(...))`을 반환하면 가능합니다.
  - asyncGets에서는 위와 같이 하고, asycnGet에서는 CachedData 객체를 인자로 받아 T 타입을 반환하는 콜백 객체를 받도록 하면 됩니다.
  - CachedData 정보를 이미 갖고 있으므로 인자가 없는 형태의 메소드를 콜백 객체로 만들어도 됩니다.
- GetsFuture 클래스를 새로 만드는 방법
  - GetFuture 클래스는 T 타입의 객체를 반환하도록 되어 있기 때문에, `CASVAlue<T>`을 반환하기 위해서는 위의 세 가지 방법 중 하나를 반드시 사용해야 합니다. 위 세 가지 방법을 제외하면 이 방법을 사용해야 합니다.
  - GetsFuture 클래스를 새로 만들고, `GetResult<T>` 타입을 필드로 갖고 있으면서 Future.get()에서 `new CASValue(cas, result.getDecodedValue())`를 반환하면 됩니다.

@jhpark816 

4가지 방안 중 어떤 방안이 좋을까요?

1. CASValue 전용 Transcoder 사용
2. GetResult의 제네릭 타입을 2개로 늘려서 디코딩 결과 타입과 반환 타입을 따로 받을 수 있도록 변경
    - asyncGet()의 경우 `GetResult<T, T>` 타입 사용
    - asyncGets()의 경우 `GetResult<T, CASValue<T>>` 타입 사용
3. 함수형 프로그래밍으로 `R decode(CachedData cd)` 메소드를 갖는 콜백 객체를 GetResult가 갖도록 변경.
    - asyncGet()의 경우 R은 T와 동일
    - asyncGets()의 경우 R은 `CASValue<T>`
4. GetsFuture 클래스 추가

2024-01-04 10:36 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +public class CASGetResult<T> extends GetResult<CASValue<T>> {
@oliviarla 
위 코멘트의 방안들 중 좋은 방안을 생각해보고, 의견 주세요.

2024-01-04 11:11 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +public class CASGetResult<T> extends GetResult<CASValue<T>> {
@uhm0311 
`GetResult<T>` 클래스에 아래 메소드를 구분하여 제공한다면 GetFuture에서 구분하여 호출할 수 있나요?
- `T getDecodedValue()` 
- `CASValue<T> getDecodedCASValue()`

2024-01-04 11:18 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +public class CASGetResult<T> extends GetResult<CASValue<T>> {
새 API의 반환 타입이 `GetFuture<CASValue<T>>`이면 내부적으로 `GetResult<CASValue<T>>` 타입의 필드를 갖되, GetResult는 자신의 제네릭 타입이 CASValue인 것은 모릅니다.
그러면 GetResult는 내부적으로 `Transcoder<CASValue<T>>` 타입의 필드를 갖습니다. 마찬가지로 tc는 자신의 제네릭 타입이 CASValue인 것은 모릅니다.
이러한 tc 객체는 CachedData를 인자로 받아 CASValue 타입을 반환해야 합니다.
물론 그렇게 구현된 tc 객체는 현재 존재하지 않습니다.
GetFuture의 제네릭 타입으로 CASValue가 주어지는 한, 제안해주신 방안은 무의미합니다.

2024-01-05 07:02 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +public class CASGetResult<T> extends GetResult<CASValue<T>> {
@jhpark816 
@brido4125 님이 구현해두신 내용 토대로 상속 대신 인터페이스를 구현하도록 하면 아래와 같은 형태가 될 것 같습니다.
```java
public interface GetResultIF<T> {
  public void setCachedData(CachedData cachedData);
  public T getDecodedValue();
}
```

```java
public class CASGetResult<T> implements GetResultIF<CASValue<T>> {
  private final long cas;
  private final Transcoder<T> tc;
  private CachedData cachedData;

  public CASGetResult(long cas, Transcoder<T> tc) {
    this.cas = cas;
    this.tc = tc;
  }

  @Override
  public void setCachedData(CachedData cachedData) {
    this.cachedData = cachedData;
  }

  @Override
  public CASValue<T> getDecodedValue() {
    if (cachedData == null) {
      return null;
    }

    return new CASValue<T>(cas, tc.decode(cachedData));
  }
}
```

2024-01-05 10:23 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +public class CASGetResult<T> extends GetResult<CASValue<T>> {
@brido4125 @uhm0311 위의 인터페이스 사용 방식에 대해 의견 주세요.

2024-01-05 10:27 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +public class CASGetResult<T> extends GetResult<CASValue<T>> {
인터페이스 방안이 좋을 것 같습니다.

2024-01-05 10:32 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +public class CASGetResult<T> extends GetResult<CASValue<T>> {
나도 위의 인터페이스 방안이 좋은 것 같습니다.

2024-01-08 01:12 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/CASGetResult.java
> +public class CASGetResult<T> extends GetResult<CASValue<T>> {
asyncGet의 구현 변경을 별도의 PR로 먼저 처리하겠습니다.

2024-01-08 03:25 UTC, brido4125 commented
PR 본문의 `@Deprecated` 관련 의견이 필요합니다.

1. 기존 API에서 곧바로 변경(현재 구현)
2. `@Deprecated`붙이고 새로운 `asynGetsNew()`와 같은 API 추가

1번의 경우 버전 업그레이드 후 컴파일 시 컴파일 에러가 발생하고,
2번의 경우 추후 `@Deprecated`된 API가 삭제될 경우, 함수명 변경을 진행해줘야합니다.
다만, 2번의 경우도 Warning을 에러 처리한 WAS인 경우 컴파일 에러가 발생합니다.

추가적인 다른 의견도 주시면 감사하겠습니다.

2024-01-08 04:24 UTC, jhpark816 reviewed
리뷰 완료

2024-01-08 04:24 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/CASGetResultImpl.java
> +public class CASGetResultImpl<T> implements GetResult<CASValue<T>> {
용어 관점에서 `GetsResultImpl`가 어떤지 ?

2024-01-08 04:24 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/CASGetResultImpl.java
> +public class CASGetResultImpl<T> implements GetResult<CASValue<T>> {
commit 메세지에서 오타 수정 바랍니다.

2024-01-08 04:58 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/CASGetResultImpl.java
> +public class CASGetResultImpl<T> implements GetResult<CASValue<T>> {
반영하였습니다.

2024-01-08 07:44 UTC, oliviarla approved these changes

2024-01-08 07:46 UTC, uhm0311 commented
> PR 본문의 @Deprecated 관련 의견이 필요합니다.

저는 2번이 낫다고 봅니다.
그런데 의문이 하나 있습니다.
기존 API를 Deprecated 처리 한다고 해서 모든 응용이 기존 API를 사용하지 않는 것은 아닙니다.
그럼 기존 API는 여전히 IO Thread에 의해 디코딩 작업을 하도록 내버려 두나요?
아니면 기존 API도 응용의 Worker Thread가 디코딩 작업을 하도록 개선을 하긴 하나요?

2024-01-08 07:51 UTC, brido4125 commented
> 그럼 기존 API는 여전히 IO Thread에 의해 디코딩 작업을 하도록 내버려 두나요?
아니면 기존 API도 응용의 Worker Thread가 디코딩 작업을 하도록 개선을 하긴 하나요?

개선을 하려면 하위호환성에 영향을 미치지 않게 개선을해야하는데, 그럴 경우 CASValue를 활용한다거나 등의 새로운 변경이 발생합니다. 
그리고 해당 변경은 추후에 기존 API를 삭제할 경우 롤백시켜야합니다.

그렇기 때문에 Deprecated 처리될 API는 여전히 IO 쓰레드가 작업을 하도록 놔두는게 맞는것 같습니다.

2024-01-08 07:57 UTC, jhpark816 commented
GetFuture가 OperationFuture를 inherit 하면 backward compatibility는 만족이 되나요?

2024-01-08 07:58 UTC, uhm0311 commented
> GetFuture가 OperationFuture를 inherit 하면 backward compatibility는 만족이 되나요?

만족이 되기 때문에 새 API를 만들고 기존 API를 Deprecated 처리할 필요가 없어집니다.

2024-01-08 08:13 UTC, jhpark816 commented
그러면, 상속 관계를 이용하여 backward compatibility 이슈를 해결하는 것이 좋겠습니다.
CollectionGetFuture와 CollectionFuture도 상속 관계가 있는 것 같으니, 확인 바랍니다.

2024-01-09 02:56 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +  private final AtomicReference<GetResult<T>> result;
### `GetResult<T>`가 아닌 `AtomicReference<GetResult<T>>` 타입을 사용한 이유

`GetFuture`의 경우 기존의 하위 클래스로 `FrontCacheGetFuture`가 존재합니다.
`FrontCacheGetFuture`는 Front Cache-Miss가 발생할 경우
`GetFuture(GetFuture<T> parent)`를 호출하여 캐시 서버로부터 데이터를 가져오는 로직을 수행합니다.
기존 로직은 `GetFuture`의 rv 레퍼런스(OperationFuture 타입)를 
`FrontCacheGetFuture`가 그대로 가지면서 캐시 서버로부터의 데이터를 로컬 메모리에 저장합니다.

만약 rv 레퍼런스의 타입이 `AtomicReference<GetResult<T>>`인 경우 
`GetResult`의 레퍼런스가 receivedStatus()를 통해 `GetFuture`에 주입되기전에도
동일한 `AtomicReference`의 레퍼런스를 공유할 수 있습니다.

반대로 rv 레퍼런스의 타입이 GetResult<T>인 경우는
receivedStatus() 로직이 GetFuture에 GetReuslt의 레퍼런스를 주입하는 기존의 로직과 달라져야합니다.

결론적으로 기존 구현으로부터 변경지점의 최소화하기 위해
`AtomicReference<GetResult<T>>`를 필드값으로 사용하였습니다.

2024-01-09 03:12 UTC, uhm0311 requested changes

2024-01-09 03:12 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    return super.cancel(ign);
단순히 super 메소드를 호출하기만 하는 경우에는 override 할 필요가 없으니 메소드 자체를 제거하도록 합시다.

2024-01-09 08:24 UTC, uhm0311 approved these changes

2024-01-09 11:16 UTC, jhpark816 reviewed
리뷰 완료

2024-01-09 11:16 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    }
`super.get()` 호출하는 형식으로 구현할  방안이 있나요?

2024-01-09 11:28 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +  private final AtomicReference<GetResult<T>> result;
여기서 말씀하시는 rv라는게 GetFuture의 result 필드라고 이해하면 될까요?

> 반대로 rv 레퍼런스의 타입이 GetResult인 경우는
receivedStatus() 로직이 GetFuture에 GetReuslt의 레퍼런스를 주입하는 기존의 로직과 달라져야합니다.

구체적으로 어떤부분들이 달라지게 되는건가요?

2024-01-09 23:27 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    }
OperationFutre가 GetResult 타입을 필드로 가지고
해당 필드가 null인지 아닌지에 대해서 분기문을 거쳐 get()을 수행해야합니다.
왜냐하면 기존의 로직을 유지시켜야하기 때문입니다.

굳이 여러 책임을 OperaitonFuture에게 위임해야할 필요는 없다고 봅니다

2024-01-09 23:28 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +  private final AtomicReference<GetResult<T>> result;
설명이 길어질거 같아 오프라인으로 말씀드릴게요

2024-01-10 02:58 UTC, oliviarla approved these changes

2024-01-15 01:57 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    }
@uhm0311 위의 내용을 검토 바랍니다.

2024-01-15 02:07 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    }
`public class GetFuture<T> extends OperationFuture<T>`

super 클래스는 디코드 된 결과물을 가져야 합니다.
super.get()을 통해 디코드 된 결과물을 반환하기 위해서는 super.get() 호출 시점에 결과물을 디코딩 하거나, 그 이전에 디코딩이 되어 있어야 합니다.
super.get()을 override 하지 않고서는 super.get() 호출 시점에 결과물을 디코딩 할 수 없습니다.
super.get() 호출 이전에 결과물을 디코딩 하는 것은 IO Thread가 해야 하므로, PR의 본래 목적과 반대됩니다.
따라서 현재 구현이 맞다고 봅니다.

2024-01-15 03:12 UTC, jhpark816 reviewed
리뷰 완료

2024-01-15 03:12 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    this.result = parent.result;
GetFuture 객체를 새로 생성하는 방식이 맞는 지 확인 바랍니다.
front caching 기능이 정상 동작하는 지를 테스트해 보면 좋겠습니다.

2024-01-15 10:28 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    this.status = status;
> 아래 구현이 가능하다면, 이 구현이 좋겠습니다.

super.get()을 호출하면 순환호출이 발생합니다.
get(long, TimeUnit) 시그니처 메서드가 
get() 시그니처 메서드를 호출하면 내부에서
get(long, TimeUnit) 시그니처 메서드를 또 다시 호출하는 형태가 됩니다.

결국 함수 호출 스택 오버플로우가 발생하게 됩니다.

2024-01-15 10:34 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    this.status = status;
코멘트 위치가 잘못된 것 같습니다. 제 위치로 옮겨주시죠.

2024-01-15 23:33 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    }
> 아래 구현이 가능하다면, 이 구현이 좋겠습니다.

super.get()을 호출하면 순환호출이 발생합니다.
get(long, TimeUnit) 시그니처 메서드가 
get() 시그니처 메서드를 호출하면 내부에서
get(long, TimeUnit) 시그니처 메서드를 또 다시 호출하는 형태가 됩니다.

결국 함수 호출 스택 오버플로우가 발생하게 됩니다.

2024-01-16 00:09 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    this.result = parent.result;
참고로 OperationFuture의 objRef는 GetFuture에서 사용되지 않습니다.
이를 대신해 result 변수가 사용됩니다.
op와 status는 동일하게 설정되지 않았습니다.

그럼에도 불구하고 현재와 같은 방식으로 테스트 코드가 통과하는 이유는 아래와 같습니다.
FrontCacheGetFuture의 경우 front-cache가 hit or miss인 경우에 따라 서로 다른 구현체가 생깁니다.

1. hit인 경우 ->`new GetFuture(null, 0)`로 생성
2. miss인 경우 -> `new FrontCacheGetFuture<T>(localCacheManager, key, parent)`로 생성

현재 논의되는 코드는 2번에서 내부적으로 호출되는 생성자입니다.
기존에도 2번과 같이 cache-miss인 경우 해당 `FrontCacheGetFuture`의 
getStatus()를 호출하는 테스트 코드가 없었기에 테스트가 통과할 수 있었습니다.
즉, 프론트 캐시 기능 자체는 정상 동작합니다.

코멘트를 정리해보자면 프론트 캐시가 miss인 경우 
내부적으로 GetFuture를 통해 캐시 노드로부터 값을 들고와 프론트 캐시에 저장합니다. 
즉, 생성된 asyncGet 연산에 대한 op와 status를 
FrontCacheFuture에 동일하게 가지게하는것이 자연스러운것 같습니다.

2024-01-16 00:37 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    this.result = parent.result;
추가적으로 status의 경우 parent GetFuture의 연산이 완료된 뒤에 설정됩니다.
즉, 현재 생성자 내부가 수행되는 시점에는 asyncGet 연산이 완료되지 않았기에 status 값을 설정할 수 없습니다.

status를 설정해야한다는 의사 결정이 될 경우 별도 PR로 처리해야할 것 같습니다.

2024-01-16 00:49 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    }
`super.get(long, TimeUnit)` 호출하는 것을 말하는 것입니다.

2024-01-16 00:51 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    this.result = parent.result;
@uhm0311 위의 내용 검토하고 의견주세요.

2024-01-16 01:21 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    }
반영했습니다.
super.set()을 통해 rv 값을 OperationFuture의 objRef에 대입시키지 않아도 되는 이유는
응용의 OperationFuture 타입을 사용한다하더라도
실제 리턴되는 인스턴스의 타입이 GetFuture이라서 
오버라이딩된 GetFuture의 get() 함수가 호출되기 때문입니다.

2024-01-16 02:16 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    this.result = parent.result;
@brido4125 @uhm0311 
`FrontCacheGetFuture`가 `GetFuture` 자체를 가지고 있어야 하지 않는 지 ?
즉, embed하고 있어야 하지 않는지 ?

2024-01-16 02:28 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    this.result = parent.result;
저도 그렇게 생각하는데, 해당 PR에 반영할까요?

2024-01-16 03:09 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    this.result = parent.result;
@brido4125 
이번 PR에 같이 반영되어야 할 것 같습니다.

2024-01-16 04:43 UTC, jhpark816 commented
@brido4125 
수정 완료된 상태이면, noti 주세요.

2024-01-16 04:48 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    this.result = parent.result;
반영하였습니다.

2024-01-17 05:22 UTC, uhm0311 requested changes

2024-01-17 05:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
>      T t = super.get(timeout, unit);
parent.get(...)으로 바뀌어야 하진 않는지 검토해주세요.

2024-01-17 05:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
> +    this.status = parent.getStatus();
기존 GetFuture의 경우 GetFuture.set(...)이 호출된 뒤라면 Future.get()을 호출하지 않아도 GetFuture.getStatus() 호출 시 올바른 값을 반환하게 되어 있습니다.
반면 이러한 구현은 반드시 Future.get()을 호출해야만 FrontCacheGetFuture.getStatus() 호출 시 올바른 값을 반환합니다.
차라리 getStatus() 메소드를 override 하여 return parent.getStatus()를 하도록 합시다.

2024-01-17 05:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    T rv = super.get(duration, units);
GetFuture.set(...) 메소드는 현재 public 메소드로, 사용자가 호출할 수도 있습니다.
GetFuture.set(...) 메소드를 사용자가 호출할 경우, rv 값에는 우리가 의도하지 않은 값이 담기게 될 것입니다.
그런데 아래 if 문에서 `result.get() == null`인 상황(`GetFuture.set(null, ...)`을 호출한 상황)이라면 rv 값이 바뀌지 않을 것이므로, rv 값에 의도하지 않은 값이 담긴채로 그대로 반환될 것입니다.
물론 이러한 방식의 GetFuture 객체 사용은 상정하지 않은 부분이지만, 조금 더 확실하게 하려면 아래와 같이 하는 것이 좋습니다.

```java
super.get(duration, units);
return result.get().getDecodedValue();
```

2024-01-17 05:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    this.result = parent.result;
FrontCacheGetFuture.get(...)의 구현에서 super.get(...)이 아닌 parent.get(...)을 호출한다면 result 필드를 AtomicReference로 표현하지 않아도 될 것 같은데, 검토해주세요.

2024-01-17 07:47 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +    T rv = super.get(duration, units);
`AtomicRefernce -> GetReuslt`로 변경할 경우

현재 구현으로는 연산의 key가 not found라서 연산의 GetResult가 null인 경우와
말씀하신대로 사용자가 set()을 호출해서 null인 경우를 구분할 수 없습니다.
(OperationStatus가 isSuccess:true에 OK로 반환됨)
not found인 경우 gotData 콜백 함수를 호출하지 않아 자동으로 GetResult가 null 값이 설정되기 때문입니다.

그래서 사용자가 설정한 null이든 연산의 결과에 의한 null이든 그대로 null을 반환하는 로직을 사용해야할 것 같습니다.

2024-01-17 08:25 UTC, uhm0311 requested changes

2024-01-17 08:25 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +      return rv;
사용자에 의해 null이 되었는지 아닌지 구분해야 할 필요성이 있는지는 잘 모르겠습니다.
그리고 이렇게 하면 이전 문제점이 그대로 있습니다.

2024-01-18 01:31 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
> +      return rv;
코드를 그대로 쓰라는 뜻은 아니고요.
OperationFuture.set(??, ...)을 호출한 경우에 rv 값에는 ?? 값이 들어가서 잘못 동작하게 되니, super.get()의 결과를 저장하고 반환하지 말자는 의미입니다.

@jhpark816 

사용자가 GetFuture 객체를 통해 OperationFuture.set(...)을 호출하면, 현재 PR 구현으로는 사용자가 설정한 값이 반환될 수 있습니다.
이는 의도하지 않은 동작이라서 OperationFuture.set(...)의 결과를 버려야 한다고 생각하는데요.
어떻게 하는 것이 좋을까요?

2024-01-18 03:38 UTC, uhm0311 requested changes

2024-01-18 03:38 UTC, uhm0311 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
>      super(parent);
FrontCacheGetFuture 클래스에서 super.get()이 아닌 parent.get()을 호출하게 되었으니, 더 이상 super(parent)를 호출할 필요가 없습니다.
GetFuture 생성자에 GetFuture를 인자로 받는 오버로딩을 제거하고 여기에서도 다른 super 생성자를 호출하도록 합시다.

2024-01-18 04:09 UTC, brido4125 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
>      super(parent);
FrontCacheGetFuture의 생성자에서
`super(CountDownLatch, long)`을 호출하려면은
parent의 latch와 opTimeout 값이 필요하여
getter를 OperationFuture 또는 GetFuture에 추가해야합니다.
`super(parent.latch, parent.opTimeout)`과 같은 프로퍼티 접근 법이 허용되지 않습니다.

사용자에게 필요하지 않은 메서드를 접근허용하는것은 줄이는게 좋다고 생각하기 때문에
getter는 제공하지 않아야 한다고 생각합니다.

2024-01-18 04:18 UTC, uhm0311 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
>      super(parent);
두 필드는 protected 아닌가요?

2024-01-18 04:45 UTC, brido4125 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
>      super(parent);
protected이므로 super.latch와 같은 접근은 가능하고,
인자로 들어온 parent 변수에 parent.latch 접근은 안되는것 같습니다.
제 생각에는 생성될 FrontCacheGetFuture 인스턴스와 인자로 들어온 parent 인스턴스간에는 
상속 관계가 성립 되지 않아서 그런것 같습니다.

![image](https://github.com/naver/arcus-java-client/assets/64846408/5d37cf91-6246-4b4f-a890-e0feb10efc81)

2024-01-18 04:51 UTC, uhm0311 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
>      super(parent);
두 클래스가 패키지가 같으면 접근이 될텐데, 다르군요.
그럼 GetFuture 생성자에 GetFuture를 인자로 받는 오버로딩에서 super(latch, timeout)만 호출하도록 합시다.

2024-01-18 05:19 UTC, brido4125 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
>      super(parent);
@uhm0311 
FrontCacheGetFuture는 외부에 노출되는 타입이 아니라서
패키지 변경해도 하위호환성에 문제가 없을것 같습니다.
변경해서 PR 반영할까요?

이 뿐만 아니라 Future 구현체라서 internal 패키지 내에 있는게 맞다고 생각됩니다.

2024-01-18 05:25 UTC, uhm0311 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
>      super(parent);
로컬 캐시 관련 클래스가 한 패키지에 모여 있기 때문에 변경하지 않는 게 더 나을 것 같습니다.

2024-01-18 05:45 UTC, brido4125 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
>      super(parent);
GetFuture 생성자 내에서 op 인스턴스의 레퍼런스를 전달해주는 코드를 제외했기에
FrontCacheGetFuture 단에서 오버라이드를 통해
parent의 op를 사용하도록 변경하였습니다.

2024-01-18 08:36 UTC, uhm0311 approved these changes

2024-01-22 03:37 UTC, oliviarla commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
> +  private final GetFuture<T> parent;
아직 익숙하지 않아서 그런데, GetFuture를 상속받으면서 동시에 GetFuture 필드(parent)를 두는 이유를 간단히 설명해주실 수 있나요?

2024-01-22 04:46 UTC, brido4125 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
> +  private final GetFuture<T> parent;
상속받는 이유는 Front 캐시를 사용해도
asyncGet 결과의 Future 타입이 GetFuture이기 때문입니다.

필드로 가지는 이유는 front cache-miss인 경우
캐시 서버로부터 가져온 값을 사용하기 위해서입니다.

2024-01-22 06:00 UTC, oliviarla commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
> +  private final GetFuture<T> parent;
GetFuture 클래스의 생성자는 아래와 같이 두고, FrontCacheGetFuture에서 parent 필드를 두지 않고 super.get()만 호출하면 제대로 된 값이 나오지 않게 되는걸까요?
```java
public GetFuture(GetFuture<T> parent) {
  super(parent.latch, parent.objRef, parent.timeout);
}
```

2024-01-22 06:03 UTC, oliviarla reviewed
리뷰 완료입니다.

2024-01-22 06:03 UTC, oliviarla commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
> -  public T get() throws InterruptedException, ExecutionException {
GetFuture와 FrontCacheGetFuture에서 get() 메서드를 오버라이딩 해야하지 않나요??

2024-01-22 06:06 UTC, brido4125 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
> -  public T get() throws InterruptedException, ExecutionException {
`get()` 메서드가 오버라이드 되지 않아도
`get()` 내부에서 호출되는 `get(long, Timeunit)` 메서드는
하위 클래스의 오버라이딩된 메서드가 호출됩니다.

2024-01-22 06:12 UTC, brido4125 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
> +  private final GetFuture<T> parent;
넵 그렇습니다.

생성될 `FrontCacheGetFuture`의 `super.get(long, Timeunit)`을 호출해도
parent 변수인 GetFuture의 result 값이 전달되지 않아서 
정확한 값이 나오지 않습니다.

2024-01-22 06:23 UTC, oliviarla commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
> +  private final GetFuture<T> parent;
아 이해했습니다. 감사합니다!

2024-01-22 06:45 UTC, oliviarla approved these changes
@jhpark816 @uhm0311 @brido4125 
FrontCacheGetFuture가 GetFuture를 상속받으면서 동시에 GetFuture 필드를 갖고 있는 것이 좋은 형태는 아닌 것 같습니다. 일단은 지금 형태로 머지하되, 나중에는 FrontCacheGetFuture가 GetFuture를 상속하지 않도록 전체적인 구조를 변경하거나 GetFuture필드를 제거할 방안을 고민해보는 게 어떨까 싶습니다.

2024-01-22 09:58 UTC, jhpark816 reviewed
리뷰 완료

2024-01-22 09:58 UTC, jhpark816 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
>      super(parent);
`super(parent)` 대신에 `super(new CountDownLatch(0), 1)` 호출하면 될 것 같습니다.
그리고, `GetFuture(GetFuture<T> parent)` 생성자는 제거하고요.

2024-01-22 09:58 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
>    public void set(GetResult<T> result, OperationStatus status) {
여기에도 `@Override` 추가합시다.

2024-01-22 10:17 UTC, uhm0311 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
> -  public T get() throws InterruptedException, ExecutionException {
Java를 비롯한 객체지향언어에서 메소드는 현재 객체 기준으로 가장 구체적인 클래스의 메소드가 호출됩니다.
구체적인 클래스에서 별도의 Override를 하지 않은 경우에만 부모 클래스의 메소드가 호출됩니다.

2024-01-22 23:38 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/GetFuture.java
>    public void set(GetResult<T> result, OperationStatus status) {
오버라이딩이 아니라 오버로딩 대상입니다.

2024-01-22 23:41 UTC, brido4125 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
> +    return parent.isCancelled();
parent에 설정된 operation과 operationStatus를 
사용하도록 메서드를 오버라이딩해서입니다.

2024-01-23 01:34 UTC, jhpark816 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
>      super(parent);
@brido4125 
바로 위의 코멘트 확인 바랍니다.

2024-01-23 01:51 UTC, brido4125 commented on src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
>      super(parent);
resolve된 코멘트 달아 주실 때,
멘션해주시면 감사하겠습니다. 반영했습니다

2024-01-23 01:58 UTC, merged