INTERNAL: Change docode logic in aysncLopGet.
naver/arcus-java-client pull request #719
Opened 2024-01-25 01:02 UTC by brido4125

## 이슈
https://github.com/jam2in/arcus-works/issues/486

## 변경 지점
1. `decode()` 로직 수행을 콜백 메서드가 아닌 XXXResult 객체를 통해 수행하도록 변경하였습니다.
2. 현재 `CollectionGetFuture`를 사용하는 api들과의 변경 전파를 방지하기 위해 `CollectionGetResultFuture`를 새롭게 생성하였습니다. 추후에 모든 api들이 변경되면 하나로 통합할 예정입니다. 변경이 필요한 api 목록들은 이슈에 남겨두겠습니다. 한번에 변경할 경우 리뷰하는게 힘들것 같아 하나씩 리뷰 받기 위함입니다.
3. `addResult()` 콜백 메서드의 경우도 최종적으로 변경 될때 완전히 삭제할 예정입니다.

2024-01-25 02:30 UTC, oliviarla commented
@brido4125 
커밋 메시지에 오타가 있습니다. docode -> decode

2024-01-25 02:40 UTC, uhm0311 requested changes

2024-01-25 02:40 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/LopGetResultImpl.java
> +  private volatile List<T> result = new ArrayList<T>();
final로 선언해도 됩니다.

2024-01-25 02:40 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/LopGetResultImpl.java
> +
Empty Line 제거

2024-01-25 02:40 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CollectionGetResultFuture.java
> +    super.get(duration, units);
GetFuture에 있는 `// for waiting latch.` 주석을 추가합시다.

2024-01-25 02:40 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CollectionGetResultFuture.java
> +    if (result == null) {
GetFuture와 같이 삼항 연산자로 표현 가능할 것 같습니다.

2024-01-25 02:40 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CollectionGetResultFuture.java
> +  public void setResult(GetResult<T> result, CollectionOperationStatus status) {
GetFutue에서 같은 역할을 하는 메소드 이름도 OperationFuture.set() 메소드와 헷갈리지 않도록 setResult로 변경하는 것이 좋을 것 같네요.
이건 다른 PR로 반영하도록 합시다.

2024-01-25 02:40 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CollectionGetResultFuture.java
> +    this.collectionOpStatus = status;
GetFuture.set(result, status)에서와 같이 `super.set(null, status)`를 호출하고 `this.result = result`만 남기도록 하죠.

2024-01-25 02:40 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +            //not impl until complete.
`// Not need to do anything here when using GetResult object.`로 하도록 합시다.

2024-01-25 03:02 UTC, uhm0311 commented
PR 제목의 오타도 고쳐주세요.

2024-01-25 03:03 UTC, uhm0311 approved these changes

2024-01-25 03:54 UTC, oliviarla approved these changes

2024-01-25 04:39 UTC, jhpark816 reviewed
리뷰 완료

2024-01-25 04:39 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    final CollectionGetResultFuture<List<T>> rv
`CollectionGetResultFuture` 별도로 두는 것이 아니라
`CollectionGetFuture`를 수정해야 하지 않는 지 ?

이를 위해, collection get 연산이 일괄 수정되어야 할 것 같습니다.

2024-01-25 04:39 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/LopGetResultImpl.java
> +public class LopGetResultImpl<T> implements GetResult<List<T>> {
여기도 개별 collection에 대한 implementation 보다
CollectionGetResultImpl이면 되지 않는지 확인 바랍니다.

2024-01-25 04:48 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    final CollectionGetResultFuture<List<T>> rv
https://github.com/naver/arcus-java-client/pull/719#issue-2099378181

위 코멘트에 남겨놓았듯이 한번에 많은 변경이 일어나면 리뷰하기 힘듭니다.
변경 api 리스트 확인하시죠

2024-01-25 04:49 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/LopGetResultImpl.java
> +public class LopGetResultImpl<T> implements GetResult<List<T>> {
lop,sop,mop,bop마다
리턴 타입이 다르기 때문에 cachedData를 담는 자료구조 타입이 다릅니다.

2024-01-25 05:59 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/LopGetResultImpl.java
> +public class LopGetResultImpl<T> implements GetResult<List<T>> {
@brido4125 
질문입니다.
- cachedData 담는 자료구조가 여러 개가 존재할 것 같습니다.
   - 이에 관련하여 어떤 연산에서 어떤 Result 클래스가 필요한 지 미리 정리해 둔 것이 있나요 ? 있을 경우만 보여주면 됩니다.
   - 연산 타입 보다는 결과 타입에 따라 각각 Result 클래스를 따로 두어야 해서 이러한 Result 클래스가 많아지는 이슈가 있습니다.
- 하나의 Result 클래스로 여러 자료 구조를 표현할 수 있는 다른 방안은 있을까요?

2024-02-03 03:39 UTC, jhpark816 commented
@brido4125 
commit message 오타 : aysncLopGet => asyncLopGet

2024-03-07 04:41 UTC, uhm0311 commented
변경이 모두 완료되면 노티 주세요.

2024-03-08 00:26 UTC, uhm0311 requested changes

2024-03-08 00:26 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          result.gotKey(key, elementCount, reverse, status);
reverse 여부는 API의 매개변수로 들어온 뒤로 바뀌지 않으니 생성자에서 주입해줘도 됩니다.

2024-03-11 02:29 UTC, uhm0311 requested changes

2024-03-11 02:29 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      private final GetResult<Map<Integer, Element<T>>> result
위에 Empty Line 제거

2024-03-11 02:29 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          private final GetResult<Map<Integer, Element<T>>> result
위에 Empty Line 제거

2024-03-11 02:29 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +
Empty Line 2개에서 1개로 줄여주세요.

2024-03-11 02:29 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetByPositoinResultImpl.java
> +
Empty Line 2개에서 1개로 줄여주세요.

2024-03-11 02:29 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopStoreAndGetResultImpl.java
> +
Empty Line 2개에서 1개로 줄여주세요.

2024-03-11 02:29 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/MopGetResultImpl.java
> +
Empty Line 2개에서 1개로 줄여주세요.

2024-03-12 02:46 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/MopGetResultImpl.java
> +
변경하였습니다.

2024-03-12 05:41 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +  private final Boolean reverse;
primitive 타입으로 변경하였습니다.

2024-03-12 09:01 UTC, uhm0311 approved these changes

2024-03-12 11:52 UTC, oliviarla reviewed
리뷰 완료입니다.

2024-03-12 11:52 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/result/SopGetResultImpl.java
> +  public SopGetResultImpl(Set<CachedData> cachedDataList, Transcoder<T> transcoder) {
cachedDataList -> cachedDataSet이 되어야 합니다.

2024-03-12 11:52 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          private final GetResult<List<T>> result = new LopGetResultImpl<T>(cachedDataList, tc);
cachedDataList를 GetResult 내부에서만 생성하고 사용하는 방식으로는 구현이 불가능할까요?

2024-03-12 11:52 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/result/BopGetByPositoinResultImpl.java
> +public class BopGetByPositoinResultImpl<T> implements GetResult<Map<Integer, Element<T>>> {
클래스명에 오타 있습니다.

2024-03-12 23:59 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          private final GetResult<List<T>> result = new LopGetResultImpl<T>(cachedDataList, tc);
외부 콜백 로직에서 cachedData를 추가해주는 로직이 있기 때문에 주입시키는 게 좋을 것 같습니다.

2024-03-13 02:17 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          private final GetResult<List<T>> result = new LopGetResultImpl<T>(cachedDataList, tc);
`BopGetBulkResultImpl` 클래스에 gotKey() 메서드가 있고 이를 콜백에서 사용하는 것처럼, gotElement() 역시 `BopGetBulkResultImpl` 클래스에 메서드를 추가해 호출하면 cachedData 자료구조를 외부에서 주입할 필요가 없을 것 같은데 가능한지와 가독성이 좋을지 검토 부탁드려요.

2024-03-13 02:56 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          private final GetResult<List<T>> result = new LopGetResultImpl<T>(cachedDataList, tc);
`ResultXXX` 클래스마다 모든 CachedData 자료구조 타입에 따라 데이터를 추가해주는 메서드를 추가해줘야하는데, 하나의 자료구조로 통일된다면 말씀해주신 메서드를 abstract class로 공통화하여 가독성을 좋게 만들 수 있을것 같습니다.
하지만 CachedData를 담는 자료구조가 `ResultXXX`마다 다르기 때문에 외부에서 사용하고 주입시켜주는게 가독성이 더 좋을 것 같네요

2024-03-13 03:37 UTC, oliviarla approved these changes

2024-03-15 04:58 UTC, jhpark816 reviewed
일부 리뷰

2024-03-15 04:58 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    final BopGetBulkResultImpl<Long, T> result
아래 형태로 표현하시죠.
```java
final GetResult<Map<String, BTreeGetResult<K, V>>> result
```

2024-03-15 04:58 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          result.gotKey(key, elementCount, status);
TreeMap의 key 타입이 Long 타입 또는 ByteArray 타입으로 달라지는 데,
`result.gotKey()` 동일하게 수행해도 되나요?

2024-03-15 04:58 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          result.gotKey(key, elementCount, status);
gotKey()에서 cachedDataMap에 empty ArrayList를 가지는 entry 추가하고
gotElement()에서 해당 arrayList에 element 추가하면 될 것 같습니다.

BopGetBulkResultImpl의 getDecodedValue()에서는 cacheDataMap으로 부터 
result map을 생성하는 형태가 일관적으로 보입니다.

2024-03-15 04:58 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          result.gotKey(key, elementCount, status);
추가 사항으로,
BTreeGetResult 클래스의 addElements() 메소드는 제거하고,
직접 treeMap 직접 생성하여 BTreeGetResult 객체를 생성하는 로직이
getDecodedValue()에 있으면 좋겠습니다.

2024-03-15 07:17 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/LopGetResultImpl.java
> +    this.transcoder = transcoder;
- cachedDataList : 생성자 위에서 바로 생성해서 Null 일 수 없음
- transcoder : 사용자가 주입하는 경우 Not null 보장 X

방법은 `tc`를 받는 메서드에서 직접 확인하는 방법밖에 없을 것 같습니다.

2024-03-15 07:32 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/BTreeStoreAndGetFuture.java
> +    this.result = result;
Boolean 타입의 데이터를 넣어줘야해서 현재 메서드가 간결할 것 같습니다.
말씀하신대로 반영하면 아래로직에서 별도의 메서드 호출이 필요합니다.
```java
if (cstatus.isSuccess()) {
              rv.setResult(true, result, cstatus);
              return;
            }
```

2024-03-15 08:06 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          result.gotKey(key, elementCount, status);
> TreeMap의 key 타입이 Long 타입 또는 ByteArray 타입으로 달라지는 데,
result.gotKey() 동일하게 수행해도 되나요?


`ByteArrayTreeMap`이 TreeMap을 상속 받고 있어서 해당 타입으로
생성할 경우 Long / ByteArray 타입의 키 모두 sortIng 됩니다.

2024-03-15 08:25 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    final BopGetBulkResultImpl<Long, T> result
gotKey 메서드를 호출해야 하기 때문에 인터페이스가 아닌 구체 클래스 타입으로 설정했습니다.

2024-03-15 09:04 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          result.gotKey(key, elementCount, status);
위의 다른 코멘트에 대해서도 의견 주세요.

2024-03-15 12:29 UTC, jhpark816 reviewed
추가 리뷰

2024-03-15 12:29 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          result.gotKey(key, elementCount, status);
GetResult 사용 로직의 통일화를 위해 아래 처리를 검토 바랍니다.
- cachedDataMap 외에 opStatusMap 사용
- gotKey() 로직은
   - opStatusMap에 항목 추가
   - cachedDataMap에 항목 추가도 검토. (empty ArrayList)
- gotElement() 로직은
   - 해당 ArrayList에 element 추가

이를 통해, BopGetBulkResultImpl 클래스는
- gotKey() 메소드가 없어도 됨.
- getDecodedValue()에서는 cachedDataMap과 opStatusMap을 참고하여 최종 result 생성

2024-03-18 00:09 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          result.gotKey(key, elementCount, status);
> GetResult 사용 로직의 통일화를 위해 아래 처리를 검토 바랍니다.

말씀하신대로 gotKey에서 Status와 cachedDataMap에 필요한 리스트 인스턴스를 생성해주고,
gotElement에서는 해당 key에 해당하는 elem들만 받아 추가해주는 로직만 수행해주는게 좋을 것 같습니다.

2024-03-18 00:53 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          result.gotKey(key, elementCount, status);
> 추가 사항으로,
BTreeGetResult 클래스의 addElements() 메소드는 제거하고,
직접 treeMap 직접 생성하여 BTreeGetResult 객체를 생성하는 로직이
getDecodedValue()에 있으면 좋겠습니다.


addElements 메서드는 제거할 경우, 해당 로직이 getDecodedValue에서 수행되는데
구현해보니 if -for -if - for 구문이 반복되어 코드 가독성이 많이 떨어집니다.
기존대로 분리시키는게 좋을 것 같습니다.

2024-03-18 02:38 UTC, jhpark816 reviewed
일부 리뷰

2024-03-18 02:38 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                  new CollectionOperationStatus(status)));
처음에는 아래와 같이 수행하는 것을 제안했던 것입니다.
그리고, BTreeGetResult 객체를 생성하여 result map을 만드는 것은 getDecodedValue() 안에서 수행하면 되고요.
```java
cachedDataMap.put(key, new ArrayList<BTreeElement<Long, CachedData>>());
opStatusMap.put(key, new CollectionOperationStatus(status));
```

PR 코드를 보니, 현재 PR도 괜찮다고 보입니다.
대신 이 경우는 opStatusMap이라기 보다는 resultMap이라고 하는 것이 나을 것 같습니다.


2 가지 구현 방안 중 어떤 것이 나은가요?

2024-03-18 02:38 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +    this.result = new ByteArrayTreeMap<K, Element<V>>(
`TreeMap<K, Element<V>>` 타입을 사용하면 문제가 있나요?

Long 타입의 BKey에 대해 `ByteArrayTreeMap` 생성한다는 것이 어색하게 느껴집니다.

2024-03-18 02:51 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                  new CollectionOperationStatus(status)));
`opStatusMap` 이라는 자료구조가 다른 api에서는 사용되지 않기에
`resultMap` 이라 표현하고 현재 PR 방식을 사용하는게 좋을 것 같습니다.

2024-03-18 02:59 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +    this.result = new ByteArrayTreeMap<K, Element<V>>(
현재 로직은 `BopGetResultImpl`에서 제네릭 K의 타입에 상관없이 Tree 객체를 생성합니다.
만약 말씀하신대로 변경한다면 내부적으로 K 타입을 알게 되는 시점에
Tree 객체를 생성해야되어, 구현이 지금 로직에 비해 복잡해 질 것입니다.

`ByteArrayTreeMap`이 상속을 통해 Long 타입의 키도 지원할 수 있다는
사실을 알고 있다면, 그렇게 어색한 구현은 아니라고 생각됩니다.

2024-03-18 04:50 UTC, jhpark816 reviewed
리뷰 완료

2024-03-18 04:50 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +    this.result = new ByteArrayTreeMap<K, Element<V>>(
이 부분은 다시 검토 바랍니다.
BKey 타입이 Long 타입이거나 ByteArrayBKey 타입에 대해 TreeMap 만들어 사용해도 될 것 같습니다.

아래 ByteArrayTreeMap 구현체를 보면, `byte[]` 타입의 값으로 조회 가능하게 하는 용도로 보이는 데,
이러한 기능은 어디에서 사용되나요?
```java
public final class ByteArrayTreeMap<K, V> extends TreeMap<K, V> {

  private static final long serialVersionUID = -304580135331634224L;

  public ByteArrayTreeMap(Comparator<? super K> comparator) {
    super(comparator);
  }

  @Override
  public V get(Object key) {
    if (key instanceof byte[]) {
      return super.get(new ByteArrayBKey((byte[]) key));
    } else {
      return super.get(key);
    }
  }
}
```

Interface에 ByteArrayBKey 타입의 Map으로 리턴하므로,
응용에서는 ByteArrayBKey 만들어서 조회해야 하지 않나요?
이 경우에 `byte[]` 타입으로 조회할 수 있게 하는 용도인가요?

```java
CollectionFuture<Map<ByteArrayBKey, Element<Object>>> asyncBopGet(....)
```

2024-03-18 04:50 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +            result = new BopStoreAndGetResultImpl<E>(
변수 선언과 함께 사용하면 될 것 같습니다.
해당 값은 trimmed element 정보이므로, result 보다는 element 용어를 사용하는 것이 나은 것 같습니다.
```java
GetResult<Element<E>> element =  ...;
rv.setElement(element);
```

2024-03-18 05:39 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +    this.result = new ByteArrayTreeMap<K, Element<V>>(
> BKey 타입이 Long 타입이거나 ByteArrayBKey 타입에 대해 TreeMap 만들어 사용해도 될 것 같습니다.

변경시, 리턴되는 구현체의 get() 구현이 달라져서 하위호환성이 깨지게 됩니다.

> 이러한 기능은 어디에서 사용되나요?

`byte[]`의 bkey를 통해 elem을 얻어올 때 사용됩니다.

> Interface에 ByteArrayBKey 타입의 Map으로 리턴하므로,
응용에서는 ByteArrayBKey 만들어서 조회해야 하지 않나요?

`ByteArrayBKey`타입의 Map의 구현체가 `ByteArrayTreeMap`입니다.
`ByteArrayTreeMap`은 get 메서드를 오버로딩해서
byte[] 타입으로 value를 가져올 수 있도록 구현되어있습니다.

2024-03-18 05:48 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopStoreAndGetResultImpl.java
> +                                  Transcoder<T> transcoder) {
@brido4125 
minor 사항이긴 하지만, 
인자 순서에서 bKeyObject가 가장 앞에 오는 것이 좋겠습니다.

2024-03-18 05:50 UTC, jhpark816 commented
@uhm0311 @oliviarla 
수정 사항이 있어, 다시 리뷰 바랍니다.

2024-03-18 08:01 UTC, uhm0311 requested changes

2024-03-18 09:05 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    return result;
@uhm0311 
위의 코멘트는 BopGetBulkResultImpl의 getDecodedValue()에 대한 것인가요?
아니면 모든 ResultImple 객체의 getDecodedValue()에 대한 것인가요?

2024-03-18 09:10 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    return result;
@jhpark816 

> getDecodedValue() 메소드가 응용의 Worker Thread에 의해 호출되는 특성상, Map이나 Collection을 반환하는 GetResult 객체의 경우 동기화 문제도 해결해야 할 것 같습니다.

`Map이나 Collection을 반환하는 GetResult 객체의 경우`로, BopGetBulkResultImpl 클래스에만 국한되는 문제는 아니지만 그렇다고 모든 GetResultImpl 클래스에 해당하는 것은 아닙니다.
단일 값을 반환하는 GetResultImpl 클래스도 존재하기 때문입니다.

2024-03-18 09:21 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    return result;
@uhm0311 
`getDecodedValue()` 메소드가 호출되는 것은 CountDownLatch의 count가 0인 경우에 호출되기 때문에
더 이상 변경이 없는 상태에서 응용의 worker thread에 의해서만 수행됩니다.
따라서, 동기화 문제가 없다고 생각합니다. 어떤가요?

2024-03-18 09:28 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    return result;
result 객체와 cachedDataMap 객체 간에 동기화 문제가 있다는 것이 아닙니다.
getDecodedValue() 메소드가 여러 Thread에 의해 호출될 때, result가 잘못 만들어질 수 있기 때문에 동기화 문제가 있다고 하는 것입니다.

현재 구현 기준의 BopGetBulkResultImpl.getDecodedValue()를 기준으로 2개의 Thread가 호출한다고 가정합시다.
다음의 두 라인이 동시에 호출되면 어떤 결과가 나올까요?
- `result.get(entry.getKey()).addElements(entry.getValue(), transcoder);`
- `cachedDataMap.clear();`

혹은 다음의 한 라인이 두 Thread에 의해 동시에 호출되는 경우는 어떨까요?
- `result.get(entry.getKey()).addElements(entry.getValue(), transcoder);`

여러 Thread에 의해 getDecodedValue() 메소드가 호출될 때 result 객체가 잘못 만들어질 가능성이 없나요?

2024-03-18 09:47 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    return result;
@uhm0311 
해당 연산을 요청하는 worker thread는 1개이기 때문에
getDecodedValue() 메소드는 1개 worker thread에 의해 요청된다고 가정한 것입니다.

의도적으로 future를 다른 thread에게 전달하여
2개 thread가 동시에 호출할 수는 있지만 거의 일어날 수 없는 일인 것 같습니다.

하지만, 외부에 공개되는 메소드이고 외부에서 어떻게 사용할 지를 모르기 때문에
Collection 교체 방식으로 처리하는 것이 안전한 것 같습니다.

@brido4125 
Collection 교체 방식으로 처리하도록 하시죠.

2024-03-19 00:10 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    return result;
문제가 되는 부분이 result 변수에 write하거나,
`cachedDataMap`의 clear를 호출하는 부분인거 같습니다.

@uhm0311 
자바에서 제공하는 동시성 제어 자료구조를 사용해도 되지 않나요?

`BopGetBulkResultImpl`에 한해서는 아래와 같이 처리가능합니다.

ConcurrentHashMap의 경우 한 스레드가 clear를 호출해도,
동시에 다른 스레드가 read할 경우 clear한 데이터가 반영되지 않고 
read를 시작한 시점의 데이터가 반영된다고 합니다. (트랜잭션처럼 동작)

addElements로부터 발생하는 문제는
`Collections.synchronizedMap(new TreeMap<Integer, Integer>());`를 
주입해줘 처리할 할 수 있을 것 같습니다.

2024-03-19 00:30 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    return result;
temp를 사용해서 교체하는 방법은 
getDecodedValue가 여러번 호출될 경우 성능이 조금이라도 더 좋을 것 같네요.
해당 방식으로 변경하겠습니다.

2024-03-19 02:20 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    return result;
`Collections.synchronizedMap(new TreeMap<Integer, Integer>())`를 사용할 경우
응용이 리턴받는 Map의 타입이 TreeMap으로 다시 캐스팅 되지 않아서,
위 방식을 Bop 연산에 적용 시키지 못합니다.

그래서 일괄적으로 temp를 사용하는 로직으로 변경했습니다.

2024-03-19 08:40 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +  }
이런 방안은 어떤가요?
- `private Map<String, BTreeGetResult<K, V>> buildResult()` 메소드를 추가하고 이 메소드는 34 ~ 37 라인을 수행한 다음 temp를 반환합니다.
- `private final AtomicBoolean isDecoded = new AtomicBoolean(false)` 필드를 추가합니다.
- `if (isDecoded.comapreAndSet(false, true))`를 수행합니다.
- if문이 true이면 result = buildResult()를 수행하고 result를 반환합니다.
- if문이 false이면 return buildResult()를 수행합니다.

2024-03-19 09:09 UTC, oliviarla reviewed
리뷰 완료입니다.

2024-03-19 09:09 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +
line 제거

2024-03-19 23:40 UTC, brido4125 commented on src/main/java/net/spy/memcached/util/BTreeUtil.java
> +  public static <T> Element<T> makeBTreeElement(BKeyObject bkey,
자주 활용되거나, BTreeElem이 아닌 Elem은 만들어 내지 않아서
굳이 새로운 클래스로 뽑아 내어서, 구현할 필요는 없다고 봅니다.

2024-03-20 02:07 UTC, oliviarla commented on src/main/java/net/spy/memcached/util/BTreeUtil.java
> +  public static <T> Element<T> makeBTreeElement(BKeyObject bkey,
기존 Element 클래스에 이 메서드를 두자는 것입니다.
참고로 유틸성 클래스는 객체 지향적이지 않기 때문에 가능한 클래스쪽에 메서드를 두는 것이 좋아보입니다.
[링크](https://www.mimul.com/blog/oop-alternative-to-utility-classes/) 참고해주세요.

2024-03-20 02:14 UTC, brido4125 commented on src/main/java/net/spy/memcached/util/BTreeUtil.java
> +  public static <T> Element<T> makeBTreeElement(BKeyObject bkey,
Element 클래스는 사용자에게 노출되는 인터페이스입니다.

사용자가 반환 받는 인스턴스에 위와 같은 인스턴스 생성 메서드를 추가해 
불필요한 인터페이스 노출을 증가 시킬 필요는 없을것 같네요.

객체 지향을 준수하는것도 좋지만, 사용자 편의가 더 중요하다고 생각합니다.

2024-03-20 02:28 UTC, oliviarla commented on src/main/java/net/spy/memcached/util/BTreeUtil.java
> +  public static <T> Element<T> makeBTreeElement(BKeyObject bkey,
흠 그런 문제가 있군요.. 지금은 이대로 두고 나중에 좋은 방안이 있으면 변경하면 될 것 같습니다.

2024-03-20 03:36 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +      return buildResult();
질문이 몇 가지 있습니다.
- 이 부분에서 아직 decode 되지 않은 상태이므로 result에 buildResult의 결과를 할당하고 반환해야 하는 것 아닌가요?
- 그리고 if문 조건에 맞지 않는다면 decode완료된 상태이거나 cacheDataMap이 비어있는 상태이니 result를 반환해도 괜찮지 않나요?
- isDecoded 변수가 BopGetBulkResultImpl에서만 사용되는 이유를 알려주실 수 있나요?

2024-03-20 05:21 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +      return buildResult();
말씀하신 사항들 고려하다보니,
buildResult와 Atomic을 사용하는 방안은 
다른 Result 클래스의 `getDecodedValue`와 일관성이 전혀 없어서
다른 방식으로 수정하였습니다.

> isDecoded 변수가 BopGetBulkResultImpl에서만 사용되는 이유를 알려주실 수 있나요?

bopBulkGet의 경우 result 변수에 decode된 elem이 담기지 않고 
내부의 TreeMap에 담겨 다른 Result 클래스들과는 다른 방식으로 DecodeElem의 존재 여부를 확인해야합니다.

2024-03-20 05:25 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +      return buildResult();
@brido4125 
다른 Result 객체의 getDecodedValue() 메소드 구현과 동일하게 맞추면 낫습니다.

2024-03-20 07:02 UTC, oliviarla approved these changes

2024-03-20 07:02 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +  private boolean resultDecoded() {
isDecoded()로 메서드 명 변경하면 어떨까요?

2024-03-20 10:35 UTC, uhm0311 requested changes

2024-03-20 10:35 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +  }
result 객체를 두는 것은 cachedDataMap을 순회하며 decoding 작업을 하지 않기 위함입니다.
현재 구현으로는 result가 모두 decode 된 상태여도 result 객체를 순회해야 합니다.

이 메소드를 수행하는 주체는 응용의 쓰레드이긴 하지만, 조금 더 최적화할 수 있습니다.
AtomicBoolean을 하나 두고, isDecoded() == true인 경우에 한해 AtomicBoolean.set(true)를 한 다음, AtomicBoolean.get() == true이면 isDeocded() 메소드에서 AtomicBoolean.get()을 반환하도록 합시다.

2024-03-20 10:35 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isDecoded() && !cachedDataMap.isEmpty()) {
isDecoded() 메소드의 사용법이 이상합니다.
decode가 된 상태인데 또 decode를 하나요?

2024-03-21 01:21 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isDecoded() && !cachedDataMap.isEmpty()) {
`isDecoded` 메서드 명이 헷갈릴만 하네요
`isResultEmpty` 로 변경하겠습니다.

2024-03-21 01:22 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +  }
> 현재 구현으로는 result가 모두 decode 된 상태여도 result 객체를 순회해야 합니다.

`break;`를 걸어놔, 순회를 최적화 하였습니다.
아무래도 다른 `XXXResultImpl`과의 통일성을 위해 `AtomicBoolean`을 사용하지 않는 방향이 좋을 것 같고, 이에 대한 트레이드 오프로 첫번째 Result 객체의 isEmtpy()를 호출하는 로직은 감안해야한다고 생각합니다.

2024-03-21 01:44 UTC, uhm0311 requested changes

2024-03-21 01:44 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    boolean isEmpty = true;
이 변수는 필요 없습니다.

2024-03-21 01:44 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +        break;
여기서 false 반환하면 됩니다.

2024-03-21 01:44 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    return isEmpty;
여기선 true를 반환하구요.

2024-03-21 05:10 UTC, uhm0311 approved these changes

2024-03-21 06:52 UTC, jhpark816 reviewed
리뷰 완료

2024-03-21 08:08 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
`getDecodedValue`에서 result를 생성하려면, gotKey 콜백 메서드의 elementCount, api 호출 인자인 reverse, 그리고 getDecodedValue 내부에서 제네릭 K 타입에 따라 Tree 인스턴스의 구현체도 분기해서 처리해줘야합니다.
또한 다른 XXXReuslt 클래스에서는 사용하지 않는 `opStatusMap` 인스턴스도 인자로 넘겨줘야하구요.

IO 스레드가 `BTreeGetResult`를 생성하지 않는다라는 점이 이점일 것 같은데, 해당 로직이 IO 연산도 아닌 bTree 개수만큼의 인스턴스 생성 로직이라 성능에 많은 영향을 미칠것 같지는 않습니다.

2024-03-21 10:47 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
@uhm0311 위의 논의를 확인하고, 의견주세요.

2024-03-22 02:20 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
@jhpark816 

> getDecodedValue에서 result를 생성하려면, gotKey 콜백 메서드의 elementCount, api 호출 인자인 reverse, 그리고 getDecodedValue 내부에서 제네릭 K 타입에 따라 Tree 인스턴스의 구현체도 분기해서 처리해줘야합니다.

이 부분을 해결하기 위해 gotKey() 메소드가 있었고, 내부적으로 TreeMap 타입에 대한 분기를 할 필요 없도록 ByteArrayTreeMap을 사용하도록 했던 것입니다.
https://github.com/naver/arcus-java-client/pull/719#discussion_r1526217582 이 의견에 따라 gotKey() 메소드가 제거된 상태이므로, 다음과 같은 구현으로 변경해야 합니다.
이 부분이 GetResult 구현체 간의 일관성을 해치게 되는데도 괜찮나요?

```java
// operation callback
@Override
public void gotKey(String key, int elementCount, OperationStatus status) {
  result.gotKey(key, elementCount, status);
}
```

```java
// BopGetBulkResultImpl

private final Map<...> opStatusMap = ...
private final Map<...> elementCountMap = ...

public void gotKey(String key, int elementCount, OperationStatus status) {
  elementCountMap.put(key, elementCount);
  opStatusMap.put(key, status);
}

private Map<...> buildResult() {
  Map<...> result = ...

  for (String key : opStatusMap.keys()) {
    TreeMap<K, BTreeElement<K, V>> tree = null;
    int elementCount = elementCountMap.get(key);

    if (elementCount > 0) {
      tree = new ByteArrayTreeMap<K, BTreeElement<K, V>>(
              (reverse) ? Collections.reverseOrder() : null);
    }
    result.put(key, new BTreeGetResult<K, V>(tree, new CollectionOperationStatus(opStatusMap.get(key))));
  }

  return result;
}
```
```

2024-03-22 02:32 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
첨고로, 아래 구조의 cachedDataMap을 사용할 수도 있습니다.
```java
Map<String, Map.Entry<CollectoinOperationStatus, List<BTreeElement<K, CachedData>>>>
```

2024-03-22 02:36 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
해당 코멘트도 CachedData 구조가 다른 Result 객체들과 달라, 추후에 해당 코드를 읽는 사람 입장에서 해당 구현에 대해 한번 더 생각해야하는 공수를 발생시키는건 동일하지 않나요?

현재 구조에서 변경하는것을 의도 하시는데, 현재 구조가 가지는 단점이 있을까요?

2024-03-22 02:46 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
`Map.Entry<CollectoinOperationStatus, List<BTreeElement<K, CachedData>>>`

이 부분은 너무 깁니다.
사용한다면 구조체로 사용할 클래스를 하나 두는 것이 맞아 보입니다.
또한 일관성이 깨지는 것은 마찬가지입니다.

2024-03-22 02:48 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
아래와 같이 getDecodedValue() 구현을 일관되게 만들었으면 합니다.
구현 로직을 다르게 가져갈 이유가 없습니다.
```java
if (result.isEmpty() && !cachedDataMap.isEmpty()) {
  temp = new HashMap<String, BTreeGetResult<K, V>>(. . .);
  . . .
  result = temp;
}
return result;
```

각 b+tree 조회에 대해 아래 정보만 있으면 됩니다.
- treemap  of elements
- operationStatus

따라서, Result 객체에 각각을 Map을 두었다가  getDecodedValue()에서 result 생성할 수 있고
- cachedDataMap
- opStatusMap

Entry<operationStatus, treeMap> 값을 가지는 Map을 두었다가 
getDecodedValue()에서 result 생성할 수도 있습니다.

2024-03-22 02:55 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
`GetResult 구현체 간 필드의 일관성`이 아니라 `getDecodedValue() 메소드 구현의 일관성` 이군요.

2024-03-22 03:03 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
> 구현 로직을 다르게 가져갈 이유가 없습니다.

현재 로직과 다른 XXXResult 객체의 `getDecodedValue` 로직을 비교하였을 때,
`isResultEmpty` 메서드 호출 로직을 제외하고는 다른 점이 없습니다.

bopGetBulk를 이해한다는 가정하에서는 
현재 사용되는 `isResultEmpty` 로직의 의도를 쉽게 이해할 수 있습니다.

오히려 해당 PR의 이슈부분에서 논의된것처럼 XXXReuslt 클래스간의 일관성이 지켜져야
유지보수 하는 입장에서 쉽게 구조를 파악할 수 있습니다.

2024-03-22 03:29 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
@brido4125
BopGetBulkResultImpl 사항은 초기부터 계속하여 논의했던 사항입니다.
생성자에서 result 인자를 제거하는 방안을 찾으려고 했던 것이며,
이를 통해 생성자 함수와 getDecodedValue() 동작을  일관되게 만들려고 했던 것입니다.

코드 리뷰해 보니, 이렇게 구현하는 것이 가능하여 리뷰 코멘트를 남긴 것입니다.

`XXXReuslt 클래스간의 일관성`이 무엇인지는 모르겠지만,
`GetResult 구현체 간 필드의 일관성` 관점에서
Result 객체는 해당 연산에 따라 해당 필드가 달라질 수 있습니다.
- 저장할 데이터 타입이나 저장 구조가 달라짐.
- 정렬이 필요하면 reverse 같은 필드가 추가될 수 있음.

하지만, 해당 Result 객체를 인터페이스나 기본 동작 방식은 동일하게 맞춰두면 좋겠다는 의견입니다.

2024-03-22 03:50 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
@jhpark816 

이해가 안가는 부분이 있습니다.
`getDecodedValue`의 동작을 일관되게 구현하는것이 목표인데,
아래 코드에서 `...` 부분이 구현이 가장 크게 달라지는 부분이 될 것으로 예상됩니다.

```java
if (result.isEmpty() && !cachedDataMap.isEmpty()) {
  temp = new HashMap<String, BTreeGetResult<K, V>>(. . .);
  . . .
  result = temp;
}
return result;
```

아마 아래 코멘트의 buildResult와 같이 구현될 것 같은데, 
이러한 변경이 현재 구현보다 `getDecodedValue`의 동작을 더 다르게 하는 것 아닌가요?
https://github.com/naver/arcus-java-client/pull/719#discussion_r1534956729

만약 위 코멘트처럼 gotKey를 내부적으로 사용하지 않는다면
opStatusMap, elementCountMap을 생성자를 통해 넘겨줘야 합니다.

이또한 result 객체를 인자로 넘기진 않지만, 더 복잡한 생성자 구성을 가지게 되는것입니다.

2024-03-22 04:23 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
> opStatusMap, elementCountMap을 생성자를 통해 넘겨줘야 합니다.

`Map<String, Map.Entry<CollectoinOperationStatus, List<BTreeElement<K, CachedData>>>>` 타입 사용을 염두한 것 같습니다.
저는 `Map.Entry<CollectoinOperationStatus, List<BTreeElement<K, CachedData>>>` 부분을 클래스화 하여 구조체로 쓰는 게 더 좋을 것 같습니다.

2024-03-22 04:32 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
우선 `Map<String, Map.Entry<CollectoinOperationStatus, List<BTreeElement<K, CachedData>>>>`로 변경해볼게요.

2024-03-22 04:39 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
bopGetBulk의 Result 객체에서 cachedDataMap 데이터 타입은 의미적으로
`Map<String, Map.Entry<CollectoinOperationStatus, List<BTreeElement<K, CachedData>>>>` 입니다.

데이터 타입이 복잡하다면, 아래 2가지 Map으로 분리하여 사용할 수 있다는 것입니다.
- `Map<String, CollecitonOperationStatus>` : opStatusMap
- `Map<String, List<BTreeElement<K, CachedData>>>`: cacheDataMap

getDecodedValue() 구현에서 달라지는 부분은
결과를 담는 데이터 타입과 구조가 각각 다르기 때문에, 달라질 수 밖에 없습니다.

위의 데이터 타입과 저장 구조를 사용한 구현체가 복잡하다고 판단될 경우만
별도의 클래스화가 필요할 수 있지만,
현재는 bopGetBulk 수행 결과에 맞는 데이터 타입이 그대로 드러나는 것이 나을 것 같은 의견입니다.
실제 구현체를 보면 감이 정확히 올 것 같습니다.

2024-03-22 04:59 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
참고 사항을 하나 더 적어 둡니다.

bopGetBulk 연산에서 `future.get()`의 리턴 타입이 `Map<String, BTreeGetResult<Long, T>>` 입니다.
CollectionOperationStatus 포함한 결과를 리턴한다고 BTreeGetResult 클래스를 정의한 것입니다.

이 보다는 
`future.get()`의 리턴 타입이 `Map<String, TreeMap<Long, BTreeElement<T>>>` 형태가 더 적합하게 보이며,
각 key에 대한 연산의 OperationStatus는 `future.getOperationStatus(key)`를 통해 
얻을 수 있게 제공하는 것이 나을 것 같습니다.


Map<String, List<BTreeElement<K, CachedData>>>:

2024-03-25 02:05 UTC, jhpark816 commented
@uhm0311 @oliviarla 최근 변경을 리뷰 바랍니다.

2024-03-25 02:06 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +    if (isResultEmpty() && !cachedDataMap.isEmpty()) {
@uhm0311 @oliviarla 
참고로 bopBulkGet 부분만 변경되었습니다.

2024-03-25 06:15 UTC, uhm0311 requested changes

2024-03-25 06:15 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
이런 형태로는 코드를 읽기가 어렵네요.
다음의 값들을 적절한 이름의 변수에 담아 사용합시다.
- entry.getKey()
- entry.getValue()
- entry.getValue().getKey()
- entry.getValue().getValue()

혹은 `Map.Entry<CollectionOperationStatus, List<BTreeElement<K, CachedData>>>` 부분을 클래스화 하여 구조체로 사용하고, 적절한 필드명으로 값을 가져오는 것도 좋습니다.
개인적으로는 cachedDataMap 필드의 선언 타입도 간소화 할 수 있으니 클래스화 하는 것이 더 좋아 보입니다.

getDecodedValue2() 메소드를 만들어서 두 방안 모두 적용해보시죠.

2024-03-25 06:15 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +        if (temp.get(entry.getKey()) == null) {
temp 맵의 키로 entry.getKey()를 사용하여 접근하는 것이 조금 반복되네요.
`temp.get(entry.getKey())`를 변수에 담아서 사용합시다.

```java
변수 = temp.get(entry.getKey());
if (변수 == null) {
  ...
  temp.put(entry.getKey(), 변수);
}
변수.addElements(...);
```

2024-03-25 06:33 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          List<BTreeElement<K, CachedData>>>> cachedDataMap,
indent 맞춰야할 것 같습니다.

2024-03-25 06:33 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +          temp.put(bKey, new Element<V>(((ByteArrayBKey) bKey).getBytes(),
여기서는 BTreeUtil#makeBTreeElement 메서드를 사용할 수 없는건가요?

2024-03-25 06:35 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +          temp.put(bKey, new Element<V>(((ByteArrayBKey) bKey).getBytes(),
헷갈리만 하신데, `makeBTreeElement`는 `Element` 타입을 생성하고
위 로직에서 필요한거는 `BTreeElement` 타입입니다.

2024-03-25 07:07 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +          temp.put(bKey, new Element<V>(((ByteArrayBKey) bKey).getBytes(),
BTreeElement 타입을 사용하는 API는 getBulk의 경우밖에 없는 것으로 알고있는데, 이 Result 클래스는 단일 get 연산에서 사용되기 때문에 BTreeElement를 사용하지 않을 것일텐데 제가 잘못 이해하고 있나요?

그리고, makeBTreeElement 메서드의 이름을 makeElement로 하는 것이 헷갈림을 방지할 수 있을 것 같습니다.

2024-03-25 07:15 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +          temp.put(bKey, new Element<V>(((ByteArrayBKey) bKey).getBytes(),
제가 클래스명을 bulk로 착각했네요 확인 다시 해볼게요

2024-03-25 07:21 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
### 1안
```java
@Override
  public Map<String, BTreeGetResult<K, V>> getDecodedValue() {
    if (result.isEmpty() && !cachedDataMap.isEmpty()) {
      Map<String, BTreeGetResult<K, V>> temp = new HashMap<String, BTreeGetResult<K, V>>(result);
      for (Map.Entry<String, Map.Entry<CollectionOperationStatus,
              List<BTreeElement<K, CachedData>>>> entry : cachedDataMap.entrySet()) {

        String key = entry.getKey();
        Map.Entry<CollectionOperationStatus,
                List<BTreeElement<K, CachedData>>> treeList = entry.getValue();
        CollectionOperationStatus opStatus = treeList.getKey();
        List<BTreeElement<K, CachedData>> elems = treeList.getValue();
        BTreeGetResult<K, V> each = temp.get(key);

        if (each == null) {
          TreeMap<K, BTreeElement<K, V>> tree = null;
          if (!elems.isEmpty()) {
            tree = new ByteArrayTreeMap<K, BTreeElement<K, V>>(
                    reverse ? Collections.<K>reverseOrder() : null);
          }
          each = new BTreeGetResult<K, V>(tree, opStatus);
          temp.put(key, each);
        }
        each.addElements(elems, transcoder);
      }
      result = temp;
    }
    return result;
  }
```
### 2안
새로운 클래스 이름은 `BopBulkData`입니다. 

```java
public Map<String, BTreeGetResult<K, V>> getDecodedValue() {
    if (result.isEmpty() && !cachedDataMap.isEmpty()) {
      Map<String, BTreeGetResult<K, V>> temp = new HashMap<String, BTreeGetResult<K, V>>(result);
      for (Map.Entry<String, BopBulkData<K>> entry : cachedDataMap.entrySet()) {
        String key = entry.getKey();
        BopBulkData<K> data = entry.getValue();

        BTreeGetResult<K, V> each = temp.get(key);
        if (each == null) {
          TreeMap<K, BTreeElement<K, V>> tree = null;
          if (!data.getElems().isEmpty()) {
            tree = new ByteArrayTreeMap<K, BTreeElement<K, V>>(
                    reverse ? Collections.<K>reverseOrder() : null);
          }
          each = new BTreeGetResult<K, V>(tree, data.getOpStatus());
          temp.put(key, each);
        }
        each.addElements(data.getElems(), transcoder);
      }
      result = temp;
    }
    return result;
  }


  public static class BopBulkData<K> {
    private final CollectionOperationStatus opStatus;
    private final List<BTreeElement<K, CachedData>> elems;

    public BopBulkData(CollectionOperationStatus opStatus,
                       List<BTreeElement<K, CachedData>> elems) {
      this.opStatus = opStatus;
      this.elems = elems;
    }

    public CollectionOperationStatus getOpStatus() {
      return opStatus;
    }

    public List<BTreeElement<K, CachedData>> getElems() {
      return elems;
    }
  }
```

막상 1안도 변수화 시켜보니 읽을만해서 괜찮을 것 같기도 합니다.

2024-03-25 07:33 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
만약 2안을 적용한다면 `data.getElems().isEmpty()` 부분은 `data.isElemsEmpty()`와 같은 메소드를 추가합시다.
1안은 cachedDataMap 변수의 선언 타입이 읽기 힘듭니다.

2024-03-25 07:35 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          List<BTreeElement<K, CachedData>>>> cachedDataMap,
check-style 통과 되면 Indent 된것 아닌가요??

2024-03-25 07:35 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
@jhpark816 

어떤것으로 구현할까요?

2024-03-25 07:38 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          List<BTreeElement<K, CachedData>>>> cachedDataMap,
cachedDataMap 매개변수와 다른 매개변수들의 indent 차이를 확인해보세요.

2024-03-25 07:53 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          List<BTreeElement<K, CachedData>>>> cachedDataMap,
다른 매개변수의 경우 `List<BTreeElement, ...>`가 아닌 `Map<String, ...>`과 동일하게 맞춰야하는거 아닌가요??

2024-03-25 07:55 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          List<BTreeElement<K, CachedData>>>> cachedDataMap,
그럼 현재 cachedDataMap 매개변수의 indent는 그대로 냅둬도 되나요? 혹은 수정해야 하나요?

2024-03-25 07:58 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          List<BTreeElement<K, CachedData>>>> cachedDataMap,
`getDecodedValue` 구현 방법이 현재 방식대로 가면 놔두고, 변경 된다면 수정이 필요합니다.

2024-03-25 08:03 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
@brido4125 @uhm0311 
어떤 구현이 좋은 지 검토할게요.

2024-03-25 08:19 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
@brido4125 
1안에서 아래 코드를 수행할 필요가 있나요?
`temp` HashMap에는 해당 key가 없기 때문에 무조건 `each == null` 조건이 만족되지 않나요?
```java
        BTreeGetResult<K, V> each = temp.get(key);
        if (each == null) {
        }
```

2024-03-25 08:21 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
https://github.com/naver/arcus-java-client/pull/719#discussion_r1537097472
위 코멘트의 반복되는 호출 때문에 수행시켰습니다.

2024-03-25 08:32 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
코멘트 의도는 temp.get() 수행하는 이유를 물어본 것입니다.
temp.get() 결과는 항상 null이어서 수행 이유가 없어 보입니다.

2024-03-25 08:45 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
구현 방향 결정되면 반영하겠습니다.

2024-03-25 08:52 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
구현 정확성을 질문한 것이고, 구현 방향과는 무관합니다.

2024-03-25 08:55 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
말씀하신대로 필요없는 분기처리이니 반영하겠다라는 의미로 코멘트 남겼습니다.

2024-03-25 09:10 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
그러면, 1안과 2안의 예제 코드를 수정해 주시죠. 간단한 것이라 금방 할 겁니다.

2024-03-25 11:06 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
@brido4125 @uhm0311 
1안과 2안을 확인해 보니, 아래의 `btreeGetBulk()` 메소드 구현과 같이
cachedDataMap과 opStatusMap을 따로 두는 것이 나은 것 같습니다

```java
  private <T> CollectionGetBulkFuture<Map<String, BTreeGetResult<Long, T>>> btreeGetBulk(
          final List<BTreeGetBulk<T>> getBulkList,
          final boolean reverse, final Transcoder<T> tc) {

    final Map<String, List<BTreeElement<Long, CachedData>>> cachedDataMap =
            new HashMap<String, List<BTreeElement<Long, CachedData>>>();
    final Map<String, CollectionOperationStatus> opStatusMap =
            new HashMap<String, CollectionOperationStatus>();
    final GetResult<Map<String, BTreeGetResult<Long, T>>> result =
            new BopGetBulkResultImpl<Long, T>(cachedDataMap, opStatusMap, reverse, tc);

    for (BTreeGetBulk<T> getBulk : getBulkList) {
      Operation op = opFact.bopGetBulk(getBulk, new BTreeGetBulkOperation.Callback() {
        @Override
        public void gotKey(String key, int elementCount, OperationStatus status) {
          if (elementCount > 0) {
            cachedDataMap.put(key, new ArrayList<BTreeElement<Long, CachedData>>());
          }
          opStatusMap.put(key, new CollectionOperationStatus(status));
        }

        @Override
        public void gotElement(String key, int flags, Object bkey, byte[] eflag, byte[] data) {
          List<BTreeElement<Long, CachedData>> elements = cachedDataMap.get(key);
          assert elements != null : "Element list not prepared in bopGetBulk";
          elements.add(new BTreeElement<Long, CachedData>((Long) bkey, eflag,
                  new CachedData(flags, data, tc.getMaxSize())));
        }
      });

      ops.add(op);
      addOp(getBulk.getMemcachedNode(), op);
    }

    return new CollectionGetBulkFuture<Map<String, BTreeGetResult<Long, T>>>(
        latch, ops, result, operationTimeout);
  }
```


BopGetBulkResultImpl 생성자는 cachedDataMap과 opStatusMap을 인자로 받아야 하고,
`getDecodedValue()` 메소드는 아래와 같이 구현할 수 있습니다.

```java
  public Map<String, BTreeGetResult<K, V>> getDecodedValue() {
    if (result.isEmpty() && !opStatusMap.isEmpty()) {
      Map<String, BTreeGetResult<K, V>> temp = new HashMap<String, BTreeGetResult<K, V>>(result);
      for (Map.Entry<String, CollectionOperationStatus> entry : opStatusMap.entrySet()) {
        String key = entry.getKey();
        List<BTreeElement<K, CachedData>> elements = cachedDataMap.get(key);
        if (elements != null) {
          BTreeGetResult<K, V> each = new BTreeGetResult<K, V>(
              new ByteArrayTreeMap<K, BTreeElement<K, V>>(
                  reverse ? Collections.<K>reverseOrder() : null),
              entry.getValue());
          each.addElements(elements, transcoder);
          temp.put(key, each);
        } else {
          temp.put(key, new BTreeGetResult<K, V>(null, entry.getValue()));
        }
      }
      result = temp;
    }
    return result;
  }
```

위의 `getDecodedValue()` 메소드가  복잡해 보입니다.
이를 단순화시키기 위해 `BTreeGetResult()` 메소드를 아래와 같이 수정합니다.
현재 구현 방향에서는 `addElements()` 메소드를 두는 것보다
 아래와 같이 생성자를 수정하는 것이 나은 것 같습니다.

```java
  public BTreeGetResult(List<BTreeElement<K, CachedData>> elemList,
                        boolean reverse, Transcoder<V> transcoder,
                        CollectionOperationStatus opStatus) {
    if (elemList != null) {
      elements = new ByteArrayTreeMap<K, BTreeElement<K, V>>(
                     reverse ? Collections.<K>reverseOrder() : null);
      for (BTreeElement<K, CachedData> elem : elemList) {
        elements.put(elem.getBkey(),
                     new BTreeElement<K, V>(elem.getBkey(), elem.getEflag(),
                         transcoder.decode(elem.getValue())));
      }
    } else {
      elements = null;
    }
    this.opStatus = opStatus;
  }
```

그리고, `getDecodedValue()` 메소드는 아래와 같이 구현할 수 있습니다.
이렇게 수정하는 것이 좋겠습니다.

```java
  public Map<String, BTreeGetResult<K, V>> getDecodedValue() {
    if (result.isEmpty() && !opStatusMap.isEmpty()) {
      Map<String, BTreeGetResult<K, V>> temp = new HashMap<String, BTreeGetResult<K, V>>(result);
      for (Map.Entry<String, CollectionOperationStatus> entry : opStatusMap.entrySet()) {
        String key = entry.getKey();
        temp.put(key, new BTreeGetResult<K, V>(cachedMapdata.get(key), reverse, transcoder,
                                               entry.getValue());
      }
      result = temp;
    }
    return result;
  }
```

2024-03-26 02:08 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
@jhpark816 
`if (elemList != null)`이 아닌 `if (!elemList.isEmpty())` 를 통해 Tree 객체를 생성할지 말지 결정해야합니다.
서버로 전달되는 KeyList는 validation에 의해 비어있지 않기 때문에 gotKey()는 항상 호출되어 null인 경우가 없습니다.

2024-03-26 02:14 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
@brido4125 
위의 `gotKey()` 로직에서 elementCount가 0이면 cachedDataMap에 empty elementList를 추가하지 않습니다.
따라서, BTreeGetResult 생성 시에 `cachedDataMap.get(key)` 인자 값은 null이 됩니다.

2024-03-26 02:28 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
현재 PR 구현대로, `if (elementCount > 0)`를 확인하지 않을 경우 null 체크를 할 필요는 없습니다.
말씀하신 구현대로라면 gotElement에서도 assert 등의 로직이 들어가야하는데 불필요하지 않나요?

2024-03-26 02:41 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
BTreeGetResult 생성자에 대해 코멘트하는 거죠?
어떤 구현이면 좋은 지를 코드로 보여주세요.


> 말씀하신 구현대로라면 gotElement에서도 assert 등의 로직이 들어가야하는데 불필요하지 않나요?
assert 로직은 정상적이면 항상 만족하게 됩니다.
SW 버그로 응답 처리에 버그가 있거나 캐시 서버에서 응답 형식이 변경되면 발생할 수 있습니다.

2024-03-26 02:47 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
@jhpark816 

> 어떤 구현이면 좋은 지를 코드로 보여주세요.

현재 PR 구현이 제가 말한 방식으로 구현되어있습니다.
BTreeGetResult 생성자와 gotKey 로직과 gotElement 로직을 확인하시면 됩니다.

그래도 코드를 코멘트에 남길까요?

2024-03-26 03:20 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
@brido4125 
코드를 확인했습니다.
elementCount == 0인 경우 element가 없다는 것을 null로 표현할 수 있습니다.
**이를 empty ArrayList 객체를 생성하여 표현하는 것이 나은 방안임을 설명할 수 있나요?**
참고로, BTreeGetResult에서도 elemens가 없음을 null로 표현하고 있습니다.

만약, emtpy ArrayList 객체를 생성하여 cachedDataMap에 추가한다면,
아래 코드와 같이 opSatusMap 기준이 아니라 cachedDataMap 기준으로 구현할 수 있습니다.

```java
   public Map<String, BTreeGetResult<K, V>> getDecodedValue() {
    if (result.isEmpty() && !cachedDataMap.isEmpty()) {
      Map<String, BTreeGetResult<K, V>> temp = new HashMap<String, BTreeGetResult<K, V>>(result);
      for (Map<String, List<BTreeElement<Long, CachedData>>> entry : opStatusMap.entrySet()) {
        String key = entry.getKey();
        temp.put(key, new BTreeGetResult<K, V>(entry.getValue(),
                reverse, transcoder, opStatusMap.get(key)));
      }
      result = temp;
    }
    return result;
  }
```

2024-03-26 04:40 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
> 이를 empty ArrayList 객체를 생성하여 표현하는 것이 나은 방안임을 설명할 수 있나요?

gotKey의 elementCount 인자를 사용하지 않는 방향 때문에 해당 구현을 제안드렸습니다.
gotElement내에서 인자를 추가해주는 여부에 따라 elementCount를 파악할 수 있기에 중복적인 의미를 지닐 필요가 없을 것 같다고 생각합니다.

2024-03-26 05:51 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
@brido4125 
`gotKey()`에서 elementCount 인자는 그대로 두는 것이 좋습니다.
- server response string에 있는 정보를 넘겨주는 것임.
- 향후 elementCount 값에 처리 로직을 최적화할 수 있음.
- elementCount == 0이면 element List 생성하지 않는 것도 결국 하나의 최적화임.

결국, `elementCount > 0` 경우만 empty elementList 생성하도록 합시다.

2024-03-26 06:26 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java
> +          if (!entry.getValue().getValue().isEmpty()) {
반영하였습니다.

2024-03-26 12:06 UTC, oliviarla reviewed
리뷰 완료입니다.

2024-03-26 23:43 UTC, brido4125 commented on src/main/java/net/spy/memcached/collection/BTreeGetResult.java
> +  private SortedMap<K, BTreeElement<K, V>> elements = null;
명시적으로 대입하는게 직관적이여서, 초기화시켰습니다.

2024-03-26 23:47 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/BTreeStoreAndGetFuture.java
> +  private GetResult<Element<E>> element;
https://github.com/naver/arcus-java-client/pull/719#discussion_r1524863858
위 코멘트 때문에 result -> element로 변경하였습니다.

2024-03-27 01:00 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/BTreeStoreAndGetFuture.java
> +  private GetResult<Element<E>> element;
@oliviarla 

이 Future의 실제 result는 store가 잘 되었는지 여부를 확인하는 Boolean이기 때문에 element가 더 낫습니다.

2024-03-27 01:47 UTC, uhm0311 requested changes

2024-03-27 01:47 UTC, uhm0311 commented on src/main/java/net/spy/memcached/collection/BTreeGetResult.java
> +    }
```java
if (elementList == null) {
  this.elements = null;
  return;
}

this.elements = new ...
...
```

이렇게 하면 elements를 다시 final로 선언할 수 있습니다.
elements는 생성자에서 값을 초기화하는 것 외에는 다시 값이 바뀌진 않으므로 final로 선언합시다.

2024-03-27 01:47 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +    }
이 if문 내에서는 cachedDataMap에 element가 항상 있으므로, 다음과 같이 `instanceof` 연산의 횟수를 줄일 수 있습니다.

```java
... entrySet = cachedDataMap.entrySet();
K bkey = entrySet.iterator().next().getKey();

boolean isByteBkey = (bKey instanceof ByteArrayBKey);
boolean isLongBkey = (bKey instanceof Long);

TreeMap<K, Element<V>> temp;

if (isByteBkey) {
  temp = new ByteArrayTreeMap<...>(...);
} else if (isLongBkey) {
  temp = new TreeMap<...>(...);
} else {
  return result; // result의 기본 타입을 TreeMap으로 변경해도 됨
}

for (... entry : entrySet) {
  bkey = entry.getKey();
  CachedData cachedData = entry.getValue();
  if (isByteBkey) {
    ...
  } else if (isLongBkey) {
    ...
  }
}
result = temp;
```

2024-03-27 02:11 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +    }
@uhm0311 

>  // result의 기본 타입을 TreeMap으로 변경해도 됨

현재 result 변수의 타입은 TreeMap인데, 주석은 어떤 의미일까요?

그리고 아래와 같이 구현해도 되지 않나요? bkey는 gotData에서 Long 또는 ByteArrayBKey로 변환되어 cachedDataMap에 put 됩니다.
```java
      //...
      TreeMap<K, Element<V>> temp = null;
      if (isByteBKey) {
        temp = new ByteArrayTreeMap<K, Element<V>>(reverse ? Collections.<K>reverseOrder() : null);
      } else if (isLongBKey) {
        temp = new TreeMap<K, Element<V>>(reverse ? Collections.<K>reverseOrder() : null);
      }
      //...
```

2024-03-27 02:41 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +    }
> 현재 result 변수의 타입은 TreeMap인데, 주석은 어떤 의미일까요?

생성자에서 result 변수의 초기화를 ByteArrayTreeMap이 아닌 일반 TreeMap으로 해도 된다는 의미입니다.

---

> 아래와 같이 구현해도 되지 않나요?

`!isByteBKey && !isLongBKey`인 경우가 없다는 의미인가요?
저 경우 원래는 `assert false : "..."`를 해도 됩니다.
다만 이러면 응용 프로세스가 중지되므로 Empty Map을 반환한다는 의미로 `return result`를 한 것입니다.

만약 다른 의미였다면 알려주세요.

2024-03-27 02:58 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +    }
반영하였습니다.

2024-03-27 03:17 UTC, uhm0311 requested changes

2024-03-27 03:17 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetByPositionResultImpl.java
> +  private TreeMap<Integer, Element<T>> result;
TreeMap 타입으로 선언된 변수들을 SortedMap 타입으로 선언하도록 합시다.

2024-03-27 03:17 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +            (reverse) ? Collections.reverseOrder() : null);
만약 Checkstyle이 허용한다면 1 Line으로 변경합시다.

2024-03-27 05:40 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +            (reverse) ? Collections.reverseOrder() : null);
반영하였습니다.

2024-03-27 06:03 UTC, uhm0311 requested changes

2024-03-27 06:03 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetByPositionResultImpl.java
> +      TreeMap<Integer, Element<T>> temp = new TreeMap<Integer, Element<T>>(result);
SortedMap으로 선언

2024-03-27 06:03 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
> +      TreeMap<K, Element<V>> temp;
SortedMap으로 선언

2024-03-27 07:11 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetByPositionResultImpl.java
> +    result = new TreeMap<Integer, Element<T>>((reverse) ? Collections.reverseOrder() : null);
`this.`가 없는 것은 1 Line으로 표현하기 위함인가요?

2024-03-27 07:14 UTC, brido4125 commented on src/main/java/net/spy/memcached/internal/result/BopGetByPositionResultImpl.java
> +    result = new TreeMap<Integer, Element<T>>((reverse) ? Collections.reverseOrder() : null);
사용하지 않아도 상관없어서 제외 했는데, 거슬리면 this가 없는 문장을 한칸 아래로 내릴까요?

2024-03-27 07:29 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/result/BopGetByPositionResultImpl.java
> +    result = new TreeMap<Integer, Element<T>>((reverse) ? Collections.reverseOrder() : null);
다른 생성자들을 보면 `this.`를 붙이고 있으니 여기도 붙이는 게 좋겠습니다.

2024-03-27 07:45 UTC, uhm0311 approved these changes

2024-03-28 02:23 UTC, oliviarla approved these changes

2024-03-28 09:20 UTC, merged