ENHANCE: Change creating callback objects multiple times in pipe operation.
naver/arcus-java-client pull request #727
Opened 2024-03-07 07:35 UTC by brido4125

## 관련 이슈
https://github.com/jam2in/arcus-works/issues/515

## 작업 내용
Piped 연산 시 op 인스턴스는 여러개 생성된다.
이와 동시에 callback 인스턴스도 여러개 생성된다.

하나의 콜백 인스턴스를 복수개의 op 인스턴스가 공유해서 사용하도록 변경한다.

2024-03-07 07:56 UTC, brido4125 commented on src/test/manual/net/spy/memcached/MultibyteKeyTest.java
> +      opFact.collectionPipedInsert(MULTIBYTE_KEY, insert, 0, cpsCallback).initialize();
해당 테스트 케이스는 insert 인스턴스를
btree, list, map, set으로 만들고 나서 하나의 `collectionPipedInsert` op 객체가 
initialize가 되는지 확인하기에 opIdx를 0으로 줘도 무방하다고 판단하였습니다.

2024-03-13 08:50 UTC, uhm0311 requested changes

2024-03-13 08:50 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      @Override// each result status
`// each result status`는 없어도 될 것 같습니다.

2024-03-13 08:50 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      Operation op = opFact.collectionPipedInsert(key, insertList.get(i), i, callback);
OperationFactory는 사용자가 직접 정의하여 구현할 수도 있기 때문에 collectionPipedInsert() 메소드의 인터페이스를 변경하면 작게나마 하위호환성이 깨지게 됩니다.
i 값을 여기서 주는게 아니라 `insertList.get(i)` 객체를 만들 때 미리 i 값을 주는 방안도 검토해주세요.

```java
if (elements.size() <= CollectionPipedInsert.MAX_PIPED_ITEM_COUNT) {
  updateList.add(new MapPipedUpdate<T>(key, elements, tc));
} else {
  PartitionedMap<String, T> list = new PartitionedMap<String, T>(
          elements, CollectionPipedUpdate.MAX_PIPED_ITEM_COUNT);

  for (int i = 0; i < list.size(); i++) {
    updateList.add(new MapPipedUpdate<T>(key, list.get(i), i, tc));
  }
}
```

2024-03-14 00:47 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      Operation op = opFact.collectionPipedInsert(key, insertList.get(i), i, callback);
구현은 가능합니다.
다만, OperationFactory를 직접 구현하여 arcus를 사용하는 유저는 거의 없을 것이라고 판단되고
이를 사용자로 하여금 변경할 수 있게 하는 인터페이스를 노출 시키는게 잘못된 설계가 아닌가 생각합니다.

다른 분들의 의견이 궁금하네요.

2024-03-14 02:07 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      Operation op = opFact.collectionPipedInsert(key, insertList.get(i), i, callback);
@jhpark816 @oliviarla 의견 주세요.

2024-03-14 05:40 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      Operation op = opFact.collectionPipedInsert(key, insertList.get(i), i, callback);
opIdx 값을 개별 operation에 추가하지 말고,
callback에서 opIdx = 0으로 추기화하고, receivedStatus() 호출될 때마다 1증가시켜도 될 것 같습니다.
이 방식이 replication, migration 과는 무관한지는 확인해 보세요.

2024-03-14 07:19 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      Operation op = opFact.collectionPipedInsert(key, insertList.get(i), i, callback);
@jhpark816 
receivedStatus() 호출될 때마다 1증가 시키는 방법을 사용하면, 여러 pipe 요청의 처리 순서를 보장하지 않아 element의 인덱스가 정확하지 않을 가능성이 있지 않나요?

2024-03-14 07:22 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      Operation op = opFact.collectionPipedInsert(key, insertList.get(i), i, callback);
1개 key에 대한 piped 연산들은 하나의 operation queue에 들어가게 되며, 그 queue에 들어간 순서대로 처리됩니다.

2024-03-18 08:11 UTC, uhm0311 requested changes

2024-03-18 08:11 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        opIndex += 1;
`opIndex` vs `opIdx`
같은 PR 내에 변수명이 통일이 되지 않았습니다.

2024-03-19 04:30 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        opIndex += 1;
변경하였습니다.

2024-03-20 08:54 UTC, uhm0311 approved these changes

2024-03-20 11:22 UTC, oliviarla approved these changes

2024-03-20 12:08 UTC, jhpark816 reviewed
리뷰 완료

2024-03-20 12:08 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        opIdx += 1;
opIdx 증가 위치는 complete() 메소드가 아닌지 ?
- receivedStatus()는 응답을 받는 경우만 호출됩니다.
- complete()는 무조건 수행되어야 합니다.

해당 연산이 cancel 되든지 or migration에 의해 이동이 되든지
생성한 op 순서대로 complete()가 호출되는 것이 보장되는 지를 확인해 보세요.

2024-03-20 12:08 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
>        addOp(key, op);
pipe 연산을 하나씩 보내고 있습니다.
pipe 연산 전체가 하나의 연산이므로, 모든 연산이 하나의 node에 전달되어야 합니다.

for 문 수행 중에 node 추가/삭제로 key가 매핑되는 node가 달라지면 문제가 됩니다.
따라서, 아래 형태와 같이 하나의 key로 매팅되는 node에 모든 연산을 add해야 할 것 같습니다.
```java
addOps(key, ops);
```

2024-03-20 12:09 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
>        addOp(key, op);
이 사항은 모든 pipe 연산에 대해 미리 일괄 처리하는 것이 좋겠습니다.

2024-03-21 02:12 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
>        addOp(key, op);
별도 PR로 처리하겠습니다.

2024-03-22 05:33 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
>        addOp(key, op);
@brido4125
pipe 연산들이 하나의 node에 전달되어야 하는 이슈를 먼저 올려주세요.

2024-03-26 05:52 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        opIdx += 1;
@brido4125 
> 해당 연산이 cancel 되든지 or migration에 의해 이동이 되든지
생성한 op 순서대로 complete()가 호출되는 것이 보장되는 지를 확인해 보세요.

위의 사항이 보장되는가요?

2024-03-26 07:01 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        opIdx += 1;
### 정상인 경우
1. 1번 Operation 인스턴스 : 0 ~ 499개
2. 2번 Operation 인스턴스 : 500 ~ 599개

1번 Op의 index가 0 ~ 499로 정상설정
2번 Op의 index가 500 ~ 599로 정상설정

### cancel인 경우
1. 1번 Operation 인스턴스 : 0 ~ 499개
2. 2번 Operation 인스턴스 : 500 ~ 599개

1번 Op가 cancel 되어서 2번이 처리됨 -> 0번 ~ 99번으로 idx 설정됨
하지만, 사용자가 결과를 받을 때 cancel 처리된 op가 존재해서 어차피 결과를 받지 못하고,
ExecutionException 발생해서 idx의 순서는 상관 없게됨.

### Migration인 경우
Pipe 연산의 특성 상, 1번 Op와 2번 Op는 동일한 노드에 매핑되어야 하고
만약 Migration에 의해 두 Op 모두 새로운 노드로 매핑이 변경되어야 한다 해도
기존 노드의 큐에 먼저 들어간 1번 Op가 
새로운 노드의 큐에 drain 될때도 큐의 특성에 의해 op들의 순서가 보장 되기에
OpIdx가 유지 된다고 생각합니다.

2024-03-28 11:46 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        opIdx += 1;
@brido4125
N개의 pipe 연산이 만들어질 경우, 어떤 경우라도 그 pipe 연산의 순서대로 complete() 호출되어야 합니다.
그 연산이 cancel 되거나 migration이 되더라도 생성한 pipe 연산의 순서대로 complete() 호출되어야 합니다.
- 정상인 경우는 당연히 문제 없음 : 하나의 MemcachedNode의 queue에 순서대로 연산을 적재하므로,
- cancel인 경우는 ?
   - 1번 op가 cancel되면, 2번 op가 처리되기 전에 1번 op의 complete()이 먼저 수행되는가?
- migration인 경우는 op drain 시에 op 순서를 유지한다면 문제가 없을 것 같습니다.

@uhm0311 @oliviarla 
이 관점에서 한번 확인 바랍니다.
piped op 순서대로 op.complete()가 수행되게 하여 opIdx를 정확히 유지하는 방법을 사용하였는 데,
이는 op.complete() 수행 순서가 op 순서대로 유지되는 지를 확인해야 하는 부담이 있긴 합니다.
예전처럼 op 내에 opIdx 추가하는 방법이 명확하고 간단한 방법이 아니었나 하는 생각도 듭니다.

2024-03-28 11:52 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        opIdx += 1;
@brido4125 
만약 N개 piped 연산에서 어떤 연산이 cancel되면 그 뒤의 연산들을 모두 cancel해야 할 것 같습니다.
예를 들어, op-1, op-2, op-3가 있다면,
- op-1 수행 성공
- op-2 수행에서 piped_error  또는 cancel 된다면 op-3는 아예 수행하지 않아야 함.
 
이렇게 동작하는 지도 확인 바랍니다.

2024-03-29 00:40 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        opIdx += 1;
> cancel인 경우는 ?
1번 op가 cancel되면, 2번 op가 처리되기 전에 1번 op의 complete()이 먼저 수행되는가?

맞습니다.
cancel이 되면 항상 complete()가 수행되기 때문에 2번 op가 아직 처리되지 않은 상황에서 1번 op가 cancel 되면 우려한 상황이 됩니다.
이 부분을 고려하면 https://github.com/naver/arcus-java-client/pull/727#discussion_r1522776727 제가 제안한 방법이 나을 것 같습니다.

2024-03-29 03:13 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        opIdx += 1;
@jhpark816 

> op-2 수행에서 piped_error 또는 cancel 된다면 op-3는 아예 수행하지 않아야 함.

현재 동작은 op-2의 결과에 상관없이 op-3는 수행됩니다.

다만, 사용자가 get()을 호출하면 op-2에 의해서 ExecutionException이 발생하고
getStatus()를 호출하면 not success에 해당하는 응답이 반환됩니다.

말씀하신대로라면 앞선 op의 상태를 알아야 뒤쪽 op의 실행여부를 결정합니다.
아래 코멘트에 해당 방법에 대한 내용이 잘 서술되어있습니다.
https://github.com/naver/arcus-java-client/pull/628#discussion_r1543900954

그리고 위와 같은 내용은 본 PR과 별개로 구현되어야하지 않나요?

2024-03-29 09:46 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        opIdx += 1;
@uhm0311 
> cancel이 되면 항상 complete()가 수행되기 때문에 2번 op가 아직 처리되지 않은 상황에서 1번 op가 cancel 되면 우려한 상황이 됩니다.

위 말의 의미를 정확히 알지 못하겠습니다.
내가 질문했던 사항은 cancel 등을 포함한 다양한 오류 상황에서도 아래 조건을 만족시키는 가요?
- `op-1.complete()` 호출된 다음에 op-2 처리 시작
- `op-2.complete()` 호출된 다음에 op-3 처리 시작

2024-04-01 00:58 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        opIdx += 1;
> 내가 질문했던 사항은 cancel 등을 포함한 다양한 오류 상황에서도 아래 조건을 만족시키는 가요?

만족하지 않을 수 있다는 의미였습니다.

2024-04-01 01:52 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        opIdx += 1;
@brido4125 @uhm0311 
- 하나의 node로 pipe 연산을 이어서 보내고 그 순서대로 처리된다고 가정하여
   처리 로직에서 opIdx를 계산하는 것을 제안하였는 데, 이 방식이 안전한 방식은 아닌 것 같습니다.
- 위의 BTreePipedInsert 객체 or opFact.collectionPipedInsert()로 생성하는 Operation 객체 중
   opIdx를 넣기에 적합한 객체를 판단하여 알려주시고, 그에 따른 수행 방식으로 변경하기 바랍니다.

2024-04-01 06:10 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        opIdx += 1;
코멘트를 보면 `pipe<Insert or update>` 객체를 만들 때 
opIdx를 넣는 것으로 의견이 모아진것 같습니다.

opFact는 앞서 나와있듯이 사소하지만 하위호환성이 깨지게 됩니다.

2024-04-01 06:55 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        opIdx += 1;
그러면, BTreePipedInsert 객체에 opIdx 넣으시죠.

2024-04-02 03:27 UTC, uhm0311 requested changes

2024-04-02 03:27 UTC, uhm0311 commented on src/main/java/net/spy/memcached/collection/CollectionPipedInsert.java
> +  protected CollectionPipedInsert(String key, int idx, CollectionAttributes attribute,
idx => opIdx

여기 외에도 원래 opIdx를 의미하는 곳의 매개변수들은 opIdx로 바꿔주세요.

2024-04-02 04:50 UTC, brido4125 commented on src/main/java/net/spy/memcached/collection/CollectionPipedInsert.java
> +  protected CollectionPipedInsert(String key, int idx, CollectionAttributes attribute,
반영하였습니다.

2024-04-03 02:42 UTC, uhm0311 approved these changes

2024-04-03 06:16 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
>        addOp(key, op);
@brido4125 이 부분에 대응되는 PR 은 반영된 상태인가요?

2024-04-03 06:19 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
>        addOp(key, op);
@oliviarla 
이슈만 올려놓은 상태입니다. 본 PR 머지되면 push할 예정입니다.
https://github.com/jam2in/arcus-works/issues/528

2024-04-05 02:21 UTC, oliviarla commented
@brido4125 현재 커밋이 3개입니다. rebase해주셔야 할 것 같습니다.

2024-04-09 03:17 UTC, oliviarla approved these changes

2024-04-09 05:21 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      Operation op = opFact.collectionPipedUpdate(key, pipedUpdate, callback);
@uhm0311 @oliviarla 
아래와 같이 collectionPipedUpdate() 호출 시에 opIdx 값을 넣어줄 수 있습니다.
이 방법의 문제는 무엇인가요?

```java
    for (int i = 0; i < updateList.size(); i++) {
      Operation op = opFact.collectionPipedUpdate(key, i, updateList.get(i), callback);
      rv.addOperation(op);
      addOp(key, op);
    }
```

2024-04-09 05:27 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      Operation op = opFact.collectionPipedUpdate(key, pipedUpdate, callback);
https://github.com/naver/arcus-java-client/pull/727#discussion_r1522776727

2024-04-09 05:59 UTC, jhpark816 reviewed
리뷰 완료

2024-04-09 05:59 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      insertList.add(new ByteArraysBTreePipedInsert<T>(key, list.get(i), i, attributesForCreate, tc));
일반적으로 element 개수가 MAX_PIPED_ITEM_COUNT 보다 적을 경우가 많을 것 같습니다.
이 경우, Partition 작업에 따른 수행 cost를 지불하지 않는 기존 구현이 나을 것 같습니다.

2024-04-09 05:59 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      public void gotStatus(Integer index, int opIdx, OperationStatus status) {
gotStatus() 인터페이스는 아래 형태가 좋을 것 같습니다.
따라서, 호출하는 쪽에서 
`(opIdx * CollectionPipedUpdate.MAX_PIPED_ITEM_COUNT)` 포함한 index 값을 넘겨주면 됩니다.

```
public void gotStatus(Integer index, OperationStatus status)
```

2024-04-09 08:31 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      Operation op = opFact.collectionPipedUpdate(key, pipedUpdate, callback);
BTreePipedUpdate 객체는 command 정보를 담고 있는 객체에 해당하며,
이러한 객체에 opIdx 두고자 하니 어색한 느낌이 있다는 것입니다.

opFact.collectionPipedUpdate()로 생성한 객체가 실제 Operation 객체입니다.
전체 piped 연산 중 몇 번째 sub 연산을 나타내는 opIdx를 추가하여도 자연스러운 형태가 됩니다.

2024-04-09 11:25 UTC, jhpark816 commented
pipe 연산의 처리, 활용 방식을 정리할 때까지 본 PR 처리는 연기해야 할 것 같습니다.

2024-09-06 09:20 UTC, jhpark816 reviewed
리뷰 완료

최신 코드 기준으로 rebase 해 주세요.

2024-09-06 09:20 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      public void gotStatus(Integer index, int opIdx, OperationStatus status) {
인자 타입이 Integer, int가 혼용 사용되고 있는 데, int 타입으로 통일하면 될 것 같습니다.

참고로, 아래와 같이 구현할 수 있습니다.

```java
      public void gotStatus(int opIdx, int elemIdx, OperationStatus status) {
        int index = (opIdx * CollectionPipedUpdate.MAX_PIPED_ITEM_COUNT) + elemIdx;
        if (status instanceof CollectionOperationStatus) {
          rv.addEachResult(index, (CollectionOperationStatus) status);
        } else {
          rv.addEachResult(index, new CollectionOperationStatus(status));
        }
      }
```

2024-09-06 09:20 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    PartitionedMap<Long, T> list = new PartitionedMap<Long, T>(elements,
PartitionedMap 구현은 주어진 map 크기가 주어진 size 보다 작거나 같을 경우, 해당 map을 그대로 리턴하도록 최적화합시다.

2024-09-06 09:20 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      insertList.add(new BTreePipedInsert<T>(key, list.get(i), i, attributesForCreate, tc));
인자 순서 검토 바람: `list.get(i), i` => `i, list.get(i)`

2024-09-06 09:20 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      public void gotStatus(Integer index, int opIdx, OperationStatus status) {
아니면, gotStatus()은 index 인자를 받고, 
해당되는 index 값은 gotStatus() 호출하는 쪽에서 계산하여 넘기는 것이 나을 것 같습니다.

```java
      public void gotStatus(int index, OperationStatus status) {
        if (status instanceof CollectionOperationStatus) {
          rv.addEachResult(index, (CollectionOperationStatus) status);
        } else {
          rv.addEachResult(index, new CollectionOperationStatus(status));
        }
      }
```

2024-09-09 02:36 UTC, brido4125 commented
> pipe 연산의 처리, 활용 방식을 정리할 때까지 본 PR 처리는 연기해야 할 것 같습니다.

@jhpark816

PR 목록을 살펴보니 아직 pipe 관련된 변경사항이 merge 되진 않은 것 같습니다.
@oliviarla 님이 진행중인 작업이 마무리된 다음에 수정사항 반영해서 작업 하는게 좋을 것 같네요

2026-02-19 07:46 UTC, closed without merging