TEST: Remove duplicated test case regardless ZK is running or not.
naver/arcus-java-client pull request #728
Opened 2024-03-12 08:00 UTC by brido4125

아래 테스트는 ZK와 함께 구동될 경우 Skip 되는 테스트 클래스입니다.
(assumeTrue 사용)

- ObserverTest

ZK 없이 테스트하는 경우 Single cached node에 테스트 코드를 수행하는 경우라서
클러스터 환경에서 나머지 테스트 케이스들을 커버합니다.

위 테스트를 제외한 나머지 테스트 케이스들의 중복 수행을 수정하는 PR입니다.
(6min -> 3min 으로 CI 시간 단축)

아래는 기존에 실행되던 테스트 방식에서 skip 되는 테스트 케이스들에 대한 정리입니다.
https://www.notion.so/jam2in/skip-test-case-94ac9e83e6024ec68e722b3ac67a287f?pvs=4

2024-03-12 10:46 UTC, uhm0311 requested changes

2024-03-12 10:46 UTC, uhm0311 commented on .github/workflows/ci.yml
> +      - name: Test ARCUS Client Without Zk
`Zk` -> `ZK`로 합시다.

2024-03-13 02:52 UTC, uhm0311 commented on .github/workflows/ci.yml
> +        run: mvn test -Dtest=ObserverTest,ArcusClientFrontCacheTest,ArcusClientConnectTest
assumeTrue(true)이면 테스트를 진행하고 assumeTrue(false)이면 테스트를 진행하지 않는 거죠?
ObserverTest에서는 `assumeTrue(!USE_ZK)`를 호출하는데, ZK 연결이 아닌 경우에 테스트를 수행하는 것인가요?
다른 두 테스트에서는 `assumeTrue(BaseIntegrationTest.USE_ZK)`를 호출하는데, ZK 연결을 하는 경우에 테스트를 수행하는 건가요?

2024-03-13 03:06 UTC, brido4125 commented on .github/workflows/ci.yml
> +        run: mvn test -Dtest=ObserverTest,ArcusClientFrontCacheTest,ArcusClientConnectTest
제가 불리언 값을 잘못 봤네요.
ObserverTest만 zk 환경이 아닌 경우 실행되면 됩니다.
나머지 두 경우는 USE_ZK가 true인 경우 테스트가 수행됩니다.
수정하겠습니다.

2024-03-13 08:53 UTC, uhm0311 approved these changes

2024-03-13 10:24 UTC, brido4125 commented
@oliviarla 

> PR 본문 내용이 무슨 의미인지 잘 이해가 가지 않는데 수정해주실 수 있을까요?

수정했습니다. 이해하신게 맞습니다.

2024-03-13 10:40 UTC, oliviarla approved these changes

2024-03-14 02:51 UTC, jhpark816 reviewed
리뷰 완료

2024-03-14 02:51 UTC, jhpark816 commented on .github/workflows/ci.yml
> +        run: mvn test -Dtest=ObserverTest
USE_ZK=false 설정과 ARCUS_HOST 설정을 주지 않아도 되나요?
`-Dtest=ObserverTest`로 명시된 test만 수행하는 것인가요?

2024-03-14 02:51 UTC, jhpark816 commented on .github/workflows/ci.yml
> +        run: mvn test -Dtest=ObserverTest
다른 테스트는 with ZK에서 한번만 테스트하면 된다는 것을 확인하고 싶은 데,
어떻게 확인하면 되나요 ?

참고로, PR 코멘트에 있는 URL은 접근이 불가합니다.

2024-03-14 03:07 UTC, brido4125 commented
PR 반영 시, With ZK 옵션으로 테스트 진행됩니다.
`@Ignore`는 공통적으로 skip 하고
그 외를 아래 테스트를 제외하고는 중복으로 수행됩니다.
- ObserverTest
- ArcusClientConnectTest
- ArcusClientFrontCacheTest

(ArcusClientConnectTest,ArcusClientFrontCacheTest는 with ZK에서만 수행합니다. )
## With ZK(10)

구동옵션 : `mvn test -DUSE_ZK=true`

### `@Ignore`

- ArcusClientPoolShutdownTest : 1
- ArcusClientPoolReconnectTest : 1
- LocalCacheManagerTest: 1
- ArcusClientNotExistsServiceCodeTest : 1
- ArcusClientReconnectTest: 1
- ArcusClientShutdownTest: 1
- ConsistentHashingTest: 1
- QueueOverflowTest: 1
- BaseIntegrationTest: 1

### USE_ZK=true

- ObserverTest: 1

## Without ZK(14)

구동옵션 : `mvn test`

### `@Ignore`

- ArcusClientPoolShutdownTest : 1
- ArcusClientPoolReconnectTest : 1
- LocalCacheManagerTest: 1
- ArcusClientNotExistsServiceCodeTest : 1
- ArcusClientReconnectTest: 1
- ArcusClientShutdownTest: 1
- ConsistentHashingTest: 1
- QueueOverflowTest: 1
- BaseIntegrationTest: 1

### USE_ZK=true

- ArcusClientFrontCacheTest: 3
- ArcusClientConnectTest: 1

2024-03-14 03:07 UTC, brido4125 commented on .github/workflows/ci.yml
> +        run: mvn test -Dtest=ObserverTest
> USE_ZK=false 설정과 ARCUS_HOST 설정을 주지 않아도 되나요?

기존에 설정하던 값들이 default 값이라 생략 가능합니다.

> -Dtest=ObserverTest로 명시된 test만 수행하는 것인가요?

넵

2024-03-14 10:46 UTC, jhpark816 reviewed
리뷰 완료

2024-03-14 10:46 UTC, jhpark816 commented on .github/workflows/ci.yml
> +        run: mvn test -Dtest=ObserverTest
`-DUSE_ZK=false` 옵션은 without ZK임을 명시적으로 나타내기 위해 추가해 둡시다.

```
mvn test -DUSE_ZK=false -Dtest=ObserverTest
```

2024-03-15 01:22 UTC, merged