FEAT: Add check DNS cache ttl method.
naver/arcus-java-client pull request #731
Opened 2024-03-15 07:08 UTC by brido4125

### 관련 이슈
https://github.com/jam2in/arcus-works/issues/487

### CI 이슈
현재 `InetAddressCachePolicy` 이슈로 인해 CI가 동작하지 않습니다.
해당 이슈 해결하는데 시간이 소요될것 같아 먼저 PR 올립니다.
추가된 메서드의 로직에 대해서만 리뷰 부탁드립니다.

2024-03-15 07:25 UTC, uhm0311 requested changes

2024-03-15 07:25 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      return InetAddressCachePolicy.get() >= 0;
이 클래스를 임포트 하는 것은 불가능합니다. Reflection 기능으로 호출해야 합니다.
그리고 값이 0 이상이기만 하면 되는 것이 아닙니다. 
이 PR에 대해 논의한 이슈를 더 자세히 살펴보고 코드를 수정해주세요.

2024-03-15 07:25 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  public static boolean isValidDnsTtlSetting() {
`...DnsCacheTtl()`로 합시다.

2024-03-15 07:25 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      throw new RuntimeException("DNS ttl setting is wrong.");
DNS Cache TTL 값이 구체적으로 어느 범위 내에 있어야 하는지도 출력을 하도록 합시다.
그리고 이러한 체크 기능을 끄고 싶다면 어떻게 해야 하는지도 알려주도록 합시다.

2024-03-15 07:25 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
> +  private boolean dnsTtlCheck = true;
`dnsTtlCheck` -> `dnsCacheTtlCheck`

2024-03-18 02:03 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      return InetAddressCachePolicy.get() >= 0;
@uhm0311 

> 그리고 값이 0 이상이기만 하면 되는 것이 아닙니다.

해당 값의 `maxTtl`(300)을 설정하는 로직을 말씀하신게 맞나요?

2024-03-18 07:43 UTC, uhm0311 requested changes

2024-03-18 07:43 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  private static final String SYSTEM_TTL = System.getProperty(DNS_CACHE_TTL_PROP); // Get DNS cache TTL from System property.
이 부분을 static final로 선언해서 두면 isValidDnsCacheTtlSetting() 메소드가 호출될 시점에는 `...getProperty(DNS_CACHE_TTL_PROP)`에 다른 값이 들어있을 수 있습니다.

2024-03-18 07:43 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      getLogger().warn("The minimum value for DNS cache TTL is 0 and the maximum value is 300sec.");
`sec`는 지웁시다.
필요하다면 단위가 seconds임을 알리면 됩니다.

2024-03-18 07:43 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      getLogger().warn("Invoke ConnectionFactoryBuilder.setDnsCacheTtlCheck(false) to avoid this validation.");
2개의 로그로 표현하지 말고 하나의 로그 내에서 모두 표현합시다.

2024-03-18 07:43 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      throw new RuntimeException("The value of the DNS cache TTL is less than 0.");
`... less than 0 or greater than ...`

2024-03-18 07:43 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    }
값을 우리가 원하는 값으로 바꾸는 것은 논의가 되지 않은 부분인 것 같습니다.
만약 논의가 된 사항이라면 설정할 수 없이 무조건 값을 바꿔도 되나요?
그리고 이 메소드가 호출된 뒤에 사용자가 다시 값을 설정하는 경우는 어떻게 처리하나요?

2024-03-18 07:43 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    }
Reflection 기능은 JDK 버전이 바뀌면서 계속 막혀가는 추세입니다.
기능을 넣긴 했지만 추후에 수행되지 않을 수 있습니다.
그러므로 Exception 종류를 세세히 나누지 말고 그냥 Throwable을 catch 한 다음 error 로그를 찍도록 합시다.

2024-03-18 07:43 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    }
최대값을 넘지 않는지도 확인해야 합니다.

2024-03-18 07:54 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    }
별도의 변경 없이 논의된 부분만 구현하도록 하겠습니다.

2024-03-19 02:21 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    }
리뷰 반영하였습니다.

2024-03-20 08:52 UTC, uhm0311 requested changes

2024-03-20 08:52 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      ttl = (Integer) Class.forName("sun.net.InetAddressCachePolicy")
`sun.net.InetAddressCachePolicy`도 바뀌지 않는 상수이니 static final로 선언해서 씁시다.

2024-03-20 08:52 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  private static boolean isValidDnsCacheTtlSetting() {
`Setting`은 지우도록 합시다.

2024-03-20 08:52 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    }
`...getProperty()` 값이 문자열인 특성상 정수로 변환이 불가능할 수도 있습니다.
NumberFormatException을 핸들링 하도록 합시다.

2024-03-20 08:52 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      throw new RuntimeException("The value of the DNS cache TTL is less than 0 or greater than 300.");
300이라는 최대값도 static final로 선언되어 있으니 로그 메세지 출력에도 선언된 변수를 사용합시다.

2024-03-21 00:12 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    } catch (NumberFormatException e) {
이 exception이 어느 클래스의 어떤 메소드를 수행할 때 발생하는지 확인해주세요.

2024-03-21 01:06 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    } catch (NumberFormatException e) {
try-catch가 아닌 정규표현식으로 해당 String 값이 
numeric인지 검사하는 로직으로 변경하였습니다.

try-catch보다 로직이 간결하다고 생각됩니다.

2024-03-21 01:20 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        arcusLogger.warn("DNS cache TTl was non-numeric type in security property.");
숫자가 아니면 ttl 적용이 안되므로 invalid로 판정하지 않고 다음 로직으로 넘어가면 됩니다.

2024-03-21 01:38 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return !target.matches("[+-]?\\d*(\\.\\d+)?");
정수만 적용되므로 소수점은 무시해도 됩니다.
더 구체적으로는 Integer.parseInt(str) 혹은 Integer.decode(str) 가능한 문자열만 허용하면 됩니다.
정규식으로 이 두 조건을 다 확인하기보단 두 메소드를 호출해보는 것이 더 간편할 것입니다.

2024-03-21 05:09 UTC, uhm0311 requested changes

2024-03-21 05:09 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +              "Invoke ConnectionFactoryBuilder.setDnsCacheTtlCheck(false) to avoid this validation.");
`". Invoke ...`

2024-03-21 05:09 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      throw new RuntimeException("The value of the DNS cache TTL is less than 0 or greater than" + MAX_DNS_CACHE_TTL);
`than " + MAX_DNS_CACHE_TTL`

2024-03-21 05:09 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
`Integer.parseInt(target)`
`Integer.decode(target)`

둘 중 하나만 성공해도 TTL이 설정되므로 현재 구현이 맞지 않습니다.

2024-03-21 05:30 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
> 둘 중 하나만 성공해도 TTL이 설정되므로 현재 구현이 맞지 않습니다.

아래 문장 뜻이 `non-numeric`인 경우, invalid로 판정하지 않고 `true`로 처리하라는 의미 아닌가요?

>숫자가 아니면 ttl 적용이 안되므로 invalid로 판정하지 않고 다음 로직으로 넘어가면 됩니다.

저도 처음 생각했을 때는 `non-numeric` 또한 Invalid한 값이니,  `non-numeric`인 경우 False 리턴하여 TTL이 설정되지 않도록 구현했습니다. 말씀한 사항의 의미가 제가 처음 생각한 것과 동일한건가요?

또한 확인해보니, Integer.decode()가 16진수를 포함한 더 포괄적인 String을 Int로 변환해줍니다.  `Integer.decode()`만 호출해도 되지 않나요?

2024-03-21 05:35 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
Integer.decode()가 Integer.parseInt()를 100% 대체할 수는 없으니 둘 다 호출하는 것이 좋습니다.

현재 구현으로는 Integer.decode()는 성공하는 문자열이더라도 Integer.parseInt()에서 실패하면 올바르지 않은 값으로 인지합니다.
Integer.decode()의 결과가 10과 같이 Valid한 값이어도 그렇습니다.
그래서 현재 구현이 맞지 않다고 하는 것입니다.

2024-03-21 05:37 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
차라리 parseTtl()과 같은 메소드를 둬서 Integer.parseInt()가 성공하면 그 값을 반환하고 Integer.decode()가 성공하면 그 값을 반환하고 다 실패하면 null을 반환하는 것이 더 나을 것 같습니다.

2024-03-21 06:43 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
> 그 값을 반환하고 다 실패하면 null을 반환하는 것이 더 나을 것 같습니다.

parseTtl()의 결과가 Null인 경우 invalid로 false 처리하여 dns cache ttl을 설정하지 못하게 처리할까요?

2024-03-21 08:04 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
System과 Security 둘 다 null이면 System.getSecurityManager() == null 반환하면 됩니다.

2024-03-21 08:35 UTC, uhm0311 requested changes

2024-03-21 08:35 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      ttl = Integer.decode(target);
`return Integer.decode(target);`를 했을 때 숫자가 아니면 반환하지 않고 catch로 들어갑니다.

2024-03-21 08:35 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      ttl = Integer.valueOf(target);
마찬가지로 `return Integer.parseInt(target);`를 하면 됩니다.
Integer.valueOf()는 Integer.parseInt()로 대체되었으므로 parseInt()를 씁시다.

2024-03-21 08:35 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return ttl;
여기서 `return null;` 하면 됩니다.

2024-03-21 08:35 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      if (ttl < 0 || ttl > MAX_DNS_CACHE_TTL) {
두 if문을 합쳐서 뎁스를 줄입시다.

2024-03-21 08:35 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        if (securityTtl < 0 || securityTtl > MAX_DNS_CACHE_TTL) {
여기도 두 if문을 합칩시다.

2024-03-21 08:35 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        if (systemTtl < 0 || systemTtl > MAX_DNS_CACHE_TTL) {
여기도 합칠 수 있습니다.

2024-03-21 08:35 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    Integer ttl = null;
여기 변수는 필요 없습니다.

2024-03-22 02:00 UTC, uhm0311 submitted a review, later dismissed

2024-03-28 12:03 UTC, jhpark816 commented
@brido4125 
DNS cache TTL 설정을 어떻게 확인하고 어떤 설정이면 invalid한 것인지 
구현 설명을 PR 코멘트에 추가 바랍니다.

2024-03-28 12:06 UTC, jhpark816 reviewed
리뷰 완료

2024-03-28 12:06 UTC, jhpark816 commented on pom.xml
> +                    <argLine>--illegal-access=permit</argLine>
무엇 때문에 필요한가요?

2024-03-28 12:06 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    }
위의 코드는 어떤 값을 확인하는 것이고 이를 확인해야 하는 이유는 무엇인가요?

참고로, 예전에 아래 값들만 확인하면 된다고 들었습니다.
```java
    String security = Security.getProperty(DNS_CACHE_TTL_PROP);
    String system = System.getProperty(DNS_CACHE_TTL_PROP);
```

2024-03-29 00:08 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    }
https://github.com/jam2in/arcus-works/issues/487#issuecomment-1958974755
위 이슈의 코멘트를 확인 부탁드립니다.

2024-03-29 12:21 UTC, jhpark816 reviewed
리뷰 완료

2024-03-29 12:21 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      }
아래와 같이 valid ttl 이면 바로 true 리턴하면 되지 않나요?

```java
      if (securityTtl != null) {
        if (securityTtl < 0 || securityTtl > MAX_DNS_CACHE_TTL))
          return false;
        else
          return true;
      }
```

2024-03-29 12:21 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      getLogger().warn("The minimum value for DNS cache TTL is 0 and the maximum value is " + MAX_DNS_CACHE_TTL +
문구 수정
DNS cache TTL must be between 0 and MAX_DNS_CACHE_TTL.

2024-03-29 12:21 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +              ". Invoke ConnectionFactoryBuilder.setDnsCacheTtlCheck(false) to avoid this validation.");
this validation => this constraint

2024-04-01 02:18 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    }
@uhm0311 

`sun.net.InetAddressCachePolicy`에 접근하더라도,
내부적으로는 결국 `Security.getProperty()`와 `System.getProperty()`, `System.getSecurityManager()`를 통해
dns ttl을 설정하는 것을 확인하였습니다.

아래 링크의 static 블럭을 확인하시면 됩니다.
https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/sun/net/InetAddressCachePolicy.java

동일한 동작을 수행하여 제외해도 괜찮을 것 같습니다.
의견 있다면 말씀해주세요.

2024-04-01 02:25 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    }
@brido4125 @jhpark816 

https://github.com/jam2in/arcus-works/issues/487#issuecomment-1886032871

`Security.getProperty()와 System.getProperty(), System.getSecurityManager()를 통해
dns ttl을 설정` 하지 않고도 설정 가능한 다른 방법이 있어서 그대로 두는 것이 나을 것 같습니다.

2024-04-01 04:54 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      }
반영하였습니다.

2024-04-03 12:10 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    String system = System.getProperty(DNS_CACHE_TTL_PROP);
위의 2개 수행은 어떻게 다른가요?

2024-04-03 12:12 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    String system = System.getProperty(DNS_CACHE_TTL_PROP);
아래 문서의 예시를 보면, 
`System.getProperty(DNS_CACHE_TTL_PROP);` 수행에서 exception 발생할 수 있어 대처 로직이 필요합니다.
https://m.blog.naver.com/adamdoha/222477256466

2024-04-03 12:17 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return System.getSecurityManager() == null;
위와 같은 순서로 확인하는 것이 맞는 지가 의문입니다.
어떤 설정이 우선 적용된다는 공식 문서의 설명이 있나요?

2024-04-04 02:10 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return System.getSecurityManager() == null;
두 설정 중 하나의 설정값이 우선 적용 되는것이 아니라, 각각 별도의 적용값입니다.
아래와 같이 적용할 경우,
Security 값으로 System 값이 덮어 씌워지는게 아니라 각각 따로 설정됩니다.
그 반대의 경우도 마찬가지입니다.

```java
    System.setProperty("networkaddress.cache.ttl", "10");
    Security.setProperty("networkaddress.cache.ttl", "50");
```

그래서 로직의 순서에 상관없이 각각 검증을 수행해줘야합니다.

2024-04-04 02:13 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    String system = System.getProperty(DNS_CACHE_TTL_PROP);
> 위의 2개 수행은 어떻게 다른가요?

서로 다른 영역 (System / Security)에서 동일한 프로퍼티 값을 각각 가져오는 것입니다.

2024-04-04 02:16 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return System.getSecurityManager() == null;
예를 들어, 아래와 같이 설정되었다면, 최종적으로 어떤 TTL로 캐싱하는가요?
결국 우선순위에 의해 결정될 수 밖에 없습니다.
```java
    System.setProperty("networkaddress.cache.ttl", "10");
    Security.setProperty("networkaddress.cache.ttl", "50");
```

2024-04-04 02:50 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return System.getSecurityManager() == null;
> 예를 들어, 아래와 같이 설정되었다면, 최종적으로 어떤 TTL로 캐싱하는가요?

직접 java 프로세스를 띄우고 나서, `jinfo -sysprops <pid>`로 확인을 해보면
System으로 설정된 값이 나오긴 합니다.
(jvm 11, 17 모두 동일한 결과)

하지만 https://github.com/jam2in/arcus-works/issues/487#issue-2073823910 의
Heap-dump를 통해 얻은 결과와 마찬가지로 
실제 dns cache를 조회할 때 10초인지는 보장할 수 없습니다.

결국 Security를 통한 설정값을 구동된 Process에서 얻어내는 법을 찾아야 하는데
구글링을 해도 별도의 방법이 없다고 나옵니다.

즉, system이 security보다 우선순위가 높아서인지
security의 값을 가져오는 방법이 없어서 인지 알 수 없습니다.

제가 의문인것은 만약 사용자가 System -> Valid, Security -> Invalid한 값으로 설정한 경우
라이브러리 입장에서는 최종적으로 사용되는 값을 알아내서 그 값을 검증하는것이 아니라
구동된 후에 사용되지 않더라도 사용자가 Invalid하게 설정한 값이 있으면
그 값을 검증하여 알려줘야하는게 맞지 않을까요?

2024-04-04 04:42 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return System.getSecurityManager() == null;
@brido4125 @uhm0311 
최종적으로 사용될 TTL 값을 검증해야 합니다.
왜 그래야 하는 지는 스스로 생각해 보고, 이상하다 싶으면 다시 문의 주세요.

2024-04-04 05:24 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return System.getSecurityManager() == null;
@jhpark816 

> 예를 들어, 아래와 같이 설정되었다면, 최종적으로 어떤 TTL로 캐싱하는가요?
결국 우선순위에 의해 결정될 수 밖에 없습니다.

- JDK 소스 코드 : Security가 우선
- @brido4125 실험 결과 : System이 우선

둘 다 체크하는 것에 어떠한 문제가 있는 것이 아니기 때문에, 더 안전하게 하려면 둘 다 확인하는 것이 좋습니다.

2024-04-04 06:25 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return System.getSecurityManager() == null;
@uhm0311 @brido4125 
> jinfo -sysprops <pid>로 확인한 결과 : System이 우선

`jinfo -sysprops <pid>`는 system properties 조회하는 명령이 아닌가요?
단순히 system property 조회하는 명령인 것이고,
DNS Cache TTL로 어떤 값이 적용되어 있는 지를 나타내는 명령은 아닌 것으로 보입니다.

> 둘 다 체크하는 것에 어떠한 문제가 있는 것이 아니기 때문에, 더 안전하게 하려면 둘 다 확인하는 것이 좋습니다.

Valid한 TTL인지는 검사하는 데 그 순서가 필요하다는 것입니다.
Security > System 의 우선순위를 가진다면,
- Security property 설정되었는 지를 먼저 확인하여 검증하면 됩니다.
  Security property 설정이 있다면, System property는 조회하지 않아도 됩니다.
- Security property 설정이 없다면, System propery 조회하여 검증합니다.

즉, System property 설정을 먼저 조회하여 검증하면 안된다는 얘기입니다.

2024-04-04 09:24 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return System.getSecurityManager() == null;
사실 현재 코드는 제가 원하는 형태가 아닙니다.
제가 원하는 형태는 Security도 Valid하고 System도 Valid한 값이어야 하는 로직입니다.
더 정확히는 SUN_NET_POLICY_PROP 값, Security 값, System 값이 모두 Valid 하고 SecurityManager == null 이어야 하는 로직이 제가 원하는 로직입니다.

https://github.com/naver/arcus-java-client/pull/731#discussion_r1544445427
그리고 해당 부분은 @jhpark816 님 리뷰로 인해 변경되었습니다.

> 즉, System property 설정을 먼저 조회하여 검증하면 안된다는 얘기입니다.

먼저 조회하여 검증하는 것이 아니라, 우선순위에 관계 없이 전부 다 검증해야 한다는 의미입니다.

2024-05-27 05:20 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return System.getSecurityManager() == null;
> 최종적으로 사용될 TTL 값을 검증해야 합니다.

이 말에 대한 결론이 어떻게 났나요? 저도 최종적으로 사용되고 있는 TTL 값만을 사용해 검증하면 될 것 같다는 생각이 듭니다.

2024-05-31 02:58 UTC, uhm0311 requested changes

2024-05-31 02:58 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    }
try문 안으로 넣고, 중첩 없이 `&&`로 묶어주세요.

2024-05-31 02:58 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      arcusLogger.error(errorMsg, e);
Stacktrace는 출력하지 않거나, debug 로그로 출력하도록 합시다.
만약 debug 로그로 출력한다면 DNS 캐시 관련 에러 로그 전부에 반영해주세요.

2024-05-31 07:02 UTC, uhm0311 requested changes

2024-05-31 07:02 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +            "Can not access to dns cache ttl property in system manager.");
`Can not access to dns cache ttl property in system manager.` => `Can not access to dns cache ttl in system properties.`

2024-05-31 07:02 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  private static boolean isValidTtl(Integer ttl) {
매개변수 타입을 int로 바꿉시다.

2024-05-31 09:24 UTC, uhm0311 submitted a review, later dismissed

2024-06-04 23:25 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        result = Integer.decode(target);
setProperty 메서드의 인자가 문자열 리터럴이기 때문에
사용자가 어떤 값을 할당시킬지 몰라서 decode()도 수행하도록 하였습니다.

```java
    Security.setProperty(DNS_CACHE_TTL_SECURITY_PROP, "0xab");
    System.setProperty(DNS_CACHE_TTL_SECURITY_PROP, "0xab");
```

2024-06-05 01:45 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        result = Integer.decode(target);
10진수가 아닌 수를 프로퍼티로 할당해도 정상적으로 TTL이 적용되나요?

2024-06-05 02:51 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        result = Integer.decode(target);
구현을 어떻게 가져가냐에 따라 달라질 것 같습니다.
저는 10진수 리터럴인 경우만 지원해줘도 된다고 생각합니다.
@uhm0311 @oliviarla 의견은 어떠신가요?

2024-06-05 02:53 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        result = Integer.decode(target);
https://github.com/openjdk/jdk/blob/jdk-21%2B35/src/java.base/share/classes/sun/net/InetAddressCachePolicy.java#L132-L160

내부적으로 Integer.decode()를 사용하기 때문에 10진수가 아닌 값도 검증해야 합니다.

2024-06-05 03:01 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        result = Integer.decode(target);
위 코드를 보니 Security.setProperty로는 10진수가 아닌 값을 주면 동작하지 않네요. parsing 로직을 Security와 System 프로퍼티마다 다르게 수행하는게 나아보입니다.

예를 들면 validateDnsCacheTtl 메서드 내부에서 validateSecurityProperty, validateSystemProperty메서드를 순차적으로 호출하는 방식으로 분리하면 좋을 것 같습니다.

2024-06-05 06:36 UTC, oliviarla submitted a review, later dismissed

2024-06-05 08:09 UTC, uhm0311 approved these changes

2024-06-05 12:16 UTC, jhpark816 reviewed
리뷰 완료

2024-06-05 12:44 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return System.getSecurityManager() == null;
이 코드의 의미를 주석으로 추가합시다.

2024-06-10 00:16 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
참고로 위 코드에서는 AccessControlException를 예외처리 해주지 않습니다.
그래서 겉보기에는 더 간결해 보일 수도 있습니다.
저희 코드를 람다를 사용 안하도록 변경하면 아래와 같습니다.

## 람다식 사용 X
```java
    String securityDnsTtl = null;
    try {
      securityDnsTtl = Security.getProperty(DNS_CACHE_TTL_SECURITY_PROP);
    } catch (SecurityException e) {
      // Using super class SecurityException to catch the deprecated AccessControlException.
      arcusLogger.error("Can not access to dns cache ttl in security properties.");
    }
    if (securityDnsTtl != null) {
      Integer ttl = null;
      try {
        ttl = Integer.valueOf(securityDnsTtl);
      }  catch (NumberFormatException e) {
        arcusLogger.warn("Invalid numeric type was set in property.");
      }
      if (ttl != null) {
        return isValidTtl(ttl);
      }
    }

    String systemDnsTtl = null;
    try {
      systemDnsTtl = System.getProperty(DNS_CACHE_TTL_SYSTEM_PROP);
    } catch (SecurityException e) {
      // Using super class SecurityException to catch the deprecated AccessControlException.
      arcusLogger.error("Can not access to dns cache ttl in sysetm properties.");
    }
    if (systemDnsTtl != null) {
      Integer ttl = null;
      try {
        ttl = Integer.valueOf(systemDnsTtl);
      }  catch (NumberFormatException e) {
        arcusLogger.warn("Invalid numeric type was set in property.");
      }
      if (ttl != null) {
        return isValidTtl(ttl);
      }
    }
return System.getSecurityManager() == null;
```

## 람다식 사용
```java
    String securityDnsTtl = getDnsTtl(() -> Security.getProperty(DNS_CACHE_TTL_SECURITY_PROP),
            "Can not access to dns cache ttl in security properties.");
    if (securityDnsTtl != null) {
      Integer ttl = parseDnsTtl(() -> Integer.valueOf(securityDnsTtl));
      if (ttl != null) {
        return isValidTtl(ttl);
      }
    }

    String systemDnsTtl = getDnsTtl(() -> System.getProperty(DNS_CACHE_TTL_SYSTEM_PROP),
            "Can not access to dns cache ttl in system properties.");
    if (systemDnsTtl != null) {
      Integer ttl = parseDnsTtl(() -> Integer.decode(systemDnsTtl));
      if (ttl != null) {
        return isValidTtl(ttl);
      }
    }
    return System.getSecurityManager() == null;
```

2024-06-10 00:20 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    }
현재 구조에서 ArcusClientPool을 생성 시 ArcusClient를 단독으로 사용하는 경우와 동일한 생성자를 호출하기에 추후에 아래 이슈가 해결되고 나서 변경해야할 것 같습니다.

https://github.com/jam2in/arcus-works/issues/572

2024-06-10 00:26 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
`SecurityException` 발생 시에 해당 설정 값을 무시하고, next 설정 값을 확인하면 되나요?
`SecurityException`는 어떤 경우에 발생하는 가요? 이 경우 해당 exception을 throw해야 하지 않는 지 ?

2024-06-10 00:52 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
> SecurityException는 어떤 경우에 발생하는 가요?

SecurityManager가 true이고 해당 SecurityManager의 권한 설정으로 System 또는 Security 프로퍼티에 접근하지 못할 때 발생합니다.

> SecurityException 발생 시에 해당 설정 값을 무시하고, next 설정 값을 확인하면 되나요?

SecurityException가 Security에서 발생하고 여기서 throw를 하게 되면 System에 설정된 값을 읽는 시도를 하지 않게 됩니다.

물론 System을 읽는다고 해서 읽을 수 있는지는 사용자가 설정한 권한에 따라 달라지고
Security와 마찬가지로 예외가 발생할 수 있습니다.

두 경우 모두 예외가 발생하면 SecurityManager가 null이 아니므로 false를 리턴하면 됩니다.
최종적으로 false인 경우는 IllegalStateException를 사용자에게 전파합니다.

2024-06-10 01:02 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
`SecurityException` 발생하더라도 jvm에 의한 ttl 설정은 제대로 되는 거죠?

Security 프로퍼티 접근에서 `SecurityException` 발생하더라도
jvm에 의한 ttl 설정이 제대로 동작한다면,
System 프로퍼티 기준으로 ttl 유효성 검사는 수행하지 않아야 합니다.

어떤가요?

2024-06-10 01:59 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
코드 수정 외에 코멘트에 대한 답변 의견도 전달해 주어야 
수정 의도도 정확히 이해할 수 있습니다.

2024-06-10 02:02 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
> SecurityException 발생하더라도 jvm에 의한 ttl 설정은 제대로 되는 거죠?

넵 정상적으로 설정되고 
코멘트 주신대로 접근 여부에 의해 예외 발생 시, next 프로퍼티는 검증하면 안됩니다.

2024-06-10 02:20 UTC, jhpark816 reviewed
리뷰 완료

2024-06-10 02:20 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    }
람다식을 제거하고 아래 코드 형태로 하시죠.
```java
                try {
                    String tmpString = Security.getProperty("networkaddress.cache.ttl");
                    if (tmpString != null) {
                        return isValidTTL(Integer.valueOf(tmpString));
                    }
                } catch (NumberFormatException ignored) {
                    // Ignore
                }

                try {
                    String tmpString = System.getProperty("sun.net.inetaddr.ttl");
                    if (tmpString != null) {
                        return isValidTTL(Integer.decode(tmpString));
                    }
               } catch (NumberFormatException ignored) {
                    // Ignore
                }
```

2024-06-10 02:20 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return System.getSecurityManager() == null;
위의 주석은 semantic을 설명한 것이 아니라 현재 코드를 말로 표현한 것입니다.

SecurityManager가 있으면 TTL이 어떻게 설정되고 없으면 어떻게 설정되는 지를
주석으로 알려주면 좋겠습니다.

2024-06-10 02:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
> Security 프로퍼티 접근에서 SecurityException 발생하더라도
jvm에 의한 ttl 설정이 제대로 동작한다면,
System 프로퍼티 기준으로 ttl 유효성 검사는 수행하지 않아야 합니다.

다음과 같은 경우에는 수행해야 하지 않나요?
- Security 프로퍼티 접근 불가
- Security 프로퍼티로 TTL 설정해두지 않음
- System 프로퍼티로 TTL 설정해둠

2024-06-10 02:35 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
Security 프로퍼티 접근 불가이면 Security 프로퍼티의 설정 여부를 알 수 없습니다. 다만, Security 설정이 되었는데 System인 경우를 확인할 경우는 동작의 정확성이 깨지게 됩니다. 이 경우를 위해 예외를 발생 시켜야합니다.

다른 경우로 Security 프로퍼티가 설정되지 않았고 System 프로퍼티로 설정하였을 때, 
접근 예외가 발생하는 경우는 잘못된 동작이라고 보기 어려울것 같습니다.

2024-06-10 02:38 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
SecurityManager != null인 경우에는 System 프로퍼티를 설정해두어도 TTL 적용이 안되나요?

2024-06-10 02:49 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
> SecurityManager != null인 경우에는 Security 프로퍼티는 설정하지 않고 System 프로퍼티를 설정해두어도 TTL 적용이 안되나요?

이 경우에 적용이 되고, 말하려는 의도가 뭔지 이해했습니다. 그러면 말씀하신대로 예외를 던지지 않을 경우 Security 설정이 되었는데 System인 경우를 확인하는 경우는 어떻게 처리하면 좋나요?

2024-06-10 02:57 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
4가지 경우로 나누어서 처리해야 할 것 같습니다.
- 둘 다 접근 불가능한 경우
- Security 프로퍼티만 접근 가능한 경우
- System 프로퍼티만 접근 가능한 경우
- 둘 다 접근 가능한 경우

아래와 같이 처리하면 어떨까요?
- Security 프로퍼티 접근 가능하고 값이 있으면 값 검증
- Security 프로퍼티 접근 가능하지만 값이 없으면 System 프로퍼티 접근 시도
- Security 프로퍼티 접근 불가능하면 System 프로퍼티 접근 시도
- System 프로퍼티 접근 가능하고 값이 있으면 값 검증
- System 프로퍼티 접근 가능하지만 값이 없으면 SecurityManager의 null 여부 검사로 넘어감
- System 프로퍼티 접근 불가능하면 Exception 전파

2024-06-10 03:10 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
PR 기능은 DNS cache ttl 값을 검증하는 기능입니다.
이를 검증할 수 있는 권한이 없다면 exception 전달하여야 합니다.
이를 통해, 해당 기능을 수행할 수 있도록 권한을 부여하든지 아니면
DNS cache ttl 값을 검증하지 않도록 설정하든 지 해야 합니다.

2024-06-10 03:10 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  }
전 생각이 다른게 접근이 불가능한 경우는 
기본적으로 SecurityManager를 사용하는 WAS입니다.
즉, java.policy를 통해 권한을 수정하고 얻어오는것에 대한 이해가 있는 사용자입니다.

그래서 별다른 예외 처리를 하지않고 그대로 예외를 사용자에게 전파하면
해당 부분에 대한 문제를 손쉽게 파악하고 해결할 수 있다고 생각합니다.
(InetAddressPolicy 구현도 현재와 같기에 더 제너럴한 처리라고 생각됩니다.)

또한 위 코멘트를 적용한다해도, 
Security 접근 불가이고 Security 값이 정상 설정되고 System 값도 
정상 설정인 경우는 System값으로 검증하는 문제는 해결하지 못합니다.

@jhpark816 
align 좀 부탁드립니다.

2024-06-11 09:26 UTC, oliviarla approved these changes

2024-06-11 09:36 UTC, uhm0311 approved these changes

2024-06-11 10:04 UTC, merged