FEAT: Change the way Arcusclient is named.
naver/arcus-java-client pull request #738
Opened 2024-03-29 01:52 UTC by brido4125

### 관련 이슈
https://github.com/jam2in/arcus-works/issues/344,
https://github.com/jam2in/arcus-works/issues/490

## 변경 내용
### ArcusClientPool 사용 시
ArcusClient-1(1-4)와 같은 네이밍으로 변경
ArcusClient의 첫번째 풀이고, 4개의 사이즈 중 1번째 클라이언트 인스턴스임을 의미

### ArcusClient만 사용시
- 사용자가 name을 생성자의 인자로 줄 경우
ex) MyClient3 -> MyClient는 사용자가 생성자의 인자로 넘겨주었고, 3은 ArcusClient객체만 사용될 경우 몇번 째 인스턴스인지 의미함
- default 설정된 name 사용 시
ex) ArucsClient2 -> "ArucsClient"는 디폴트 네임이고, ArcusClient객체만 사용하는 2번째 인스턴스라는 의미

2024-03-29 04:05 UTC, uhm0311 requested changes

2024-03-29 04:05 UTC, uhm0311 commented on src/main/java/net/spy/memcached/CacheManager.java
> +      int poolIndex = CacheManager.poolIndex.getAndIncrement();
이 함수는 Cache List가 업데이트 될 때마다 호출되기 때문에 이러한 사용법은 잘못된 방법입니다.
ArcusClientPool 클래스에 poolIndex 필드를 static으로 두는 것을 검토해보세요.

2024-03-29 04:42 UTC, brido4125 commented on src/main/java/net/spy/memcached/CacheManager.java
> +      int poolIndex = CacheManager.poolIndex.getAndIncrement();
@uhm0311 

아래코드는 `commandCacheListChange` 내의 
`initArcusClient`가 호출되는 로직입니다.
`client==null`인 경우는 처음 캐시 매니저가 초기화 되거나
initArcusClient 메서드 내의 catch 로직에서만 `client = null`을 수행합니다.

```java
if (client == null) {
      if (!addrs.isEmpty()) {
        initArcusClient(addrs);
      }
      return;
    }
```

그렇게 되면, Cache List가 업데이트 될 때마다 호출되지 않는 것으로 이해하였는데
어떤 부분을 제가 놓친게 있을까요?

2024-03-29 05:04 UTC, uhm0311 commented on src/main/java/net/spy/memcached/CacheManager.java
> +      int poolIndex = CacheManager.poolIndex.getAndIncrement();
제가 착각을 했네요. 이 부분은 문제 없습니다.

2024-03-29 05:05 UTC, uhm0311 requested changes

2024-03-29 05:05 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    registerMbean();
기존 생성자에서도 똑같이 수행하는 부분이니 공통 부분을 메소드로 만들어서 사용합시다.

2024-03-29 05:38 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    registerMbean();
아래와 같은 메서드 호출하려면, collectionTranscoder와 
smgetKeyChunkSize의 final 키워드를 제거해야합니다.

```java
private void setField(CollectionTranscoder tc, int size) {
    collectionTranscoder = tc;
    smgetKeyChunkSize = size;
    //...
  }
```

일부 호출이 중복되더라도, final 키워드를 유지시키는게 좋을 것 같습니다.

2024-03-29 06:39 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    registerMbean();
저 3 라인에 해당하는 부분이 변경되어야 하면 변경 지점이 2곳이라서 통일하는 것이 좋을 것 같습니다.
`private ArcusClient(ConnectionFactory cf, String name, boolean attachIndex, List<InetSocketAddress> addrs)` 생성자를 하나 만듭시다.
안에서 attachIndex 값에 따라 clientIndex를 붙이기도 하고 안붙이기도 하는 것입니다.
그러면 새로 추가한 생성자는 지우고, getInstance() 메소드도 원래대로 되돌릴 수 있을 것 같습니다.
한 번 검토해주세요.

2024-04-01 05:16 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    registerMbean();
반영하였습니다.

2024-04-01 07:20 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    registerMbean();
getInstance()에서 이름을 만들어주는 부분도 다시 CachaManager로 옮길 수 있지 않나요?

2024-04-01 07:55 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    registerMbean();
반영하였습니다.

2024-04-01 08:03 UTC, uhm0311 requested changes

2024-04-01 08:03 UTC, uhm0311 commented on src/main/java/net/spy/memcached/CacheManager.java
> +        String cilentName = "ArcusClient" + "-" + poolIndex +
변수명에 오타가 있습니다.

2024-04-01 08:03 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +            : name, addrs);
이 부분 name 변수 넘겨주는게 복잡한데, static 메소드로 뺄 수 있나요?

2024-04-01 08:19 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +            : name, addrs);
반영했습니다.

2024-04-01 08:23 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return null;
아래와 같이 더 줄일 수 있을 것 같습니다.
동일한 로직인지 검토해주세요.

```java
if (attachIndex && name != null) {
  return name + ...;
}
return name;
```

2024-04-01 08:39 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return null;
### 함수 동작 분석

- **attachIndex가 false일 때**:
  - 기존 함수는 `name`을 그대로 반환합니다.
  - 변경 함수도 `name`을 그대로 반환합니다.
  - **결과**: 동일

- **attachIndex가 true이고, name이 null이 아닐 때**:
  - 기존 함수는 `name` 뒤에 "-"와 `clientIndex`를 붙여 반환합니다.
  - 변경 함수도 `name` 뒤에 "-"와 `clientIndex`를 붙여 반환합니다.
  - **결과**: 동일

- **attachIndex가 true이고, name이 null일 때**:
  - 기존 함수는 `name` (즉, null)을 반환합니다.
  - 변경 함수는 `null`을 반환합니다.
  - **결과**: 동일

2024-04-01 09:42 UTC, uhm0311 approved these changes

2024-04-12 01:22 UTC, uhm0311 commented
rebase 해주세요.

2024-04-17 01:01 UTC, uhm0311 commented on src/main/java/net/spy/memcached/CacheManager.java
> +      poolIndex.decrementAndGet();
여러 ArcusClientPool을 사용하는 경우 poolIndex 값에 동기화가 필요할 수 있습니다.
ArcusClientPool을 2개 쓰고 동시에 이 메소드를 호출하는데, 1개의 Pool에서 ArcusClient 객체 생성 중 try-catch 문에서 Exception이 발생하는 경우입니다.
객체 생성이 실패한 Pool은 사용되지 않으니 상관 없겠지만, 객체 생성에 성공한 Pool 내의 어떤 ArcusClient는 poolIndex가 1이고 어떤 ArcusClient는 poolIndex가 2가 됩니다.

일반적으로 2개 이상의 ArcusClientPool을 사용한다면 1개라도 생성에 실패했을 때 WAS가 구동되지 않을 것이고, ArcusClient 객체의 생성을 실패하는 것 또한 버그일 것입니다.
다만 IOException이 발생하는 `cfb.createConnection()` 메소드를 사용자가 정의할 수 있고 이에 따라 실패할 가능성은 있습니다.
따라서 기능의 무결성 관점에서는 다음의 두 가지 안 중 하나를 채택할 수 있습니다.

1. `poolIndex.decrementAndGet();`을 하지 않음
2. try-catch 문을 감싸는 동기화 기법 적용 (ReentrantLock, synchronized 등)

이러한 변경이 정말 필요한지는 검토해주세요.

2024-04-17 09:13 UTC, brido4125 commented on src/main/java/net/spy/memcached/CacheManager.java
> +      poolIndex.decrementAndGet();
위 로직을 수행하는 메서드인 `initArcusClient`는 
`commandCacheListChange`가 호출 될 때 수행됩니다. 

`commandCacheListChange`는 Watcher의 동작에 대한 콜백 함수인 processResult 내에서 호출됩니다.

processResult와 같은 콜백 메서드는 주키퍼 클라이언트 쪽의 스레드에 의해 호출됩니다.
이 부분을 좀 더 알아보니 해당 콜백 메서드는 
`EventThread`라는 `ClientCnxn` 클래스 내부의 정의된 스레드의 prcoessEvent에 의해 실행됩니다.

즉, 콜백 메서드가 하나의 스레드에 의해 처리되기에 
위와 같은 동시성 이슈는 발생하지 않을 것으로 예상됩니다.

(ArcusClientPool : CacheManager : Zookeeper : Clientcnxn : EventThread 모두 1대1 관계)

2024-04-17 09:20 UTC, uhm0311 commented on src/main/java/net/spy/memcached/CacheManager.java
> +      poolIndex.decrementAndGet();
ArcusClientPool을 2개 생성하면 Zookeeper 객체도 2개 생성되지 않나요?
Zookeeper 객체가 2개여도 EventThread는 1개라는 의미인가요?

2024-04-18 00:25 UTC, brido4125 commented on src/main/java/net/spy/memcached/CacheManager.java
> +      poolIndex.decrementAndGet();
poolIndex가 static 키워드인 점을 고려하지 않았네요. 
말씀하신 대로 변경해야 할 것 같습니다.

2024-04-19 03:06 UTC, uhm0311 commented on src/test/manual/net/spy/memcached/ArcusClientCreateTest.java
> +
Empty Line 1개로 변경

2024-04-19 03:06 UTC, uhm0311 commented on src/test/manual/net/spy/memcached/ArcusClientCreateTest.java
> +
Empty Line 1개로 변경

2024-04-19 03:06 UTC, uhm0311 commented on src/test/manual/net/spy/memcached/ArcusClientPoolCreateTest.java
> +    }
각 클라이언트의 이름이 정확히 만들어졌는지 확인할 필요는 없나요?

2024-04-23 04:35 UTC, brido4125 commented on src/main/java/net/spy/memcached/CacheManager.java
> +      poolIndex.decrementAndGet();
로직 제거하는 방안으로 적용시켰습니다.

2024-04-23 04:55 UTC, uhm0311 requested changes

2024-04-23 04:55 UTC, uhm0311 commented on src/test/manual/net/spy/memcached/ArcusClientCreateTest.java
> +    int clientIdx = 1;
이 변수는 어디에 사용되나요?

2024-04-23 04:55 UTC, uhm0311 commented on src/test/manual/net/spy/memcached/ArcusClientCreateTest.java
> +    Assert.assertEquals(nodes.size(), 1);
ArcusClient.getName()이 본 PR에서 의도하는 대로 만들어지는 지도 테스트 해봅시다.

2024-04-23 04:55 UTC, uhm0311 commented on src/test/manual/net/spy/memcached/ArcusClientPoolCreateTest.java
> +              CACHE_NODE_SIZE);
ArcusClient.getName()이 본 PR에서 의도하는 대로 만들어지는 지도 테스트 해봅시다.

2024-05-16 04:18 UTC, brido4125 commented on src/test/manual/net/spy/memcached/ArcusClientPoolCreateTest.java
> +              CACHE_NODE_SIZE);
CacheManager의 poolIndex 인스턴스가 테스트 환경 내에서 공유되기에
정확한 인덱스 값을 가져오기 위해 리플렉션을 사용했습니다.

2024-05-16 04:41 UTC, uhm0311 commented on src/test/manual/net/spy/memcached/ArcusClientPoolCreateTest.java
> +              CACHE_NODE_SIZE);
그래도 아마 테스트 도중에 간헐적으로 실패할 것 같습니다.
clientPoolIdx 값을 가져와서 정확한 이름을 테스트하지 말고, 현재 PR의 clientPoolIdx 값에 위치한 문자열이 어느 값이던 숫자로만 되어 있으면 테스트를 통과하도록 할 수 있나요?

2024-05-16 05:18 UTC, brido4125 commented on src/test/manual/net/spy/memcached/ArcusClientPoolCreateTest.java
> +              CACHE_NODE_SIZE);
@uhm0311 

junit4에서 병렬 실행과 관련된 문서입니다.
요약하자면, junit4에서 제공하 병렬 실행 옵션은 존재하지 않고
maven의 sureFire 플러그인을 통해 병렬 옵션을 줄 수 있습니다.

https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit.html#running-tests-in-parallel

java-client의 sureFire 구성을 보면 아래와 같이
병렬 옵션과 관련된 프로퍼티 없어서 테스트들이 순차적으로 동작함을 알 수 있습니다.
```java
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19</version>
                <configuration>
                    <skipAfterFailureCount>1</skipAfterFailureCount>
                    <excludes>
                        <!-- skip some tests for servers without IPv6 support.  -->
                        <exclude>**/BinaryIPV6ClientTest.java</exclude>
                        <exclude>**/AsciiIPV6ClientTest.java</exclude>
                        <!-- This early ZK test is broken -->
                        <exclude>**/CacheMonitorTest.java</exclude>
                        <!-- Arcus does not support binary protocol -->
                        <exclude>**/BinaryClientTest.java</exclude>
                        <!-- Does not work with ZK -->
                        <exclude>**/RedistributeFailureModeTest.java</exclude>
                        <exclude>**/LoggingTest.java</exclude>
                    </excludes>
                </configuration>
            </plugin>
```


병렬로 실행되는 경우를 제외하고 리플렉션을 통해 poolIndex 값이 잘못 가져와지는 경우가 또 있을까요?

없다면 그래도 코멘트 주신대로 변경을 할까요?

2024-05-16 08:04 UTC, uhm0311 requested changes

2024-05-16 08:04 UTC, uhm0311 commented on src/test/manual/net/spy/memcached/ArcusClientPoolCreateTest.java
> +    Pattern compile = Pattern.compile("ArcusClient-(\\d+)\\(");
뒤에 붙는 `<i+1>-POOL_SIZE)`까지 검사합시다.
for문 내에서 `"ArcusClient-(\\d+)\\(" + (i + 1) + "-" + POOL_SIZE + "\\)"`로 하면 될 것입니다.
그 뒤에 붙는 것은 캐시 서버 주소이니 지금과 동일하게 검사하지 않으면 됩니다.

2024-05-16 08:57 UTC, uhm0311 requested changes
커밋 메세지 `Arcusclient => ArcusClient` 수정해주세요.

2024-05-16 08:57 UTC, uhm0311 commented on src/test/manual/net/spy/memcached/ArcusClientPoolCreateTest.java
> +    //create second ArcusClientPool instance.
두번째 풀을 만드는 것이 poolIndex가 증가하고 있음을 확인하기 위한 용도라면 CacheManager에 clientIndex의 현재 값을 반환하는 default 접근제한자 Getter를 두고, 첫번째 풀을 만들었을 때의 값이 두번째 풀을 만들었을 때의 값보다 작음을 테스트합시다.

2024-05-17 01:44 UTC, uhm0311 commented on src/test/manual/net/spy/memcached/ArcusClientPoolCreateTest.java
> +  }
리플렉션 사용하는 이유가 무엇인가요?

2024-05-17 01:56 UTC, brido4125 commented on src/test/manual/net/spy/memcached/ArcusClientPoolCreateTest.java
> +  }
테스트 코드에서만 호출되는 메서드를 최대한 구현하지 않으려고 합니다.

2024-05-17 02:08 UTC, uhm0311 submitted a review, later dismissed

2024-05-17 07:30 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  private static String checkAttachAndNull(String name, boolean attachIndex) {
메서드명을 verifyAndAttachIndex 와 같이 인덱스를 추가한다는 의미를 추가하는 것이 어떨까요?
조건에 맞을 때만 attach하는 역할이기 때문에 attachIndex 만으로도 의미가 충분할 것 같습니다.

2024-05-17 07:30 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  private static final AtomicInteger clientIndex = new AtomicInteger(1);
static final 변수를 모두 대문자(CLIENT_INDEX)로 표현하지 않아도 괜찮을까요?

2024-05-17 07:47 UTC, oliviarla submitted a review, later dismissed

2024-05-20 05:41 UTC, brido4125 commented
@uhm0311 
ArcusClient만 사용하는 경우
사용자가 커스텀하게 name을 주는 경우는 
client_index가 적용되지 않도록 변경하였습니다.

2024-05-20 07:02 UTC, uhm0311 requested changes

2024-05-20 07:02 UTC, uhm0311 commented on src/test/manual/net/spy/memcached/ArcusClientPoolCreateTest.java
> +        Assert.assertEquals(matcher.matches(), true);
true와 비교하는 경우 assertTrue() 사용

2024-05-23 08:01 UTC, uhm0311 submitted a review, later dismissed

2024-05-23 11:13 UTC, jhpark816 reviewed
리뷰 완료

2024-05-23 11:13 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  private static final AtomicInteger CLIENT_INDEX = new AtomicInteger(1);
0부터 시작하는 index 개념이라기 보다는
1부터 시작하는 id 또는 번호(num) 같은 느낌입니다.
ARCUS_CLIENT_ID 라는 용어는 어떤가요?

2024-05-23 11:13 UTC, jhpark816 commented on src/main/java/net/spy/memcached/CacheManager.java
> +  private static final AtomicInteger POOL_INDEX = new AtomicInteger(1);
ARCUS_POOL_ID는 어떤지?

2024-05-23 11:13 UTC, jhpark816 commented on src/main/java/net/spy/memcached/CacheManager.java
> +      int poolIndex = CacheManager.POOL_INDEX.getAndIncrement();
이 문장을  아래와 같이 ArcusClient Pool 생성 이전 위치에 두는 것이 어떤가요?

```java
    cfb.setInitialObservers(Collections.singleton(observer));

    int poolIndex = CacheManager.POOL_INDEX.getAndIncrement();
    
    client = new ArcusClient[poolSize];
    int i = 0;
```

2024-05-24 08:07 UTC, brido4125 commented
@jhpark816 

ArcusClient 객체 생성의 책임을 ArcusClientPool에게 옮기는 작업은
@uhm0311 님과 논의했을 때도 CacheManager의 책임을 줄이기에
좋은 방향이라는 것에 서로 동의하였습니다.

다만, 제가 판단하건데 이러한 변경 사항이 본 PR과는 별개로 처리되어야 할 것 같습니다.
CacheManager의 어떤 책임을 분리시키고 어떤식으로 구현할지에 대해 
신중하게 설계를 해야하기 때문입니다.
또한 본 PR의 목적과도 전혀 다르기 때문입니다.

말씀하신 부분은 새로운 이슈로 생성하고 별도로 처리하도록 하겠습니다.

2024-05-24 08:20 UTC, jhpark816 commented
@uhm0311 최종 리뷰 부탁합니다.

2024-05-24 09:04 UTC, uhm0311 approved these changes

2024-05-24 10:34 UTC, merged