ENHANCE: Change getNodeForKey logic in locator.
naver/arcus-java-client pull request #755
Opened 2024-05-10 06:12 UTC by brido4125

### 관련 이슈
https://github.com/jam2in/arcus-works/issues/558

### 변경 내용
중복으로 호출되는 ketamaNodes TreeMap에 대한 조회를 최적화하였다.

2024-05-10 07:52 UTC, uhm0311 requested changes

2024-05-10 07:52 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> -          }
이 방식은 그대로 사용하도록 합시다.

2024-05-10 07:52 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java
> +        return rv;
여기도 rv를 반환하지 말고 null을 반환합시다.

2024-05-10 07:52 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java
> +      rv = rg.getNodeByReplicaPick(pick);
여기서 rv에 대입하지 않고 바로 반환하면 rv 변수는 제거할 수 있습니다.

2024-05-10 07:52 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java
> +      }
rg 변수를 선언하는 위치를 여기로 옮깁시다.

2024-05-10 08:16 UTC, uhm0311 approved these changes

2024-05-12 11:11 UTC, jhpark816 reviewed
리뷰 완료

2024-05-12 11:11 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +      Long nodeHash = ketamaNodes.ceilingKey(hash);
ceilingEntry() 검토 바랍니다.

2024-05-13 02:42 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +              = ketamaNodes.ceilingEntry(hash);
1줄로 표현 가능한가요?

2024-05-13 08:01 UTC, uhm0311 submitted a review, later dismissed

2024-05-13 09:36 UTC, jhpark816 reviewed
리뷰 완료

2024-05-13 09:36 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java
> +      // return a node (master / slave) for the replica pick request.
아래와 같이 nodeHash 대신에 entry 이름의 변수가 나을 것 같고,
entry == null 인 경우에 entry를 firstEntry()로 설정하시죠.

```java
      Map.Entry<Long, SortedSet<MemcachedReplicaGroup>> entry
              = ketamaGroups.ceilingEntry(hash);
      if (entry == null) {
        entry = ketamaGroups.firstEntry();
      }
      MemcachedReplicaGroup rg = entry.getValue().first();
      // return a node (master / slave) for the replica pick request.
```

위의 코드에서도 nodeHash 보다 entry가 나은 것 같습니다.

2024-05-14 03:19 UTC, jhpark816 commented
@uhm0311 최종 리뷰 바랍니다.

2024-05-14 03:46 UTC, uhm0311 approved these changes

2024-05-14 03:49 UTC, merged