REACTOR: ArucsClientPool constructor parameters.
naver/arcus-java-client pull request #764
Opened 2024-06-05 07:19 UTC by brido4125

### 이슈
https://github.com/jam2in/arcus-works/issues/572

### 구현
ArcusClientPool 의 생성자를 리팩토링하였습니다.
기존 코드와 동일하게 CacheManager 생성자가 완료되면,
zk로부터 캐시리스트 정보를 받아옴이 보장됩니다.

그러므로 cacheManager.getAC()가 정확한 정보를 가지게 됩니다.

2024-06-05 08:14 UTC, uhm0311 requested changes

2024-06-05 08:14 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClientPool.java
> +    this.client = cacheManager.getAC();
client를 먼저 할당 받고 poolSize에는 client.length를 할당합시다.

2024-06-10 02:22 UTC, uhm0311 approved these changes

2024-06-10 03:06 UTC, jhpark816 reviewed
리뷰 완료

2024-06-10 03:06 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClientPool.java
> +    this.rand = new Random();
ArcusClientPool 생성자에서 cacheManager를 인자로 받는 의도는 무엇인가요?

아래의 clientPool 인자만 가져도 충분하지 않나 생각됩니다.
```java
public ArcusClientPool(ArcusClient[] clientPool)
```

2024-06-10 03:14 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClientPool.java
> +    this.rand = new Random();
본 PR의 이슈와 관련 있습니다.
간단히 설명하자면, CacheManager나 Locator 등의 Pool에서 사용되는 객체들에 대한 의존성을
ArcusClientPool에 위임하고 ArcusClient와의 결합을 끊어내려고 합니다.

이슈 설명 한번 읽어주세요.

2024-06-10 03:23 UTC, jhpark816 commented
@oliviarla 추가 리뷰어 지정합니다.

2024-10-04 08:49 UTC, uhm0311 commented
PR 제목을 실제 변경사항과 일치하게 바꿔주세요.

2024-10-04 12:48 UTC, jhpark816 commented
> 추후 ArcusClient가 상속 구조를 가질 수도 있을 것 같아 private으로 설정하지 않았습니다.

ArcusClient 상속할 경우가 추후에 발생하나요?

2024-10-07 00:53 UTC, brido4125 commented
> ArcusClient 상속할 경우가 추후에 발생하나요?

FrontCacheMemcachedClient와 MemcachedClient의 관계처럼
ArcusClient도 플러그인 성격의 어떠한 클래스를 상속할 수도 있다고 생각합니다.

2024-10-07 01:12 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  public static ArcusClient createArcusClientWithProxy(List<InetSocketAddress> addrs,
Proxy에 연결하는 경우라면 Proxy에 맞는 NodeLocator가 있어야 하므로 Proxy 단어가 붙는 것은 부적합해 보입니다.

2024-10-07 06:29 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  public static ArcusClient createArcusClientWithProxy(List<InetSocketAddress> addrs,
@uhm0311 @oliviarla 
기존의 public ArcusClient() 생성자를 대체할만한
적절한 메서드 명 추천 가능하실까요?

2024-10-07 08:00 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  public static ArcusClient createArcusClientWithProxy(List<InetSocketAddress> addrs,
그냥 createArcusClient로 하면 어떤가요?

2024-10-07 08:25 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  public static ArcusClient createArcusClientWithProxy(List<InetSocketAddress> addrs,
주석에 proxy 관련이 아직 남았습니다.

2024-10-07 09:16 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> -  public ArcusClient(ConnectionFactory cf, String name, List<InetSocketAddress> addrs)
여기는 deprecated로 두지 않고 바로 protected로 변경해도 되나요?

2024-10-08 00:37 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> -  public ArcusClient(ConnectionFactory cf, String name, List<InetSocketAddress> addrs)
반영했습니다.

2024-10-08 07:39 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +  public static ArcusClient createArcusClientWithProxy(List<InetSocketAddress> addrs,
아직 있습니다.

2024-10-08 07:44 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> -  public ArcusClient(ConnectionFactory cf, String name, List<InetSocketAddress> addrs)
여기선 name을 넘길 수 있는데, name을 넘길 수 있는 새로운 creatArcusClient()가 없습니다.

2024-10-08 07:48 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> -  public ArcusClient(ConnectionFactory cf, String name, List<InetSocketAddress> addrs)
이 부분 관련해서 의견이 필요합니다.
기존의 createArcusClient 및 createArcusClientPool 등은
name 인자를 넘기지 않고 생성하도록 하였습니다.

그래서 이번 변경에서 name을 추가한다면 기존에 존재하던 
스태틱 메서드들도 추가하는게 일관된 형태라고 생각됩니다.

다만, name이라는 필드를 유지한다면 기존 함수의 호환성을 유지 하는것 제외하고는
중요한 인자라는 생각이 들지는 않아서 현재 구현에서는 제외하였습니다.

2024-10-08 08:11 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> -  public ArcusClient(ConnectionFactory cf, String name, List<InetSocketAddress> addrs)
만약 응용에서 name을 따로 넘겨준다면 로그에서 구분하는 용도일 것입니다.
하지만 일반적으로는 Pool을 사용하므로 name을 따로 넘기는 경우는 많지 않을 것 같습니다.

2024-10-08 08:11 UTC, uhm0311 submitted a review, later dismissed

2024-10-10 01:30 UTC, oliviarla submitted a review, later dismissed

2024-10-14 02:21 UTC, jhpark816 reviewed
리뷰 완료

2024-10-14 02:21 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      clients[i] = new ArcusClient(cfb.build(), addrs);
ArcusClient 호출 시에 어떤 name 값으로 지정해야 하는 지를 검토 바랍니다.

2024-10-14 02:21 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      clients[i] = new ArcusClient(cfb.build(), addrs);
용어 관점
- size 대신에 poolSize가 나을 것 같습니다.
- 다른 API에서 poolSize 사용하고 있습니다.
- 단순히 size는 addrs 목록의 size인지 pool size인지가 구분되지 않습니다.

2024-10-14 02:21 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      clients[i] = new ArcusClient(cfb.build(), addrs);
@brido4125 @oliviarla @uhm0311 

`addrs, poolSize, cfb` 인자 순서가 나은 것 같은 데, 다른 API의 인자 순서와 일관되게 한 거죠?
새로운 API에서만 인자 순서를 변경하는 것이 어색한거죠?

2024-10-14 02:21 UTC, jhpark816 commented on src/test/java/net/spy/memcached/ClientBaseCase.java
> +              .setInitialObservers(cf.getInitialObservers()));
`new CFB(cf)` 호출하는 것과 어떤 차이가 있나요?

2024-10-14 02:21 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                                              ConnectionFactoryBuilder cfb)
`name, addrs, cfb` 인자를 가지는 API도 제공해야 하지 않는 지 ?

2024-10-14 02:22 UTC, jhpark816 commented
그리고, PR 처음 코멘트는 현재 수정 사항을 나타내도록 변경되어야 합니다.

2024-10-14 02:37 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                                              ConnectionFactoryBuilder cfb)
아래와 같이 의견이 취합되었습니다.

https://github.com/naver/arcus-java-client/pull/764#discussion_r1791374594

2024-10-14 04:36 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      clients[i] = new ArcusClient(cfb.build(), addrs);
> addrs, poolSize, cfb 인자 순서가 나은 것 같은 데, 다른 API의 인자 순서와 일관되게 한 거죠?
새로운 API에서만 인자 순서를 변경하는 것이 어색한거죠?

넵 다른 api와 일관되도록 의도했습니다.

2024-10-14 05:04 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                                              ConnectionFactoryBuilder cfb)
zookeeper 주소를 입력받는 createArcusClient 메서드에도 name을 입력받지 않고 있으며 name 필드 자체가 내부적으로 로깅 용도로 사용하는 값이므로, 제 생각에는 name을 입력받는 메서드를 별도로 추가하지 않아도 될 것 같습니다.

2024-10-14 07:56 UTC, brido4125 commented on src/test/java/net/spy/memcached/ClientBaseCase.java
> +              .setInitialObservers(cf.getInitialObservers()));
`new CFB(cf)`의 경우 내부적으로
getInitialObservers 메서드를 오버라이드해서
비어있는 리스트를 리턴합니다.

그래서 `new CFB(cf)`를 호출할 경우 빈 리스트가 테스트 로직내에서 사용되어
ObesrverTest의 testInitialObservers 테스트 케이스에서 에러가 발생합니다.

2024-10-15 02:35 UTC, uhm0311 approved these changes

2024-10-16 02:12 UTC, brido4125 commented
@jhpark816 님 의견에 따라 close 합니다.

2024-10-16 02:12 UTC, closed without merging