FIX: Concurrency problem in locator allNodes.
naver/arcus-java-client pull request #769
Opened 2024-07-02 01:27 UTC by brido4125

## 이슈
https://github.com/jam2in/arcus-works/issues/490#issuecomment-2199206597
위 코멘트 말고도 Braodcast 연산 시에 getAll()을 호출하는데
read는 worker-thread 로 write는 IO 스레드에 의해서
ConcurrentModificationException이 발생할 수도 있습니다.

왜냐하면 기존 구현은 리턴되는 Collections.unmodifiableCollection이
allNodes 참조와 연결되어있기 때문입니다.

반환 값에 새로운 참조를 넣어서 기존 allNodes 참조와의 
연결을 끊어주면 동시성 문제가 발생하지 않습니다.

다른 대안으로는 `new CopyOnWriteArrayList<>(allNodes);`와 같은 타입을 리턴할 수도 있습니다.
다만 alterNodes와의 구현 통일성 때문에 현재 구현을 채택했습니다.

참고로 alterNodes는 위와 같이 서로 다른 스레드가 
각각 동시에 read/write 하는 로직이 존재하지 않습니다.

2024-07-02 02:07 UTC, uhm0311 requested changes

2024-07-02 02:07 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    return Collections.unmodifiableCollection(new ArrayList<>(allNodes));
생성자에서 allNodes를 대입할 때 `new CopyOnWriteArrayList<>()`로 감싸서 대입하도록 합시다.

2024-07-02 02:34 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    return Collections.unmodifiableCollection(new ArrayList<>(allNodes));
현재 구현의 경우에도 언급된 문제를 해결하지 않나요?

getAll()에 의해 리턴된 Collection의 참조에는 동시에 여러 스레드가 접근하는 경우는 없는 것 같습니다.

2024-07-02 02:36 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    return Collections.unmodifiableCollection(new ArrayList<>(allNodes));
getAll() 메소드 호출 시 allNodes를 계속 복제한다는 문제가 있습니다.
복제할 필요가 없어 보입니다.

2024-07-02 02:52 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    return Collections.unmodifiableCollection(new ArrayList<>(allNodes));
말씀하신 코멘트가 `Collections.unmodifiableCollection(new CopyOnWriteArrayList<>(allNodes));`로 변경하는게 맞나요?

2024-07-02 03:06 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    return Collections.unmodifiableCollection(new ArrayList<>(allNodes));
ArcusKetamaNodeLocator 의 생성자에서 allNodes 필드를 초기화할 때 `new CopyOnWriteArrayList<>(allNodes)`를 사용하라는 의미인 것 같고 저도 동의합니다.

2024-07-02 03:28 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    return Collections.unmodifiableCollection(new ArrayList<>(allNodes));
@brido4125 

@oliviarla 님의 코멘트를 의미하는 것이었습니다.

2024-07-02 06:59 UTC, oliviarla approved these changes, later dismissed

2024-07-02 07:38 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    allNodes = new CopyOnWriteArrayList<>(nodes);
KetamaNodeLocator 클래스에도 적용해야 하지 않을까요?

2024-07-02 07:57 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    allNodes = new CopyOnWriteArrayList<>(nodes);
기존 MemcachedClient 구현에서부터 KetamaNodeLocator의 경우 
아래와 같이 동시성 문제를 전혀 고려하지 않고 구현되어 있습니다.

```java
public Collection<MemcachedNode> getAll() {
    return allNodes;
  }
```

유지보수 관점에서 KetamaNodeLocator 또는 ArrayModNodeLocator는 
`@Deprecated` 시키거나 ArcusXXXLocator 구현의 변화를 
따라가지 않도록 하는게 좋을 것 같은데 어떻게 생각하실까요?
(테스트 코드 때문에 내부적으로는 사용되어야 할 것 같습니다)

2024-07-02 08:06 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    allNodes = new CopyOnWriteArrayList<>(nodes);
arcus-java-client는 arcus-memcached가 아닌 memcached에 연결해서도 사용할 수 있어야 합니다.
따라서 KetamaNodeLocator도 유지해야 합니다.

2024-07-02 12:06 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    allNodes = new CopyOnWriteArrayList<>(nodes);
@brido4125 @uhm0311 
cache list update 이벤트에 의해 allNodes 변경하는 경우,
allNodes 원소들로 구성된 newAllNodes 생성한 후에
newAllNodes에 대해 변경된 캐시 노드를 추가/제거하고 나서,
`allNodes = newAllNodes;` 형태로 replace하는 방법이 있습니다.

관련하여 질문은
- 위의 방법으로 구현한다면 구현이 쉬운가요?
- CopyOnWriteArrayList 사용하는 방식과는 장단점 비교를 한다면 ?

2024-07-02 23:53 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    allNodes = new CopyOnWriteArrayList<>(nodes);
@jhpark816 

> 위의 방법으로 구현한다면 구현이 쉬운가요?

update 메서드가 변경 되어야 하니 지금 PR보다는 복잡합니다.

> CopyOnWriteArrayList 사용하는 방식과는 장단점 비교를 한다면 ?

newAllNodes의 타입을 ArrayList를 사용한다고 가정하겠습니다.
장점은 없는것 같습니다.
단점은 
1. 매 update 요청마다 새로운 newAllNodes 객체를 생성해야합니다.(미미한 수준)
2. CopyOnWriteArrayList 구현에 비해 코드의 의미를 파악하는데 시간이 오래 소요됩니다.
3. KetamaNodeLocator와 ArrayModNodeLocator의 경우 update()를 지원하지 않아 별도의 형태로 현재 이슈를 해결해야합니다.


간단히 구현할 수 있는 방법이 있는데 
어떤 부분 때문에 위와 같은 방식을 제안하시는 건가요?

2024-07-03 00:39 UTC, jhpark816 reviewed
리뷰 완료

2024-07-03 00:39 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    allNodes = new CopyOnWriteArrayList<>(nodes);
@uhm0311 
위의 사항에 대해 검토하고 의견주세요.

2024-07-03 00:39 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    allNodes = new CopyOnWriteArrayList<>(nodes);
`KetamaNodeLocator`는 그대로 유지해야 합니다.

`KetamaNodeLocator` 객체의 allNodes에 대해 element 추가/삭제 등이 존재하나요?

2024-07-03 00:39 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    allNodes = new CopyOnWriteArrayList<>(an);
readOnlyCopy 목적이라 CopyOnWriteArrayList 변환이 필요한 지 의문입니다.

2024-07-03 02:26 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    allNodes = new CopyOnWriteArrayList<>(an);
MemcachedClient의 getNodeLocator를 호출하면 
getReadonlyCopy가 호출되고 위의 private 생성자가 호출됩니다.

readOnlyCopy된 Locator의 경우 IO스레드의 
update에 의한 동시성 이슈는 발생하지 않을 것 같습니다.
원복하는게 좋을 것 같네요.

2024-07-03 02:29 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    allNodes = new CopyOnWriteArrayList<>(nodes);
> KetamaNodeLocator 객체의 allNodes에 대해 element 추가/삭제 등이 발생하나요?

앞선 코멘트에서 나온것처럼 update() 지원을 하지 않고 
allNodes에 대한 변경 로직이 내부에 존재하지 않습니다.

애초에 update에 의한 이슈가 발생하지 않으므로 유지 가능합니다.

2024-07-03 06:46 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    allNodes = new CopyOnWriteArrayList<>(nodes);
CopyOnWriteArrayList는 동작 특성상 Write 연산이 느리게 동작합니다.
캐리 리스트 업데이트가 연속적으로 반영된다면 캐시 리스트 업데이트를 위해 Locator의 Lock을 빈번하게, 그리고 오랫동안 잡고 있을 수 있습니다.
Replace 방식으로 바꿀 경우의 코드가 그렇게 복잡해질 것으로 보이지는 않습니다.

본 이슈와는 별개로 allNodes와 Lock에 대한 조사 중 발견한 것으로 getReadonlyCopy() 메소드의 구현에서 Lock을 획득하는 방식이 올바르지 않게 구현되어 있는 것 같습니다.

```java
  public NodeLocator getReadonlyCopy() {
    TreeMap<Long, SortedSet<MemcachedNode>> smn =
            new TreeMap<>(ketamaNodes);
    Collection<MemcachedNode> an = new ArrayList<>(
            allNodes.size());

    lock.lock();
    try {
      // Rewrite the values a copy of the map.
      for (Map.Entry<Long, SortedSet<MemcachedNode>> me : smn.entrySet()) {
        SortedSet<MemcachedNode> nodeROSet =
                new TreeSet<>(config.new NodeNameComparator());
        for (MemcachedNode mn : me.getValue()) {
          nodeROSet.add(new MemcachedNodeROImpl(mn));
        }
        me.setValue(nodeROSet);
      }
      // Copy the allNodes collection.
      for (MemcachedNode n : allNodes) {
        an.add(new MemcachedNodeROImpl(n));
      }
    } finally {
      lock.unlock();
    }

    return new ArcusKetamaNodeLocator(smn, an, config);
  }
```

ketamaNodes를 복제하여 smn 객체로 두기 전에 미리 Lock을 잡아야 새롭게 생성할 ArcusKetamaNodeLocator 내의 ketamaNodes 형상과 allNodes 형상이 일치할 것입니다.

2024-07-03 07:00 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    allNodes = new CopyOnWriteArrayList<>(nodes);
@uhm0311 
`getReadonlyCopy()` 구현 오류를 수정하기 위한 PR을 따로 올려주시죠.

2024-07-03 07:05 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    allNodes = new CopyOnWriteArrayList<>(nodes);
@uhm0311 @brido4125 
의견입니다.
- newAllNodes 생성 후에 replace 하는 비용이 CopyOnWriteArrayList 보다 낮을 것 같습니다.
   - 한번의 cache list update에서 add or remove 되는 cache nodes가 많을 수록 비용 차이가 커집니다.
   - 클러스터 규모(캐시 노드의 수)가 클수록 비용 차이가 더 커지게 됩니다.
- newAllNodes 생성 후에 replace 하는 구현이 간단하다면 이 구현이 나을 것 같습니다.
  이 구현이 복잡다면, CopyOnWriteArrayList 방식도 괜찮다고 생각합니다.

2024-07-03 09:18 UTC, brido4125 commented on src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
> +    allNodes = new CopyOnWriteArrayList<>(nodes);
구현이 복잡하지 않아 replace 방식으로 변경하였습니다.

2024-07-03 10:37 UTC, uhm0311 approved these changes

2024-07-03 10:45 UTC, jhpark816 commented
@oliviarla 리뷰 바랍니다.

2024-07-04 02:00 UTC, oliviarla approved these changes

2024-07-04 09:05 UTC, brido4125 commented
@jhpark816 

오프라인에서 말씀하신 사항에 대한 답변입니다.
ketamaNodes를 read하여 key에 해당하는 노드를 선정할 때
update() 로직에서 사용되는 동일한 lock 객체를 사용합니다.


```java
MemcachedNode getNodeForKey(long hash) {
    lock.lock();
    try {
      if (ketamaNodes.isEmpty()) {
        return null;
      }
      Map.Entry<Long, SortedSet<MemcachedNode>> entry = ketamaNodes.ceilingEntry(hash);
      if (entry == null) {
        entry = ketamaNodes.firstEntry();
      }
      return entry.getValue().first();
    } finally {
      lock.unlock();
    }
  }
```

2024-07-07 06:20 UTC, jhpark816 commented
@oliviarla 한번 더 점검하고, 의견주세요.

2024-07-08 11:42 UTC, oliviarla commented
@jhpark816 
제가 확인한 바로는 allNodes를 사용하는 메서드는 IO스레드에서만 호출되고, update 메서드 자체도 IO 스레드에서만 호출되기 때문에 문제가 없을 것 같습니다.

2024-07-09 01:15 UTC, brido4125 commented
@jhpark816 @oliviarla 

어떤 관점에서 점검을 지시 하셨는지는 모르겠는데,
단순히 Broadcast 연산만 하더라도 응용의 스레드가 
allNodes를 read 해갈 수 있지 않나요?

추가적으로 locator를 리팩토링하는 설계에 있어 
allNodes도 변경이 생길 것 같아 본 PR은 draft로 돌려놓겠습니다.

2024-09-06 07:40 UTC, jhpark816 commented
@brido4125 rebase 해 주시죠.

2024-09-06 07:54 UTC, brido4125 commented
@jhpark816 

본 PR은 현재 진행중인 이슈(Locator 공유)에 의해서 변경될 가능성이 굉장히 높습니다.
(allNodes가 tcp 커넥션의 리스트라서 현재 구현처럼 Locator 클래스 내에 존재하지 않을 확률이 높음)

그래서 close를 시켜놓고 보류하려고 합니다.

2026-01-22 11:10 UTC, jhpark816 commented
@brido4125 
draft => open 해 주세요.

@uhm0311 @oliviarla 
현재 PR 그대로 반영하면 될 것 같은데요.
한번 확인 바랍니다.

2026-01-23 02:05 UTC, uhm0311 commented
충돌 난거만 해결하면 될 것 같습니다.

2026-03-16 08:32 UTC, closed without merging