INTERNAL: add mop upsert API
naver/arcus-java-client pull request #774
Opened 2024-07-04 10:06 UTC by oliviarla

- https://github.com/jam2in/arcus-works/issues/579
- mop upsert API를 추가합니다.

2024-07-11 07:14 UTC, jhpark816 commented
@oliviarla 
이제 PR 정식으로 보내주시죠.

2024-07-12 01:23 UTC, jhpark816 commented
@brido4125 리뷰 바랍니다.

2024-07-12 03:36 UTC, brido4125 requested changes
CollectionOperationImple 클래스의 생성자에서
setAPIType을 설정하는 로직이 빠진것 같아요
추가해주셔야할 것 같습니다.

2024-07-12 03:36 UTC, brido4125 commented on src/test/manual/net/spy/memcached/collection/map/MopUpsertTest.java
> +      // then
CollectionOperationStatus의 상태와 메세지도 검증합시다.

2024-07-16 07:45 UTC, brido4125 approved these changes

2024-07-17 11:23 UTC, jhpark816 commented
@uhm0311 추가 리뷰어 지정합니다.

2024-07-18 06:34 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClientIF.java
> +   * If element does not exist and attributesForCreate argument is not null,
원소가 아닌 Map 그 자체가 없을 때를 의미하는 주석이 되어야 하지 않나요?

2024-07-18 06:34 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClientIF.java
> +   * If element does not exist and attributesForCreate argument is not null,
여기 주석도 마찬가지입니다.

2024-07-18 06:50 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClientIF.java
> +   * If element does not exist and attributesForCreate argument is not null,
반영했습니다.

2024-07-18 06:51 UTC, uhm0311 approved these changes

2024-07-18 13:17 UTC, merged