INTERNA: Change callback method for mutate operation.
naver/arcus-java-client pull request #786
Opened 2024-07-11 05:12 UTC by brido4125

2024-07-15 02:14 UTC, uhm0311 requested changes

2024-07-15 02:14 UTC, uhm0311 commented on src/main/java/net/spy/memcached/MemcachedClient.java
> +          public void gotMutatedValue(Long result) {
`gotDelta`로 이름을 바꿉시다.

2024-07-15 02:14 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ops/MutatorOperation.java
> +     * @param result the value that was mutated.
주석도 `변화량`을 매개변수로 넣어줘야 한다는 점을 더욱 명확하게 나타내는 문장으로 바꾸고요.

2024-07-30 23:41 UTC, brido4125 commented
아래 코멘트에 의해서 PR close 하고
callback 처리 시 일괄적으로 다루겠습니다.

https://github.com/jam2in/arcus-works/issues/584#issuecomment-2235803311

2024-07-30 23:41 UTC, closed without merging