INTERNAL: make waitForQueues method into private
naver/arcus-java-client pull request #794
Opened 2024-08-12 09:04 UTC by oliviarla

### 🔗 Related Issue

- https://github.com/jam2in/arcus-works/issues/585
### ⌨️ What I did

- waitForQueues 메서드를 private으로 변경합니다.
- MemcachedThreadBench 에서 사용되던 waitForQueues는 MemcachedClient#set 의 결과를 받은 후 다시 요청을 보내므로 필요 없어 제거합니다.
- ObserverToy에서 사용되던 waitForQueues는 asyncGet으로 대체합니다.

2024-08-12 09:07 UTC, uhm0311 commented on src/main/java/net/spy/memcached/MemcachedClientIF.java
> -
다시 보니 spymemcached에도 있는 메소드였네요.
@jhpark816 spymemcached와 다르게 가도 괜찮나요?

2024-08-12 09:15 UTC, jhpark816 commented on src/main/java/net/spy/memcached/MemcachedClientIF.java
> -
@uhm0311 
아래 수정된 테스트가 valid하다면, private으로 변경하고자 합니다.
즉, 이 부분에 한하여 spymemcached와 다르게 가려고 합니다.

2024-08-12 09:32 UTC, uhm0311 requested changes

2024-08-12 09:32 UTC, uhm0311 commented on src/test/manual/net/spy/memcached/test/ObserverToy.java
> +
저장하지 않아도 됩니다.

2024-08-12 09:32 UTC, uhm0311 commented on src/test/manual/net/spy/memcached/test/ObserverToy.java
>      }
아래와 같이 합시다.

```suggestion
    while (true) {
      try {
        client.asyncGet("ObserverToy").get(1, TimeUnit.SECONDS);
        Thread.sleep(1000);
      } catch (Exception e) {
        e.printStackTrace();
      }
    }
```

2024-08-13 01:03 UTC, uhm0311 approved these changes

2024-08-13 01:24 UTC, merged