INTERNAL: make lop piped operations process synchronously
naver/arcus-java-client pull request #795
Opened 2024-08-19 06:37 UTC by oliviarla

### 🔗 Related Issue

- https://github.com/jam2in/arcus-works/issues/540

### ⌨️ What I did

- 500개 아이템 단위로 Operation 객체를 나누어 비동기로 요청을 보내던 것을 동기 방식으로 보내어 Arcus 서버에 과도한 부하가 들어가는 것을 방지하고, 실패 시 다음 Operation을 수행하지 않도록 합니다.
  - 만약 CLIENT_ERROR, SERVER_ERROR 실패가 발생하면 그 즉시 latch.countdown을 호출해 더이상 로직을 수행하지 않습니다.
  - OVERFLOWED, OUT_OF_RANGE 같은 실패가 발생하면 이후의 item에 대해 CANCELLED 오류를 반환하도록 합니다.
- 기존에 asyncLopPipedInsert에서 입력받은 valueList 순서대로 저장하지 않는 문제가 있었고 이를 순서대로 저장하도록 변경했습니다.
- 시범적으로 Lop Piped Insert에만 적용합니다.
- future를 통한 비동기 수행이 되기 때문에 메서드명은 그대로 두고자 합니다.

2024-08-19 08:41 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                    || rv.hasErrored()
Future에 CANCELED를 하나하나 추가하는 대신 HashMap을 입력받아 putAll 메서드를 통해 넣는 것 외에는 딱히 떠오르지 않습니다. 다만 이렇게 할 경우 내부적으로 사용할 용도인 메서드가 Future에 추가되므로 클라이언트에게 노출될 수 있습니다.

2024-08-19 11:31 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                    || rv.hasErrored()
hasErrored()를 호출할 때 지금까지 처리된 Operation들의 Error 여부를 메모리에 boolean 필드 1개로 캐싱해둘 수 있을 것입니다.
캐싱된 값이 true이면 바로 true를 반환하면 됩니다.
캐싱된 값이 false이면 캐싱 이후에 처리된 연산에 대한 Error 여부만 계산하면 됩니다.

2024-08-21 03:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                  }
> Future에 CANCELED를 하나하나 추가하는 대신 HashMap을 입력받아 putAll 메서드를 통해 넣는 것 외에는 딱히 떠오르지 않습니다. 다만 이렇게 할 경우 내부적으로 사용할 용도인 메서드가 Future에 추가되므로 클라이언트에게 노출될 수 있습니다.

여기 로직을 말하는 것 같은데요.
여기는 크게 수정할 수 있는 부분이 아닌 것 같습니다.
단, CompletableFuture를 지원하지 않는 형태에서는 Future 내에 캔슬 여부를 boolean으로 저장해두었다가 Future.get() 호출 시 채워주는 방법이 있습니다.

추후에 CompletableFuture를 지원하면서 PipedInsertResult와 같은 객체를 따로 사용하지 않을 것이라면 응용의 워커 쓰레드에게 작업을 위임할 수 없습니다.
`CompletableFuture<Map<Integer, CollectionOperationStatus>>` 형태의 API라면 IO 쓰레드의 작업 부담을 줄이기 위해 이러한 작업을 전담할 별도의 Thread Pool이 있어야 할 것 같습니다.
`CompletableFuture<LopPipedInsertResult>` 형태의 API라면 LopPipedInsertResult.get() 호출 시 값을 채워주면 됩니다.

2024-08-21 03:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java
> +        throw new CheckedOperationTimeoutException(duration, unit, elapsed, lastOp);
현재 구현은 사용자가 Future 객체를 받았을 땐 이미 Future 객체내에 ops가 모두 채워진 상태로 보입니다.
lastOp만 TimeoutException 메세지에 포함하면 맞지 않습니다.

2024-08-21 03:22 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java
> +    }
같은 이유로 lastOp의 오류 발생 여부만 확인하면 맞지 않습니다.

2024-08-21 08:23 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                    || rv.hasErrored()
이부분은 Future에 currentOp라는 필드를 두고  setCurrentOp라는 public API를 빼내어 개선할 수도 있긴 합니다. 그렇게 되면 아래에서 TimeoutException에 넣을 Operation도 빠르게 조회할 수 있습니다.

@uhm0311 @jhpark816 setCurrentOp API 추가에 대해서 어떻게 생각하시나요?

2024-08-21 08:30 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                    || rv.hasErrored()
API를 꼭 추가해야 한다면 아래 이슈를 먼저 처리하면 좋겠습니다.
- https://github.com/naver/arcus-java-client/issues/632

이와는 별개로, 지금처럼 `List<Operation>`에 모든 Operation을 넣어둔 채로 시작하지 않고 complete() 콜백 호출 시점에 필요할 때만 넣는 방식도 검토해주세요.

2024-08-22 08:59 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                    || rv.hasErrored()
complete 호출 시점에 새로운 op를 생성하려면 complete 메서드 내부에 op 생성하는 코드를 작성해야 하므로 가독성이 불편해질 것 같습니다.

2024-08-22 09:16 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                    || rv.hasErrored()
Op의 콜백에서 다음 Op를 접근하려면, 미리 Operation들을 future에 저장해두거나 for문을 거꾸로 돌아 생성할 수 밖에 없습니다.
(ArcusClient에서 Op를 만들면서 배열에 저장해두고 콜백에서 다음 Op를 가져오는 것은 불가능합니다.)
근데 for문을 거꾸로 도는 방식이 가독성이 좋지 않다하여 현재대로 변경되었습니다.

2024-08-22 09:29 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                    || rv.hasErrored()
> ArcusClient에서 Op를 만들면서 배열에 저장해두고 콜백에서 다음 Op를 가져오는 것은 불가능합니다.

왜 불가능한가요?
배열을 어디에 만들어두었고 Operation은 언제 넣어두나요?
콜백 내에서는 배열에 어떻게 접근하나요?

2024-08-22 10:59 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                    || rv.hasErrored()
아래와 같이 작성하면 IndexOutOfBoundsException이 발생합니다.
```java
List<Operation> ops = new ArrayList<>();
for (int i = 0; i < insertList.size(); i++) {
  final CollectionPipedInsert<T> insert = insertList.get(i);
  final int idx = i;
  Operation op = opFact.collectionPipedInsert(key, insert, new CollectionPipedInsertOperation.Callback() {
    public void complete() {
      // ...
      Operation nextOp = ops.get(idx + 1);
      rv.addOperation(nextOp);
      addOp(key, nextOp);
    }
    // ...
  });
  ops.add(op);
}
```

2024-08-23 01:10 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                    || rv.hasErrored()
> 아래와 같이 작성하면 IndexOutOfBoundsException이 발생합니다.

1. for문 내에서 addOp() 메소드를 호출하고 있는 것은 아닌가요? complete() 콜백이 반드시 for문이 완료된 후에 호출되는 것을 검증해주세요.
2. `idx + 1 < insertList.size()`를 검증해주세요.

2024-08-23 11:36 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                    || rv.hasErrored()
새로 만든 ops 리스트와 future의 리스트를 헷갈려서 에러가 났던 것 같습니다. 현재는 위 방식으로 수정해두었습니다.

2024-08-26 02:38 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    final List<Operation> ops = new ArrayList<>();
`insertList.size()`를 인자로 줍시다.

2024-08-26 02:38 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          new CollectionPipedInsertOperation.Callback() {
Indent가 너무 깊게 들어가는 것 같습니다.
아래의 형태를 검토해주세요.

```java
Function<Integer, OperationCallback> cb = (i) -> new CollectionPipedInsertOperation.Callback() {
  ...
};

for (int i = 0; i < insertList.size(); i++) {
  Operation op = opFact.collectionPipedInsert(key, insertList.get(i), cb.apply(i));
  ops.add(op);
}
```

2024-08-27 02:19 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          new CollectionPipedInsertOperation.Callback() {
일단 변경해 적용해보긴 했는데, 저에게는 가독성이 둘다 비슷한 것 같습니다.

2024-08-27 02:24 UTC, uhm0311 approved these changes

2024-08-28 04:01 UTC, jhpark816 reviewed
일부 리뷰

2024-08-28 04:20 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        } else if (!rv.getOperationStatus().isSuccess()) {
관련 사항을 좀 더 자세하게 적으면 다음과 같습니다.
- PIPE_ERROR 응답이 온 경우
   - 현재의 piped 연산에서 PIPE_ERROR로 인해 아예 수행되지 item 연산이 있을 수 있습니다.
   - 이 경우, 현재 failed Result에 결과를 담지 않고 있으므로, 이를 추가해야 합니다.
- PIPE_END 응답이 온 경우
   - 개별 연산에 대해 NOT_FOUND, ELEMENT_EXISTS, OVERFLOWED, OUT_OF_RANGE, TYPE_MISMATCH, BKEY_MISMATCH 오류가 발생할 수 있습니다.
   - B+Tree collection에 대해 BKEY_MISMATCH 오류가 발생한 경우, 주어진 element만 insert 실패하고 나머진 성공할 수 있습니다. 이 경우, next 연산을 수행하는 것이 맞지 않는 지 ?  ELEMENT_EXISTS 오류도 비슷해 보입니다.
   - 그 외의 오류인 경우는 캐시 서버에서 수행을 중지하고, PIPE_ERROR 리턴해야 하지 않나 생각합니다.
   - 결국, 캐시 서버 동작 부분도 함께 고려되어야 하지 않나 생각합니다.

2024-08-28 06:39 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                || rv.getOperationStatus().getResponse() == CollectionResponse.CANCELED) {
같은 의미입니다. future의 iscancelled 메서드에서 future의 operationStatus 필드를 기준으로 판별하도록 변경하고, 여기서는 iscancelled 메서드 호출하도록 했습니다.

2024-08-28 07:00 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        } else if (!rv.getOperationStatus().isSuccess()) {
END 응답이 왔고 btree일 때 BKEY_MISMATCH, map, set일 때 ELEMENT_EXISTS만 발생했다면 다음 Operation 보내는 것에는 동의합니다.

PIPE_ERROR가 CLIENT_ERROR, SERVER_ERROR 로 인해 발생했다면 예외가 발생해 failed result를 조회할 수 없습니다. PIPE_ERROR가 command/memory overflow 로 인해 발생했다면 에러를 무시하고 모든 응답을 기준으로 전체 성공/실패 여부만 판별합니다. 따라서 "PIPE_ERROR" 라는 응답이 왔는지 future에서는 확인할 수 없으며, failed result에 결과를 넣을 필요도 없습니다.
https://github.com/naver/arcus-java-client/blob/f60ed483c1d9ad76f5bbcaa1d8f17e1a294d6643/src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java#L139-L148

2024-09-06 04:21 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        } else if (!rv.getOperationStatus().isSuccess()) {
@oliviarla 

기존 pipe 처리에도 일부 문제가 있는 것 같습니다.
- CLIENT_ERROR, SERVER_ERROR 등의 오류가 있는 경우, java client는 PIPE_ERROR 응답까지 읽지 않는다.
  그러면, 다음 연산에서 응답을 읽을 시에 PIPE_ERROR 응답을 보게 되는 문제가 있습니다.
   대략 확인한 사항이라, 이 부분에 관한 코드는 직접 확인해 보기 바랍니다.
- 아래 2가지 PIPE_ERROR에 대해 "END" 응답을 받은 경우와 동일하게 처리합니다.
  즉, 처리하지 못한 연산이 존재하더라도 처리가 완료된 것으로 판단하고 있습니다.
   - PIPE_ERROR command overflow
   - PIPE_ERROR memory overflow

이러한 pipe 처리 오류는 본 PR과는 별도로 처리해야 하죠?
검토 바랍니다.

2024-09-06 05:28 UTC, jhpark816 reviewed
리뷰 완료

2024-09-06 05:28 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +                              false, "CANCELED", CollectionResponse.CANCELED)));
`new CollectionOperationStatus(...)` 2회 호출하는 데, 1회만 호출하면 되지 않나요?

2024-09-06 05:28 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          }
아래와 같이 status는 한번만 생성하여 사용하면 될 것 같습니다.

```java
          CollectionOperationStatus status = new CollectionOperationStatus(
                              false, "CANCELED", CollectionResponse.CANCELED);
          for (int opIdx = idx + 1; opIdx < insertList.size(); opIdx++) {
            int baseIdx = opIdx * CollectionPipedInsert.MAX_PIPED_ITEM_COUNT;
            for (int itemIdx = 0; itemIdx < insertList.get(opdx).getItemCount(); itemIdx++) {
              rv.addEachResult(itemIdx + baseIdx, status);
            }
          }
```

2024-09-06 05:28 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          }
현재 PR에서 구현한 사항은
개별 연산에 대해 NOT_FOUND, ELEMENT_EXISTS, OVERFLOWED, OUT_OF_RANGE, TYPE_MISMATCH, BKEY_MISMATCH 등의 오류가  하나라도 발생하면, 현재 연산에서 수행을 중지하고 다음 연산을 보내지 않는 거죠?

2024-09-06 06:24 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          }
네 맞습니다.

2024-09-06 06:38 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        } else if (!rv.getOperationStatus().isSuccess()) {
CLIENT_ERROR, SERVER_ERROR 등의 오류가 있는 경우, 바로 OperationException이 throw 됩니다.
이 예외를 MemcachedConnection에서 catch하여 연결을 끊기 때문에 다음 연산이 응답을 읽을 수 없을 것으로 보입니다. 

https://github.com/naver/arcus-java-client/blob/45720de1fd98ffe78561c89b5f5cbccbb339be29/src/main/java/net/spy/memcached/MemcachedConnection.java#L948-L952

2024-09-06 06:57 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        } else if (!rv.getOperationStatus().isSuccess()) {
PIPE_ERROR command/memory overflow 오류 시, 처리되지 못한 연산에 대해
본 PR 처럼 CANCELED CollectionOperationStatus 설정하는 것이 좋겠습니다.

2024-09-06 07:01 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          }
뒤에 있는 모든 연산에 대해 CANCELED CollectionOperationStatus 설정하는 방법 대신,
뒤에 있는 첫째 연산에 대해 CANCELED CollectionOperationStatus 설정해 두고,
그 뒤의 연산은 모두 CANCEL된 것이라고 guide 문서에 설명하는 방법은 어떤가요?

참고로, 후자로 표현한 failedResult 만으로도
응용에서 pipe 연산 수행 상태를 정확히 알고 처리할 수 있을 것 같습니다.

2024-09-06 10:22 UTC, oliviarla commented
@jhpark816 리뷰 반영했습니다.

2024-09-09 02:50 UTC, jhpark816 commented
@uhm0311 리뷰 바랍니다.

2024-09-23 03:34 UTC, uhm0311 commented
@oliviarla 

컨플릭트 확인해주세요.

2024-09-23 06:30 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          rv.addEachResult((idx + 1) * CollectionPipedInsert.MAX_PIPED_ITEM_COUNT,
여기 인덱스는 어떤 기준으로 산정한 것인가요?
예시와 함께 설명해주세요.

2024-09-23 08:41 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          rv.addEachResult((idx + 1) * CollectionPipedInsert.MAX_PIPED_ITEM_COUNT,
특정 op에서 NOT FOUND, OVERFLOWED 등의 실패가 발생했을 때, 다음 op의 가장 첫 인덱스에 CANCELED를 매핑해 저장하도록 했습니다.

예를 들어 510개의 값을 리스트에 넣고자했을 때 0~499번째 인덱스에 대해서는 서버에 요청을 보냈으므로 반환값이 오고 여기서 실패한 것만 failedResult에 저장합니다. 500~509번째 인덱스에 대해서는 서버에 요청을 보내지 않으므로 500번째 인덱스에 대해서만 CANCELED 값을 failedResult에 저장합니다.

2024-09-23 09:02 UTC, uhm0311 submitted a review, later dismissed

2024-09-26 06:21 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      // command flow / memory flow
@namsic @uhm0311 
제 생각에는 `PIPE_ERROR memory overflow`일 경우에만 redirect 처리하도록 변경하면 될 것 같은데, 어떻게 생각하시나요?

2024-09-26 06:51 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      // command flow / memory flow
PIPE_ERROR 종류가 무엇인가요?

2024-09-26 07:43 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      // command flow / memory flow
command overflow와 memory overflow일 때 Redirect를 하지 않는 이유와 하는 이유는 무엇인가요?

2024-09-26 07:46 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      // command flow / memory flow
command overflow일 때는 해당 operation으로 생성되는 pipe 명령어의 개수가 동일하기 때문에 redirect하여 똑같은 명령을 보내면 실패하므로 redirect할 필요성이 없어보입니다.
memory overflow일 때는 해당 캐시 노드에 memory 용량이 부족했던 것이기 때문에, 다른 노드로 redirect되었을 때 성공할 가능성이 있으므로 redirect 처리하면 될 것으로 보입니다.

2024-09-26 08:03 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      // command flow / memory flow
궁금한 점이 있습니다.
lop insert로 -1 인덱스에 100개를 추가를 하던 중에 50개를 추가하고 나서 NOT_MY_KEY를 받고 마지막에 PIPE_ERROR memory overflow를 받으면 어떻게 해야 하나요?

2024-09-26 12:22 UTC, namsic commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      // command flow / memory flow
> 왜 그런지 간단히 설명해 주시죠.

코드를 확인해 보니, `NOT_MY_KEY` 발생 이후 invalid command 수신하는 경우에는
`NOT_MY_KEY` + `CLIENT_ERROR` + `PIPE_ERROR bad error` 응답이 가능해 보입니다.

그 외에 정상적인 명령으로 구성된 single key pipe에서는 아래와 같이 동작합니다.

https://github.com/jam2in/arcus-memcached-EE/wiki/Response-format

1. pipe 처리 중 `NOT_MY_KEY` 발생하면 response buffer에 `NOT_MY_KEY` 응답을 추가합니다.
   - 만약 이 응답을 추가하는 과정에서 문제가 생기면, `NOT_MY_KEY` 응답 대신
   `PIPE_ERROR` 응답이 추가되며 pipe 종료하고 클라이언트에게 응답을 돌려줄 것입니다.

2. single key pipe 명령에서 직전 명령이 `NOT_MY_KEY` 발생했으면 현재 명령은 swallow(skip) 처리합니다.
   - 수행하더라도 `NOT_MY_KEY` 발생할 것이기 때문입니다.

3. `NOT_MY_KEY` 1회 발생 이후 모든 명령이 swallow 처리되므로
`PIPE_ERROR`가 발생하는 상황(cmd_ovfl, mem_ovfl, ERROR)이 없고,
마지막 명령까지 swallow 처리된 후 `END`와 함께 클라이언트에게 응답 반환합니다.

2024-10-07 09:54 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      // command flow / memory flow
CLIENT_ERROR 이더라도 PIPE_ERROR까지 읽도록 수정한다면,
PIPE_ERROR이더라도 redirect 수행해야 할 것입니다.
따라서, CLIENT_ERROR 이더라도 PIPE_ERROR까지 읽게 하는 작업을 먼저 진행하는 것이 좋겠습니다.


> command overflow일 때는 해당 operation으로 생성되는 pipe 명령어의 개수가 동일하기 때문에 redirect하여 똑같은 명령을 보내면 실패하므로 redirect할 필요성이 없어보입니다.
memory overflow일 때는 해당 캐시 노드에 memory 용량이 부족했던 것이기 때문에, 다른 노드로 redirect되었을 때 성공할 가능성이 있으므로 redirect 처리하면 될 것으로 보입니다.

위의 내용에 대한 코멘트입니다.
- command overflow에서 redirect하면, 처리되지 않은 연산만 보내므로 해당 연산들은 성공할 수 있습니다.
- memory overflow에서 rediret하는 이유는 일부 연산이 처리되기 전에 해당 key가 다른 node로 이전했기 때문이며, 처리되지 못한 연산만을 이전된 node로 보내어 처리해야 하기 때문입니다.

2024-10-07 10:00 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java
> +    if (!latch.await(duration, unit) && lastOp.getState() != OperationState.COMPLETE) {
`latch.await()` 호출 전에 lastOp 객체를 미리 구해두는 것이 이상합니다.
`latch.await()` 동안에도 새로운 op가 생성되어 등록될 수 있기 때문입니다.

그리고, lastOp가 실제 future에 등록된 마지막 op가 아니라
실제 요청해야 할 마지막 op이어야 하지 않는가요?

2024-10-14 02:23 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      // command flow / memory flow
클라이언트가 정상적으로 동작한다면 command overflow가 발생하지 않을 것입니다. 제 생각에는 command overflow가 발생하면 redirect하지 않고 예외를 발생시켜 문제가 있는 상황임을 알리는 것이 좋을 것 같습니다.

memory overflow에 대해서는 말씀하신 사항에 동의합니다.

2024-10-14 02:38 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java
> +    if (!latch.await(duration, unit) && lastOp.getState() != OperationState.COMPLETE) {
> 그리고, lastOp가 실제 future에 등록된 마지막 op가 아니라
실제 요청해야 할 마지막 op이어야 하지 않는가요?

여러 Op 객체 연산 수행 중 하나의 Op에서 예외나 잘못된 응답이 발생하면 future에 다음 Op를 넣지 않고 latch를 countdown시킵니다.
따라서 future에서는 실제 요청해야 할 마지막 Op를 확인할 필요 없이 실행되었던 가장 마지막 Op만 확인하는 것입니다.

2024-10-14 02:49 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java
> +    return operationStatus.get().getResponse() == CollectionResponse.CANCELED;
사용자가 future.cancel을 호출하거나 내부적으로 op.cancel이 호출되면 BaseOperationImpl의 cancel 메서드가 호출됩니다.
해당 cancel 메서드 내부에서는 wasCancelled 메서드를 호출하게 되는데, 이는 자식 클래스인CollectionPipedInsertOperationImpl에 구현되어 있고, receivedStatus에 의해 future의 상태에 쓰이게 됩니다.
따라서 operationStatus만으로도 cancel 여부를 확인 가능합니다.

https://github.com/naver/arcus-java-client/blob/f60ed483c1d9ad76f5bbcaa1d8f17e1a294d6643/src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java#L95-L107

https://github.com/naver/arcus-java-client/blob/f60ed483c1d9ad76f5bbcaa1d8f17e1a294d6643/src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java#L182-L185

2024-12-05 11:10 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      // command flow / memory flow
@jhpark816 
> CLIENT_ERROR 이더라도 PIPE_ERROR까지 읽도록 수정한다면,
PIPE_ERROR이더라도 redirect 수행해야 할 것입니다.
따라서, CLIENT_ERROR 이더라도 PIPE_ERROR까지 읽게 하는 작업을 먼저 진행하는 것이 좋겠습니다.

이 부분 다시 설명해주실 수 있나요?

2024-12-05 11:34 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      // command flow / memory flow
@oliviarla 
위의 문장은 앞의 문맥을 같이 봐야 하는 데요.
아래와 같이 `NOT_MY_KEY`와 `CLIENT_ERROR`가 함께 존재하는 경우에 대한 얘기입니다.
이 경우, PIPE_ERROR 시에 redirct 해야 하는 경우가 있다는 것이며,
따라서, PR 코드에서 수정한 사항이 원래대로 되돌려져야 한다는 것을 말한 것입니다.
- CLIENT_ERROR이더라도 PIPE_ERROR까지 읽어야 하고,
- PIPE_ERROR 시에도 NOT_MY_KEY 응답이 있었다면 redirect 수행해야 한다는 것입니다.

```
RESPONSE N
xxxx
...
NOT_MY_KEY
CLEINT_ERROR
PIPE_ERROR
```

2024-12-20 12:06 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      // command flow / memory flow
@oliviarla 
Single key에 대한 pipe 연산에 관한 것입니다.
먼저 문제를 단순화하기 위해, SWITCHOVER과 NOT_MY_KEY 응답을 고려하지 않습니다.
이 경우, 치리 동작은 다음과 같습니다.
- PIPE 응답이 END이면
   - 내부 요청이 모두 성공이면, next pipe 연산을 수행합니다. 없으면 종료합니다.
   - 내부 요청이 하나라도 실패하면, next 요청들에 대해 CANCEL 표시하고 종료합니다.
   - `future.get()` 요청에 failed result 응답
- PIPE 응답이 PIPE_ERROR 이면,
   - 현재 pipe 연산을 중지하고, 다음 요청들은 CANCEL 표시하고 종료합니다.
   - reconnect 대상 ERROR이면, 
      - reconnect 처리하고,
      - future.get() 요청 시 exception throw 합니다.
   - reconnect 대상 ERROR가 아니면,
      - future.get() 요청 시, failed result 응답합니다.
   - 참고로, reconect 대상 ERROR이더라도 failed result 응답하도록 수정 필요
      -  이를 위해, PIPE_ERROR까지 읽도록 처리 필요(??)

SWITCHOVER 응답이 있으면 최종 PIPE_ERROR 응답이 오게 됩니다.
이 경우, 클라이언트는 switchover 후에 새로운 master에게 나머지 요청을 보내고,
새로운 master로 부터 응답을 받아 처리합니다. (이 경우는 위의 정상 처리와 동일)

NOT_MY_KEY 응답이 있으면, 
- 대부분의 경우 END 응답이 옵니다.
   - 나머지 요청들을 redirect하여 보내고 응답을 받아 처리합니다. (정상 처리와 동일)
- 아주 희박하게 CLIENT_ERROR 후에 PIPE_ERROR 응답이 올 수 있습니다.
   - 이 경우는 redirect 설정을 clear하고,
   - PIPE_ERROR와 같이 동일하게 처리합시다.

위와 같이 정리하면 될 것으로 보입니다.

2024-12-20 12:08 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      transitionState(OperationState.COMPLETE);
@oliviarla 
Single key에 대한 pipe 연산에 관한 것입니다.
먼저 문제를 단순화하기 위해, SWITCHOVER과 NOT_MY_KEY 응답을 고려하지 않습니다.
이 경우, 치리 동작은 다음과 같습니다.
- PIPE 응답이 END이면
   - 내부 요청이 모두 성공이면, next pipe 연산을 수행합니다. 없으면 종료합니다.
   - 내부 요청이 하나라도 실패하면, next 요청들에 대해 CANCEL 표시하고 종료합니다.
   - `future.get()` 요청에 failed result 응답
- PIPE 응답이 PIPE_ERROR 이면,
   - 현재 pipe 연산을 중지하고, 다음 요청들은 CANCEL 표시하고 종료합니다.
   - reconnect 대상 ERROR이면, 
      - reconnect 처리하고,
      - future.get() 요청 시 exception throw 합니다.
   - reconnect 대상 ERROR가 아니면,
      - future.get() 요청 시, failed result 응답합니다.
   - 참고로, reconect 대상 ERROR이더라도 failed result 응답하도록 수정 필요
      -  이를 위해, PIPE_ERROR까지 읽도록 처리 필요(??)

SWITCHOVER 응답이 있으면 최종 PIPE_ERROR 응답이 오게 됩니다.
이 경우, 클라이언트는 switchover 후에 새로운 master에게 나머지 요청을 보내고,
새로운 master로 부터 응답을 받아 처리합니다. (이 경우는 위의 정상 처리와 동일)

NOT_MY_KEY 응답이 있으면, 
- 대부분의 경우 END 응답이 옵니다.
   - 나머지 요청들을 redirect하여 보내고 응답을 받아 처리합니다. (정상 처리와 동일)
- 아주 희박하게 CLIENT_ERROR 후에 PIPE_ERROR 응답이 올 수 있습니다.
   - 이 경우는 redirect 설정을 clear하고,
   - PIPE_ERROR와 같이 동일하게 처리합시다.

위와 같이 정리하면 될 것으로 보입니다.

2024-12-23 02:12 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      transitionState(OperationState.COMPLETE);
서버쪽에서 NOT_MY_KEY 응답 뒤에 항상 END 응답이 오도록 수정할 계획입니다.
실 구현이 가능할 지는 검토 후에 다시 코멘트 하겠습니다.

2024-12-23 11:56 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      transitionState(OperationState.COMPLETE);
> single key와 multi key를 구분하지 않고 통일된 응답 형식을 갖도록 하면 좋겠습니다.
> 
> single key pipe에서 NOT_FOUND 발생하더라도 다음 명령을 계속해서 처리하고 N번의 중복 응답을 보내는 것처럼,
NOT_MY_KEY 응답 발생하더라도 다음 요청을 swallow 처리하지 않고 계속해서 읽어 처리하는 것이 일관성 있는 동작이라고 생각합니다.

@oliviarla @namsic @uhm0311 
위와 같이 응답을 보내기로 했습니다.
따라서, 기존 single key 시의 redirect 처리 로직이 변경되어야 합니다.

2024-12-31 07:02 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      transitionState(OperationState.COMPLETE);
이부분은 별도 issue에서 처리하도록 하겠습니다.

2025-02-13 02:46 UTC, oliviarla commented
@uhm0311 @jhpark816 
첫 코멘트에 새롭게 구현된 사항을 다시 정리해두었습니다.
리뷰 부탁드립니다.

2025-02-13 08:49 UTC, uhm0311 reviewed
코드를 본지 오래 되어서, 일단 궁금한 부분 먼저 질문합니다.

2025-02-13 08:49 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return syncCollectionPipedInsert(key, Collections.unmodifiableList(insertList));
여기에 Collections.unmodifiableList()가 추가된 이유가 무엇인가요?

2025-02-13 08:49 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        if (opIdx == insertList.size() - 1) {
`opIdx == insertList.size() - 1` 조건과 `!rv.getOperationStatus().isSuccess()` 조건을 동시에 충족하는 경우에는 `rv.addEachResult()`를 할 필요가 없는 건가요?

2025-02-13 08:49 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/SingleKeyPipeOperationImpl.java
> +      cb.setNotExecutedIndex(index);
여기서 index 값을 그대로 넣어주는 이유는 이미 `index++`가 실행되었기 때문인가요?

2025-02-17 02:18 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return syncCollectionPipedInsert(key, Collections.unmodifiableList(insertList));
다른 비슷한 종류의 코드에는 Collections.unmodifiableList()가 없는데, 여기만 추가된 이유가 있나요?

2025-02-17 02:29 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +    return syncCollectionPipedInsert(key, Collections.unmodifiableList(insertList));
코드 수정하다보니 한 부분에만 들어갔는데요, 다른 부분까지 적용하려다보니 나중에 일괄 적용하는게 나을 것 같아 일단 제거했습니다.

2025-02-17 02:55 UTC, uhm0311 reviewed
하나 더 질문입니다.

2025-02-17 02:55 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/SingleKeyPipeOperationImpl.java
> +      } else {
SingleKeyPipeOperationImpl 클래스 특성상 멀티 키에 대한 처리는 없어도 되지 않나요?

2025-02-17 08:55 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/SingleKeyPipeOperationImpl.java
> +      } else {
제거하였습니다.

2025-02-18 06:48 UTC, uhm0311 reviewed
세 번째 질문 남깁니다.

2025-02-18 06:48 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/SingleKeyPipeOperationImpl.java
> +      // single key piped operation when redirection.
지난번에 NOT_MY_KEY 응답이 이제는 1개가 아니고 여러개가 오도록 바뀌었다고 들었습니다.
해당하는 변경 사항은 나중에 반영할 예정인가요?

2025-02-18 08:56 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        }
index가 음수로 주어질 경우에도 정상 동작할 것으로 보입니다.

501개의 값을 -1 인덱스에 추가하고자 한 경우 510개 값이 순차적으로 맨 마지막에 추가되어야 합니다.
따라서 501개 값을 추가할 때 모두 -1 인덱스 위치에 추가해야 하고, 현재 코드는 그렇게 동작하고 있습니다.

2025-02-18 08:56 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/SingleKeyPipeOperationImpl.java
> +      // single key piped operation when redirection.
네, 동기 방식 반영된 후에 별도 PR올릴 예정입니다.

2025-02-18 09:40 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        }
설명을 조금 더 해주었으면 좋겠습니다.
`index += elementList.size();` 라인에 의해 index 값이 변하고 있는데도 항상 -1 위치에 추가하게 되나요?

2025-02-18 10:05 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        }
처음 주어진 index 값이 0 이상인 경우에만 index 값이 변하게 됩니다. 따라서 음수가 주어지면 항상 처음 입력한 index 위치에 추가합니다.

2025-02-18 10:09 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        }
아 그렇네요. if문을 자세히 못봤습니다.

2025-02-20 09:49 UTC, jhpark816 reviewed
일부 리뷰

2025-02-20 09:49 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/SingleKeyPipeOperationImpl.java
> +      cb.setNotExecutedIndex(index);
setNotExecutedIndex() 호출 시에 `index+1`을 넘겨야 하지 않는 지 ?

2025-02-20 09:49 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      }
항상 gotStatus()가 호출되므로, 마지막 gotStatus()에서 넘겨 받은 index를 알게됩니다.
notExecutedIndex는 (마지막으로 넘겨 받은 index + 1)의 값일 것 같습니다.
따라서, setNotExecutedIndex() 메소드를 따로 두지 않아도 될 것 같습니다.

2025-02-24 03:22 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      }
반영했습니다.

2025-02-24 07:27 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        }
@oliviarla 

여기 리뷰 의견은 어떻게 처리되었나요?
- 사전 PR을 반영한 상태?
- 이번 PR에 반영하기로 합의한 상태?
- 기존 코드의 버그가 아니라 이번 PR에 필요한 코드인 것으로 합의한 상태?

2025-02-24 07:32 UTC, jhpark816 reviewed
일부 리뷰

2025-02-24 07:32 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +      }
아래와 같이 success인 경우가 먼저 나오면 좋겠습니다.
```java
        if (rv.getOperationStatus().isSuccess()) {
          if ((opIdx + 1) < ops.size()) {
            // If operations are succeed and next operation exists, then add it.
            Operation nextOp = ops.get(opIdx + 1);
            rv.addOperation(nextOp);
            addOp(key, nextOp);
          } else {
            latch.countDown();
          }
        } else {
          // If this operation has been errored or cancelled,
          // add the command not executed in a operation as not executed state.
          // The remaining operations will be also not executed state but not added into failed result.
          Integer nextIndex = -1;
          if ((lastExecutedIndex + 1) < itemCount) {
             nextIndex =  lastExecutedIndex + 1 + (opIdx * MAX_PIPED_ITEM_COUNT);
          } else if ((opIdx + 1) < ops.size()) {
             nextIndex = (opIdx + 1) * MAX_PIPED_ITEM_COUNT
          }
          if (nextIndex > 0) {
            rv.addEachResult(nextIndex, new CollectionOperationStatus(false, "NOT_EXECUTED",
                                            CollectionResponse.NOT_EXECUTED));
          }
          latch.countDown();
        }
```

2025-02-24 07:32 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java
> +    return ops.get(ops.size() - 1).cancel("by application.");
ops에 3개 op가 있고, 현재 1st op가 수행 중인 상태라고 가정합니다.
이 경우, 아래와 같이 동작하므로 문제가 됩니다.
- 3rd op를 cancel 시키더라도 1st op는 cancel되 상태가 아니므로 계속 수행 될 것입니다.
- operation callback의 complete()는 3rd op가 cancel할 때도 호출되고, 1st op가 완료될 때도 호출됩니다.
   즉, 3rd op가 먼저 complete되고 1st op가 complete 됩니다.

2025-02-24 07:32 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java
> +    return ops.get(ops.size() - 1).hasErrored();
op 수행하다가 중지가 되면, 마지막 op를 수행하지 않을 수도 있습니다.

2025-02-24 07:32 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java
> +      if (lastExecutedOp.getState() != OperationState.COMPLETE) {
마지막 op가 아예 수행되지 않을 수도 있습니다.

2025-02-24 07:33 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +        }
https://github.com/naver/arcus-java-client/pull/881 로 반영되었습니다.

2025-02-24 08:26 UTC, uhm0311 requested changes

2025-02-24 08:26 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/SingleKeyPipeOperationImpl.java
> +    }
여기 return 문이 빠졌습니다.

2025-02-24 08:44 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/SingleKeyPipeOperationImpl.java
> +    }
수정했습니다.

2025-02-24 08:44 UTC, jhpark816 commented on src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java
> +    return ops.get(ops.size() - 1).cancel("by application.");
> Future 객체의 변수로 존재하는 ops 리스트에서는 가장 마지막에 있는 op만 실행중인 상태이고 그 앞에 있는 op들은 정상적으로 실행 완료된 상태입니다. 따라서 ops에 3개 op가 있고, 현재 1st op가 수행 중인 상태라는 가정을 할 수 없습니다.

Future에 등록된 ops이군요. 처음 op 생성할 시의 ops와 혼돈했습니다.

2025-02-25 11:24 UTC, oliviarla commented
- 현재 cancel 처리 과정에서 미흡한 부분이 있어 개선하고자 합니다.

- 아래와 같이 경우의 수를 따져보았을 때 3-3 케이스를 지원하려면 **future에 모든 ops를 담아두고 currentOpIdx를 사용해야 할 것으로 판단되어 변경 작업을 진행**하도록 하겠습니다. (현재는 future에 완료되었거나 실행중인 ops만 담아둡니다. future에 cancel 플래그를 두고 이를 callback에서 활용할 수 있도록 해보려 했으나 3-3 케이스를 구현하려면 매우 복잡해질 것 같습니다.)
- 아래에서 callbacked 변수는 BaseOperationImpl에 존재하는 변수로, Operation이 완료되었는지의 기준이 됩니다.
1. cancel 요청이 `callbacked == false`일 때 들어왔을 경우
    1. 해당 op는 완료되기 전 상태이므로 cancel 가능
2. cancel 요청이 `callbacked == true`이고 `callback.complete()` 수행 직전 들어왔을 경우
    1. 해당 op는 완료된 상태이므로 cancel 불가능
    2. 다음 op를 cancel 시킨 채 future에 넣고, input queue에는 넣지 않는다.
3. cancel 요청이 `callbacked == true`이고 `callback.complete()` 수행 도중 들어왔을 경우
    1. 수행해야 할 op가 남아있는 경우이고 future에 op를 추가하지 않은 상태라면 2번과 같이 처리한다.
    2. 수행해야 할 op가 남아있는 경우이고 future에 op를 추가한 상태라면 1번 상태이므로 다루지 않는다.
    3. 수행해야 할 op가 남아있지 않은 경우 이미 완료된 것이므로 cancel 요청이 실패하였으므로 false 반환해야 한다.

2025-02-26 09:16 UTC, uhm0311 commented
@oliviarla 

코멘트만 봐서는 잘 이해가 되지 않습니다.
오프라인으로 더 자세히 설명해주실 수 있나요?

2025-02-27 05:35 UTC, oliviarla commented
@uhm0311 @jhpark816 
코멘트 내용을 좀더 자세히 수정하였습니다. 검토 부탁드립니다.

2025-02-27 05:57 UTC, uhm0311 commented
기존 PR의 어떤 부분이 어떻게 문제가 되었는지부터가 이해가 안되는 부분이라서, 거기서부터 설명이 필요합니다.
지금 코멘트는 TO-BE에 관한 설명만 있습니다. AS-IS의 문제가 무엇이었는지, 어떠한 이유로 문제였는지부터 천천히 설명해주세요.

> 기존 cancel 처리 과정에서 operation을 complete 처리중일 때 future로부터 cancel을 요청했고 nextOp가 남아있었다면 이를 cancel하는 대신 실패 응답을 보내고 있었습니다.

실패 응답이 무엇인가요?
- cancel() 메소드가 실패했다는 응답?
- 캐시 연산이 실패했다는 응답?
- 다른 기타 응답?

2025-02-27 06:03 UTC, oliviarla commented
@uhm0311 원본 코멘트에 더 자세히 작성했습니다. cancel()메서드가 실패했다는 응답을 의미했습니다.

2025-02-27 08:40 UTC, oliviarla commented
@uhm0311 @jhpark816 
이전 코멘트가 너무 복잡한 방향으로 진행되어 @jhpark816 님의 피드백을 받고 아래와 같이 구상을 변경하였습니다.

### future.cancel()
- op.cancel이 실패하는 경우는 이미 op가 complete 처리되고 있는 경우 뿐이다. 따라서 complete 처리된 op는 스킵하고 다음 op를 cancel 시도한다.
- 현재 수행중인 op부터 순회하며 cancel이 성공하였다면 즉시 성공 응답을 반환하도록 한다.
- cancel된 op가 하나라도 있다면 future는 cancel된 상태이다.

```java
public boolean cancel(boolean ign) {
	for (int i = currentOpIdx; i < ops.size(); i++) {
		if (ops.get(i).cancel("by application.")) {
			return true;
		}
	}
	return false;
}

public boolean isCancelled() {
  for (int i=0;i<ops.size();i++) {
    if (ops.get(i).isCancelled()) {
	    return true;
    }
  }
  return false;
}
```

### callback.complete()
- nextOp를 cancel 시키는 동시에 addOp하는 경우 cancel 상태이면서 input queue에 추가될 수 있으나, write queue에서 제외되므로 문제가 발생하지 않는다.

```java
public void complete() {
  if (rv.getOperationStatus().isSuccess()) {
    Operation nextOp = rv.getNextOp(); // next op가 있다면 op 객체를, 없다면 Null 반환
    if (nextOp != null && !nextOp.isCancelled()) {
      addOp(key, nextOp);
      rv.setCurrentOpIdx(nextOpIdx);
    } else {
      latch.countDown();
    }
  } else {
    // ...
    if (nextIndex > 0) {
      rv.addEachResult(nextIndex,
              new CollectionOperationStatus(false, "NOT_EXECUTED", CollectionResponse.NOT_EXECUTED));
    }
    latch.countDown();
  }
}
```

2025-02-28 05:36 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          }
@oliviarla 
complete()는 cancel 시에도 호출됩니다.
이 경우, `rv.getOperationStatus().isSuccess()`는 false이므로, NOT_EXECUTED 상태를 추가하게 되는 데요.
cancel 시에 NOT_EXECUTED 상태를 추가하는 것이 맞는 지 검토 바랍니다.
아래는 참고 바랍니다.
- lastExecutedIndex는 gotStatus() 호출에서 증가하게 되는 데요.
- cancel 시에  현재의 lastExecutedIndex 기존으로 NOT_EXECUTED 추가하였다가
- 나중에 gotStatus() 호출에 의하여 해당 index의 status를 교체할 수 있게 됩니다.
   즉, NOT_EXECUTED가 제거될 수 있습니다.

2025-02-28 06:26 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          }
> 나중에 gotStatus() 호출에 의하여 해당 index의 status를 교체할 수 있게 됩니다.
즉, NOT_EXECUTED가 제거될 수 있습니다.

이 경우는 발생하지 않을 것 같습니다. gotStatus가 호출되려면 op가 이미 node의 queue에 추가되어 있어야 하는데, NOT_EXECUTED가 추가되는 시점에는 op가 node의 queue에 있을 수 없으므로 gotStatus 역시 호출될 수 없습니다.

2025-02-28 07:34 UTC, oliviarla commented
@uhm0311 @jhpark816 
이제부터 다시 리뷰해주시면 됩니다.

2025-03-04 09:41 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          if (nextCommandIdx > 0) {
nextCommandIdx 값이 0인 경우에는 왜 처리하지 않아도 되는지를 설명하는 주석을 추가해주세요.

2025-03-04 09:41 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          } else if (opIdx + 1 < insertList.size()) {
currentCommandIdx 값이 -1인 경우에 대해서는 따로 처리를 하지 않아도 되나요?

2025-03-06 11:13 UTC, jhpark816 reviewed
리뷰 완료

2025-03-12 02:54 UTC, oliviarla commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          } else if (opIdx + 1 < insertList.size()) {
처리하는 방향으로 수정되었습니다.

2025-03-12 02:54 UTC, oliviarla commented
리뷰 반영했습니다.

2025-03-12 08:11 UTC, jhpark816 reviewed
리뷰 완료

2025-03-12 08:11 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/SingleKeyPipeOperationImpl.java
> +  }
checkStatus() 관한 질문입니다.
추상 메소드를 첫번째의 상속 클래스(SingleKeyPipeOperationImpl)에서 구현하지 않고,
SingleKeyPipeOperationImpl를 상속한 클래스에서 구현하는 것은 가능한가요?

2025-03-12 08:59 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          }
@oliviarla 
Stopped status 추가하는 부분은 다시 검토한 후에 코멘트 남기겠습니다.

2025-03-12 11:47 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ArcusClient.java
> +          }
@oliviarla 
위의 코멘트 수정하였으니, 다시 확인 바랍니다.

2025-03-13 05:23 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java
> +  private int currentOpIdx = -1;
이 값이 -1인 상태에서 일부 함수에서 for 루프를 돌면 IndexOutOfBoundsException이 발생하게 됩니다.
이에 관한 적절한 처리가 필요해 보입니다.

2025-03-13 08:46 UTC, oliviarla commented
@uhm0311 @jhpark816 
현재 Future에 currentOpIdx, 모든 Operation을 담은 List 를 두다보니 해당 값을 callback에서도 사용하고 future에서도 사용하여, 동시성 문제가 발생할 여지가 높아져있습니다. 또한 Future는 값을 기다리는 역할만을 갖는 것이 단순하고 추후 Future를 통합할 때도 유용할 것이라는 생각이 들었습니다.

따라서 Future에 해당 값들을 두지 않고, 기존에 수행했던대로 Future에는 현재 실행중이거나 실행 완료된 Operation만을 담는 List를 갖도록 변경하는 PR을 다시 올리려고 합니다.
구현은 완료된 상태이고, 자체 리뷰 거쳐 내일 다시 PR 올리겠습니다.

2025-04-23 07:46 UTC, closed without merging