INTERNAL: upgrade to ehcache version
naver/arcus-java-client pull request #798
Opened 2024-08-21 08:29 UTC by cheesecrust

### 🔗 Related Issue

- https://github.com/jam2in/arcus-works/issues/600

### ⌨️ What I did

- ehcache version 3 로 업그레이드
- test code 수정
  - ehcache 2 의 경우 TTL, TTI 조건 중 둘 중 하나만 만족시켜도 만료가 되었었는데, ehcache 3 부터는 두 조건을 모두 만족시켜야 만료됩니다.
  따라서 이를 만족시키기 위해 테스트 코드의 sleep time을 변경하였습니다.

2024-08-21 09:42 UTC, uhm0311 requested changes

2024-08-21 09:42 UTC, uhm0311 commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +  }
동시성 제어를 추가합시다.

```java
if (cacheManager != null) {
  return cacheManager;
}

synchronized (CacheManager.class) {
  if (cacheManager == null) {
    cacheManager = CacheManagerBuilder.newCacheManagerBuilder().build(true);
  }
  return cacheManager;
}
```

2024-08-21 09:43 UTC, uhm0311 commented
커밋 메세지 수정해주세요.

`Upgrade to ehcache version => Upgrade ehcache version`

2024-08-22 03:55 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +  }
반영하였습니다.

2024-08-22 05:03 UTC, uhm0311 commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> -                           boolean copyOnWrite) {
copyOnRead, copyOnWrite를 더 이상 사용하지 않게 되었습니다.
Ehcache 3에는 동일한 옵션이 없는 것 같은데, DefaultConnectionFactory 클래스와 ConnectionFactoryBuilder 클래스에 두 필드는 더 이상 사용되지 않는 필드라는 주석을 달도록 합시다.

2024-08-22 06:26 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> -                           boolean copyOnWrite) {
해당 클래스들의 필드 위에 더 이상 사용하지 않는다 /* no longer used */ 라고 주석을 달았습니다.

2024-08-22 07:39 UTC, uhm0311 requested changes

2024-08-22 07:39 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
> +  /* front cache copyOnRead and copyOnWrite is no longer used */
사용되지 않는다는 의미에서 `@Deprecated` 어노테이션도 붙입시다.
두 필드의 값을 설정하는 메소드에도 동일한 주석과 어노테이션을 붙여주세요.
어노테이션을 붙이고 나서 발생하는 컴파일 워닝은 `@SuppressWarnings`로 무시 처리를 하면 됩니다.

2024-08-22 07:39 UTC, uhm0311 commented on src/main/java/net/spy/memcached/DefaultConnectionFactory.java
> +   * copyOnWrite is no longer used
여기와 Getter 메소드에도 같은 어노테이션을 붙여주세요.

2024-08-22 08:14 UTC, cheesecrust commented on src/main/java/net/spy/memcached/DefaultConnectionFactory.java
> +   * copyOnWrite is no longer used
get 메서드와 set 메서드 모두 @Deprecated 하였습니다.

2024-08-22 08:19 UTC, uhm0311 submitted a review, later dismissed

2024-08-22 08:26 UTC, uhm0311 requested changes
테스트 코드 관련 커밋이므로 커밋 메세지 `INTERNAL`을 `TEST`로 바꿔주세요.

2024-08-27 02:35 UTC, oliviarla commented
@cheesecrust 
ehcache2 -> ehcache3 업그레이드하면서 제거된 기능과 추가된 기능을 정리해 what i did 부분을 개선해주세요.

@uhm0311 
왜 커밋 타입이 TEST인가요? 전반적으로 의존성과 인터페이스 자체가 변경되었기 때문에 기존과 같이 INTERNAL로 두어야할 것 같은데요.

2024-08-28 08:35 UTC, cheesecrust commented
> @cheesecrust ehcache2 -> ehcache3 업그레이드하면서 제거된 기능과 추가된 기능을 정리해 what i did 부분을 개선해주세요.

추가하였습니다.

2024-08-29 09:15 UTC, oliviarla commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +      if (tti > 0) {
검증 코드는 제거해도 될 것 같습니다.

이와는 별개로 https://github.com/jam2in/arcus-works/issues/576 이슈에 따라 ConnectionFactoryBuilder의 assert문을 IllegalArgumentException으로 교체하는 것도 생각해보아야 할 것 같습니다.
@jhpark816 @uhm0311 이 점 참고 부탁드립니다.

2024-08-29 09:35 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ConnectionFactory.java
>    int getFrontCacheExpireTime();
getFrontCacheIdleExpireTime() 추가하는 것으로 합시다.

2024-08-30 08:36 UTC, cheesecrust commented on pom.xml
> +                <exclusion>
주석 달았습니다!

2024-09-02 01:31 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +      if (tti > 0) {
위 검증 코드는 맨 처음 tti 의 디폴트 값을 0으로 정해두고 그 값을 사용자가 수정하면 tti 를 적용시킨다는 의미로 두었습니다.
해당 검증 코드를 제거한다면 항상 tti 가 덮어씌워지는 것을 먹기 위해 try catch 문을 활용할 수 있습니다. 해당 방식을 동해 수정할 까요??

2024-09-02 01:33 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +      if (tti > 0) {
```
                .withExpiry(ExpiryPolicyBuilder
                              .timeToLiveExpiration(Duration.of(ttl, ChronoUnit.SECONDS)));
      try {
        configBuilder = configBuilder.withExpiry(ExpiryPolicyBuilder
                .timeToIdleExpiration(Duration.of(tti, ChronoUnit.SECONDS)));
      } catch (Exception ignored) {
        // ignore if the timeToIdle is not supported.
      }
      ```

2024-09-02 02:28 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +  protected Cache<String, Object> cache;
변경해도 문제가 없어 변경하였습니다.

2024-09-02 03:15 UTC, oliviarla commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +      if (tti > 0) {
default tti를 0으로 두는 대신 default ttl과 동일하게 설정해두고 이쪽에서는 검증하지 않도록 하면 될 것 같습니다.

2024-09-02 03:18 UTC, oliviarla commented on pom.xml
> +                <exclusion>
주석 내용이 무슨 의미인가요?

2024-09-02 03:51 UTC, cheesecrust commented on pom.xml
> +                <exclusion>
maven 3.8.1 부터는 의존성에 http repository 가 있는 경우 block 을 시킵니다. 따라서 이를 피하기 위해 exclude 시켰습니다.

2024-09-02 03:53 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +      if (tti > 0) {
ehcache3 의 구현에서는 만료시간을 재는 변수를 ttl 과 tti 설정이 공유합니다. 따라서 뒤에 설정하는 설정으로 덮어씌워지고 ehcache2 의 경우에는 두개중 하나의 조건만 성립하면 만료시킵니다.

2024-09-02 04:41 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +      if (tti > 0) {
따라서 동일하게 설정하고 둘다 적용시키면 항상 tti 만 적용되어 ttl 만을 적용시킬 수 없습니다.

2024-09-02 05:31 UTC, cheesecrust commented on src/main/java/net/spy/memcached/ConnectionFactory.java
>    int getFrontCacheExpireTime();
`getFrontCacheExpireTime();` 메서드를 그대로 쓰고 `getFrontCacheIdleExpireTime();` 을 추가하였습니다.

2024-09-02 05:31 UTC, oliviarla commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +      if (tti > 0) {
이부분은 인터페이스와도 연관이 되어서 @jhpark816 님과 상의해보면 될 것 같습니다.

2024-09-02 05:31 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +  private static CacheManager getCacheManager() {
반영하였습니다.

2024-09-02 06:26 UTC, oliviarla commented on pom.xml
> +                <exclusion>
아래와 같이 주석 달거나 3.9.0 버전 사용하면 굳이 제외시키지 않아도 되는데, 어떻게 하는게 좋을까요? @uhm0311 님도 의견 주세요.

`org.glassfish.jaxb is blocked in maven 3.8.1 as it comes from http (not https) repository. Also, it is not required in java 8 so we excluded it. See https://github.com/ehcache/ehcache3/issues/2881 .`

2024-09-11 01:42 UTC, cheesecrust commented
> TTL, TTI 설정에 관한 ehcache2 vs. ehcache3 차이점을 알고 싶은 데요.
> 
> * ehcache manual에 기술된 내용을 바탕으로 차이점이 있나요?
> * 테스트로 확인한 차이점은 무엇인가요?
> * 그 외의 방법으로 확인한 차이점이 있나요?

테스트로 확인한 차이점을 기술하겠습니다.

```
      CacheConfiguration config =
              new CacheConfiguration(name, max)
                      .copyOnRead(copyOnRead)
                      .copyOnWrite(copyOnWrite)
                      .memoryStoreEvictionPolicy(MemoryStoreEvictionPolicy.LRU)
                      .eternal(false)
                      .timeToLiveSeconds(exptime)
                      .timeToIdleSeconds(exptime)
                      .diskExpiryThreadIntervalSeconds(60)
                      .persistence(new PersistenceConfiguration().strategy(
                          PersistenceConfiguration.Strategy.NONE));
```

```
  protected void setUp() throws Exception {
    super.setUp();
    ConnectionFactoryBuilder cfb = new ConnectionFactoryBuilder();
    cfb.setFrontCacheExpireTime(5);
    ...
  }
  public void testGet() throws Exception {
    for (String k : keys) {
      client.set(k, 2, k + "_value").get();
    }

    String key = keys.get(0);

    Future<Object> f = client.asyncGet(key);
    Object result = f.get();

    Object cached = client.getLocalCacheManager().get(key);

    assertNotNull(result);
    assertNotNull(cached);
    assertSame("not the same result", result, cached);

    // after 3 seconds : remote expired, locally cached
    Thread.sleep(3000);

    f = client.asyncGet(key);
    result = f.get();

    cached = client.getLocalCacheManager().get(key);

    assertNotNull(result);
    assertNotNull(cached);
    assertEquals("not the same result", result, cached);

    // after another 3 seconds : both remote and local expired
    Thread.sleep(3000);

    f = client.asyncGet(key);
    result = f.get();

    cached = client.getLocalCacheManager().get(key);

    assertNull(result);
    assertNull(cached);
  }
```

위는 현재 `develop` 브랜치의 LocalCahceManager 설정과 테스트 코드 입니다. 테스트 코드는 아이템을 생성하고 3초 후에 요청하면 반환을 성공하고 3초를 더 기다린 후에 요청하면 실패하는 테스트 코드 입니다. 따라서 위 처럼 설정을 하면 **TTL 만이 적용**되는것을 알 수 있습니다. TTI 를 적용한다면 최초 3 초를 기다린 후에 요청 하였을때 만료시간이 초기화 되어 마지막 `assertNull` 에서 실패해야 하기 때문입니다. 이는 두 **설정의 순서를 바꿔도 같습니다**. (코드 상에서 ttl 다음에 tti 를 하거나 tti 후에 ttl 을 설정)

이에 따라 설정에서 `.timeToLiveSeconds(exptime)` 를 제거한다면 해당 테스트 코드는 실패 합니다. 마지막 `assertNull(result);` 에서 실패합니다. TTI 만이 설정 되었기 때문입니다.

반면 ehcache3 로 넘어올때 아래 처럼 문법만 바꾸게 되면 TTI 만이 설정되었을 때와 같은 곳에서 실패 합니다. 
```
                    .withExpiry(ExpiryPolicyBuilder
                            .timeToLiveExpiration(Duration.of(exptime, ChronoUnit.SECONDS)))
                    .withExpiry(ExpiryPolicyBuilder
                            .timeToIdleExpiration(Duration.of(exptime, ChronoUnit.SECONDS)));
```
하지만 위 코드에서 두 설정의 **순서를 바꾸면 테스트 코드를 수정하지 않아도 성공**합니다. (TTL, TTI -> TTI, TTL) 그 이유는 ehcache3 에서는 만료 시간을 측정할때 `create`, `access`, `update` 라는 내부 인자를 활용하는데 TTL 과 TTI 모두 같은 곳을 수정하기 때문에 **나중에 설정한 정책이 적용**됩니다. 

따라서 ehcahe2 에서는 TTL 과 TTI 를 모두 적용하게 되면 순서에 상관없이 항상 TTL 이 적용되고 ehcache3 에서는 TTL 과 TTI 를 적용할때 마지막에 적용한 정책이 적용됩니다.

따라서 TTL 만을 적용하려면 ehcache2 처럼 TTI 애도 같은 값을 주는게 아닌 **TTI 설정을 제거하고 TTL 설정만**을 남겨야 할 것 같습니다.

2024-09-11 02:10 UTC, jhpark816 commented
아래 형태로 설정이 가능하나요?

```java
                    .withExpiry(ExpiryPolicyBuilder
                            .timeToLiveExpiration(Duration.of(exptime, ChronoUnit.SECONDS))
                            .timeToIdleExpiration(Duration.of(exptime, ChronoUnit.SECONDS)));
```

2024-09-11 02:11 UTC, jhpark816 commented
@cheesecrust 
그리고, ehcache2와 ehcache3의 manual 설명을 확인하고 알려주세요.

2024-09-11 02:54 UTC, cheesecrust commented
> 아래 형태로 설정이 가능하나요?
> 
> ```java
>                     .withExpiry(ExpiryPolicyBuilder
>                             .timeToLiveExpiration(Duration.of(exptime, ChronoUnit.SECONDS))
>                             .timeToIdleExpiration(Duration.of(exptime, ChronoUnit.SECONDS)));
> ```

위의 형태로는 설정 불가합니다.

ehcache2 manual 에서는
```
         <cache name="myCache"
      maxEntriesLocalDisk="10000" eternal="false" timeToIdleSeconds="3600"
      timeToLiveSeconds="0" memoryStoreEvictionPolicy="LFU">
</cache>
```
위와 같이 ttl 과 tti 를 동시에 설정할 경우 둘 중의 하나의 만료조건이 충족되면 만료된다고 안내하고 있습니다.

ehcache3 doc 에서는 위와 같은 예시를 제시하지 않는데, tti 는 ehcache3 부터 비공식적으로 더 이상 지원하지 않는 개념이라고 합니다.
https://github.com/ehcache/ehcache3/issues/1097

2024-09-11 03:19 UTC, cheesecrust commented on pom.xml
> +                <exclusion>
https://github.com/ehcache/ehcache3/issues/2881
ehcache3 에서 3.9.1 이후 버전 부터는 제외하는것을 추천하고 있는것 같습니다.

2024-09-11 05:36 UTC, jhpark816 commented
@cheesecrust @oliviarla @brido4125 @uhm0311 
- TTI 설정을 제거합시다.
- 다음의 궁금한 부분이 있습니다.
   -  `withExpiry()` 메소드로 Expiry 값을 설정하는 것이며, 2번 나오면 뒤에 설정한 값이 덮어쓰기 하는 것 같습니다.
   -  `withExpiry()` 메소드로 TTL or TTI 중의 하나를 설정하는 것으로 보입니다.
   -  `withExpiry()` 메소드로 TTL과 TTI 모두를 설정하는 방법이 있을까요?
       `withExpiry()` 메소드와 해당 클래스 코드를 보면 확인 가능한지 궁금합니다.

```java
                    .withExpiry(ExpiryPolicyBuilder
                            .timeToIdleExpiration(Duration.of(exptime, ChronoUnit.SECONDS)))
                    .withExpiry(ExpiryPolicyBuilder
                            .timeToLiveExpiration(Duration.of(exptime, ChronoUnit.SECONDS)));
```

2024-09-11 06:14 UTC, cheesecrust commented
@jhpark816 
`.withExpiry()` 메서드의 경우 `ExpiryPolicy()` 를 지정합니다. 그리고 해당 `ExpiryPolicy()` 를 `.timeToLiveExpiration()`, `.timeToIdleExpiration()` 에서 반환합니다. 따라서 `.withExpiry()` 를 할때 마다 새로운 정책을 지정하는것과 같습니다.
따라서 TTL 과 TTI 모두를 설정하는 방법은 없는것으로 보입니다.

2024-09-19 01:14 UTC, jhpark816 commented
ExpiryPolicyBuilder 코드를 보면, TTL과 TTI를 모두 설정할 방법은 있는 것 같습니다. 참고 바랍니다.
https://github.com/tarantool/tarantool-jcache/blob/master/src/main/java/org/tarantool/jsr107/ExpiryPolicyBuilder.java

2024-09-19 01:34 UTC, cheesecrust commented
> ExpiryPolicyBuilder 코드를 보면, TTL과 TTI를 모두 설정할 방법은 있는 것 같습니다. 참고 바랍니다. https://github.com/tarantool/tarantool-jcache/blob/master/src/main/java/org/tarantool/jsr107/ExpiryPolicyBuilder.java
> 
> ARCUS에서는 TTL만 설정하면 될 것 같습니다.

👍 참고하겠습니다.
그리고 현재는 TTL 만 설정하였습니다.

2024-09-19 08:47 UTC, oliviarla commented on pom.xml
> +                <exclusion>
주석을 제가 단 코멘트대로 변경해주세요. 의존성 버전은 그대로 두면 될 것 같습니다.

2024-09-19 09:05 UTC, cheesecrust commented on pom.xml
> +                <exclusion>
주석을 변경하였습니다.

2024-09-20 03:43 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +    this.cache = cacheManager.getCache(name, String.class, Object.class);
@oliviarla 
위 생성자처럼 이름만 받아서 LocalCacheManger 를 만들기 위해서는 디폴트 값이 필요한데, 이를 설정하는것 보다는 위 생성자를 사용하는곳이 없으므로 제거하는건 어떤가요?

2024-09-20 03:46 UTC, oliviarla commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +    this.cache = cacheManager.getCache(name, String.class, Object.class);
제 생각에는 LocalCacheManager 자체를 외부에서 사용하는 일이 거의 없을 것 같아 제거해도 될 것 같습니다.
@jhpark816 제거해도 될까요?

2024-09-23 03:33 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
> +  /* front cache copyOnRead and copyOnWrite is no longer used */
EhCache 2에서 CopyOnRead와 CopyOnWrite의 역할이 정확히 무엇인가요?

2024-09-23 06:23 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
> +  /* front cache copyOnRead and copyOnWrite is no longer used */
그렇다면 `@Deprecated` 처리를 해도 응용의 설정에 따른 동작이 달라지지 않을 것으로 보입니다.
기존에 false로 두고 있었다면 더 정확한 동기화가 이뤄질 것이고, true로 두고 있었다면 변화가 없습니다.
기존 응용에서도 컴파일이 가능하도록 `@Deprecated` 처리를 하는 것이 나을 것 같습니다.

2024-09-23 09:03 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
> +  /* front cache copyOnRead and copyOnWrite is no longer used */
@cheesecrust @oliviarla @uhm0311 
인터페이스로 노출된 부분이 있다면 그 부분만 `@Deprecated` 처리하고
내부적인 처리에서는 관련 필드나 메소드를 제거하는 것이 좋겠습니다.

2024-09-24 01:48 UTC, cheesecrust commented on src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
> +
제거하였습니다.

2024-09-24 01:48 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/FrontCacheMemcachedClient.java
>        // TODO add an additional option
제거하였습니다.

2024-09-24 01:49 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +    this.cache = cacheManager.getCache(name, String.class, Object.class);
@oliviarla 
빈 cacheManager 를 생성후 cache 를 설정하도록 변경하였습니다.

2024-09-24 01:49 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +                            .timeToLiveExpiration(Duration.of(exptime, ChronoUnit.SECONDS)));
반영하였습니다.

2024-09-24 01:51 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +  public Map.Entry<String, Object> getElement(String key) {
`@Deprecate` 하였습니다.
`Element` 클래스는 ehcache3 에서 사라지게 되어 이를 대체하기 위해 `Entry` 사용 후 메서드 명을 getEntry 로 변경하였습니다.

2024-09-24 01:55 UTC, cheesecrust commented on src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
> +  /* front cache copyOnRead and copyOnWrite is no longer used */
`@Deprecated` 처리 한 후 호출 부분은 남기고 내부 구현 부분을 제거하였습니다.

2024-09-24 02:12 UTC, uhm0311 commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +  public Map.Entry<String, Object> getElement(String key) {
LocalCacheManager 클래스도 내부적으로만 사용하는 클래스이지 않나요?
그렇다면 그냥 제거해도 될 것 같습니다.

2024-09-24 09:15 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +  public Map.Entry<String, Object> getElement(String key) {
제거하였습니다.

2024-09-24 10:22 UTC, uhm0311 approved these changes

2024-09-25 07:03 UTC, oliviarla submitted a review, later dismissed

2024-09-25 07:22 UTC, oliviarla commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
>    }
제거해도 될 것 같습니다.

2024-09-25 07:23 UTC, jhpark816 reviewed
리뷰 완료

2024-09-25 07:23 UTC, jhpark816 commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +    this.cache = cacheManager.createCache(name, config);
예전 코드는 CacheManager에서 조회하여 없는 경우에 생성하여 등록하는 형태였지만,
ehcache3에서는 매번 해당 캐시를 생성하는 형태입니다.
이렇게 변경한 이유는 무엇인가요?

2024-09-25 08:03 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
> +    this.cache = cacheManager.createCache(name, config);
@jhpark816 
ehcache2 에서는 기본적으로 `.getInstance()` 메서드를 활용하여 싱글톤으로 관리되는 CacheManager 를 조회한 후 없을 경우에 생성하여 등록하는 형태로 사용되었습니다. 
ehcache3 로 넘어오게 되면서 `.getInstance()` 역할을 하는 메서드가 사라지게 되었습니다.

따라서 싱글톤 방식을 사용하지 않는 것이 자연스럽다고 생각했습니다.
또한 자원을 공유하는 형태가 아니라면 위처럼 구현하는 것이 간단하다고 생각하였습니다.

2024-09-25 08:10 UTC, jhpark816 commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
>    }
@cheesecrust 
아래 생성자는 사용되지 않으므로, 제거하시죠.
```
public LocalCacheManager(String name)
```

2024-09-25 08:16 UTC, cheesecrust commented on src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
>    }
반영하였습니다.

2024-09-25 08:21 UTC, jhpark816 approved these changes

2024-09-25 08:21 UTC, merged