INTERNAL: remove assert or change into IllegalArgumentException
naver/arcus-java-client pull request #834
Opened 2024-10-23 02:20 UTC by oliviarla

### 🔗 Related Issue

- https://github.com/jam2in/arcus-works/issues/576

### ⌨️ What I did

- IllegalArgumentException / Assertions.assertXXX 으로 전환할 수 있거나 assert문을 제거할 수 있는 부분을 고쳤습니다.
- 테스트 코드 변경하면서 불필요한 `throws Exception` 도 함께 제거했습니다.

2024-10-23 05:44 UTC, uhm0311 requested changes
`throws Exception`을 제거하는 변경사항이 본 PR에 필수적이지 않다면 별도의 PR로 반영합시다.

2024-10-23 05:44 UTC, uhm0311 commented on src/main/java/net/spy/memcached/CASMutator.java
> -
assertNotNull()을 호출할 필요는 없을까요?

2024-10-23 05:44 UTC, uhm0311 commented on src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
> +      throw new IllegalArgumentException("timeout exception threshold must be a positive number");
조건과 에러 메세지가 일치하지 않습니다.

2024-10-23 05:44 UTC, uhm0311 commented on src/test/java/net/spy/memcached/ProtocolBaseCase.java
> +      assertEquals(flags, d.getFlags());
어디는 에러 메세지를 유지하고 어디는 제거했습니다.
전부 제거해도 될 것 같습니다.

2024-10-23 05:44 UTC, uhm0311 commented on src/test/java/net/spy/memcached/transcoders/TranscoderUtilsTest.java
> -  void testLongOverflow() {
이 테스트는 왜 사라졌나요?

2024-10-23 06:01 UTC, oliviarla commented on src/test/java/net/spy/memcached/transcoders/TranscoderUtilsTest.java
> -  void testLongOverflow() {
decodeLong에 대해 크기 제한을 두고 있지 않아 현재 테스트도 overflow를 검증하지 못하고 있습니다. (AssertionError가 발생하지 않아 fail()이 호출되지만, 이때 AssertionError를 발생시켜 테스트가 통과함)
추후 decodeLong에 대한 byte[] 크기 제한하는 코드가 추가되면 그때 제대로된 테스트를 추가하는 것이 좋아보입니다.

2024-10-23 06:35 UTC, uhm0311 approved these changes

2024-10-23 08:49 UTC, jhpark816 reviewed
일부 리뷰

2024-10-23 08:49 UTC, jhpark816 commented on src/main/java/net/spy/memcached/collection/SMGetElement.java
> +    }
SMGetElement의 compareXXX() 메소드들은 arcus-java-client 내부 로직에 의해서만 호출됩니다.
이 경우는
- debug 시에 assert 문이 적합해 보이고,
- 실 환경에서 NullPointerException이 발생하여도 충분하다고 보입니다.

2024-10-23 08:49 UTC, jhpark816 commented on src/main/java/net/spy/memcached/collection/Attributes.java
> +    }
아래 메소드에서 setAttribute()가 호출됩니다. 즉, IO thread가 수행합니다.
이 경우에서 exception을 던지면 어떻게 되는가요?

```java
 public CollectionFuture<CollectionAttributes> asyncGetAttr(final String key) {
    final CountDownLatch latch = new CountDownLatch(1);
    final CollectionFuture<CollectionAttributes> rv = new CollectionFuture<>(
            latch, operationTimeout);
    Operation op = opFact.getAttr(key, new GetAttrOperation.Callback() {
      private final CollectionAttributes attrs = new CollectionAttributes();

      public void receivedStatus(OperationStatus status) {
      }

      public void complete() {
      }

      public void gotAttribute(String k, String attr) {
        assert key.equals(k) : "Wrong key returned";
        attrs.setAttribute(attr);
      }
    });
    rv.setOperation(op);
    addOp(key, op);
    return rv;
  }
```

2024-10-24 05:30 UTC, oliviarla commented on src/main/java/net/spy/memcached/collection/Attributes.java
> +    }
- MemcachedConnection의 `catch (Exception e)`부분에 의해 DEFAULT reconnect 됩니다.
- 제 생각에는 이 부분은 내부 동작이므로 IllegalStateException을 발생시키고, IllegalStateException을 catch하여 IMMEDIATE reconnect가 되도록 수정하면 될 것 같습니다.
https://github.com/naver/arcus-java-client/blob/f60ed483c1d9ad76f5bbcaa1d8f17e1a294d6643/src/main/java/net/spy/memcached/MemcachedConnection.java#L938-L963

2024-10-25 03:43 UTC, merged