INTERNAL: read while END/PIPE_ERROR received in the pipe operation
naver/arcus-java-client pull request #839
Opened 2024-11-15 08:47 UTC by oliviarla

### 🔗 Related Issue

- https://github.com/jam2in/arcus-works/issues/616

### ⌨️ What I did

- 본 이슈에서는 두 가지 사항을 처리합니다.
  - proxy 서버에서 하나의 pipe operation에서 여러 error가 발생할 때를 대비하여 operation의 예외 필드를 List로 변경합니다.
  - pipe operation에서 예외가 하나라도 발생했을 때 곧바로 커넥션을 끊는 대신 END|PIPE_ERROR 까지 읽고 예외를 모아 저장해둡니다. 이를 통해 사용자는 get() 메서드 호출 시 발생했던 모든 예외를 CompositeException을 통해 조회해볼 수 있습니다.
  - 만약 모든 response를 읽은 후에 END|PIPE_ERROR 를 읽지 못했다면 버퍼로부터 다음 Line을 읽는 시점에 OperationException을 던져 커넥션을 끊도록 합니다.

2024-11-15 11:17 UTC, jhpark816 commented
@uhm0311 먼저 리뷰하면 됩니다.

2024-11-18 02:51 UTC, uhm0311 reviewed
1차 질문입니다.

2024-11-18 06:26 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> -      transitionState(OperationState.COMPLETE);
pipe 연산의 가장 마지막 부분(500개 연산이 담긴 operation 객체 내부에서 500번째 연산)일 것이라고 잘못 이해했었는데, 다시 생각해보니 501개의 연산이 들어왔을 때 2번째 operation 객체에 1개의 연산만 담기는 경우 위 분기문에 해당하는 것이었네요.
다시 추가했습니다.

2024-11-18 08:12 UTC, uhm0311 reviewed
2차, 리뷰 의견과 질문입니다.

2024-11-18 08:12 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java
> +      transitionState(OperationState.COMPLETE);
같은 로직이 반복적으로 나타납니다.
지금 당장 수정하지 않더라도 별도의 메소드 같은 것으로 빼도록 합시다.

2024-11-18 08:12 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
질문입니다.
- index가 0보다 큰데도 count는 0보다 크지 않은 경우도 있나요?
- count가 0보다 크지 않을 수 있나요?
- index가 0인 경우를 제외하는 이유는 무엇인가요?
  - RESPONSE를 읽은 후에 바로 어떤 에러가 발생하지는 않기 때문인가요?

2024-11-18 08:12 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
> +      if (isPipeOperation() && getException() != null && getState() == OperationState.COMPLETE) {
`getException() != null` 대신 `hasErrored()`로 바꿨을 때 로직적으로 동일하다면 바꾸도록 합시다.

2024-11-18 08:57 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
이 경우는 count 개수 만큼의 응답이 와 index 혹은 index + 예외 개수가 count와 동일해졌을 때를 의미합니다.
따라서 index나 count가 0인 경우는 고려하지 않습니다.

2024-11-18 09:03 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
`(index > 0 && count > 0)` 부분이 꼭 있어야만 하나요?
없으면 어떤 문제가 있나요?

2024-11-18 11:02 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
`(index > 0 && count > 0)` 부분이 없으면 다음과 같은 문제가 생깁니다.

if 분기문에서 line이 `RESPONSE ...` 혹은 `<STATUS>` 임을 검증하기 전에 이 분기가 수행되면, 아직 index와 count값이 설정되지 않아 0인 상태여서 값이 같다고 판단되어 exception 객체가 생성되고 응답 처리가 종료됩니다.

2024-11-18 11:08 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/CompositeException.java
> +  public CompositeException(List<Exception> exceptions) {
해당 내용은 별도 PR로 처리하겠습니다.

2024-11-18 11:11 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java
> +      transitionState(OperationState.COMPLETE);
제 생각에는 로직이 두세줄밖에 없어서 별도 메서드로 빼는 것이 좋을 지 의문입니다.

2024-11-19 01:08 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
Pipe 응답에 RESPONSE 없이 바로 에러가 발생하는 경우도 있는 건가요?

2024-11-19 01:13 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
서버측에서 해당 경우는 발생하지 않을 것입니다.

아래와 같은 경우가 발생하였을 때 `RESPONSE 5`를 읽기 전 모든 응답을 받았고 `END|PIPE_ERROR`가 아님을 검증하여 에러를 던지기 위해 추가되었습니다.
```bash
RESPONSE 3
STORED
STORED
CLIENT_ERROR # 가장 마지막에 PIPE_ERROR가 나와야 하지만 나오지 않았고 바로 다음 Operation의 응답이 온다.
RESPONSE 5
STORED
...
```

2024-11-19 01:26 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
RESPONSE 5를 읽기 전의 상태는 count = 3, index = 2 아닌가요?
즉, count가 0이 되지 않습니다.
그런데도 `count > 0` 조건이 있어야 하나요?

2024-11-19 01:40 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
`(index > 0 && index == count) || (count > 0 && index + getExceptions().size() == count)` 로 표현할 수도 있습니다.

RESPONSE가 0 이상이고 모든 응답이 `CLIENT_ERROR|SERVER_ERROR`라면 index가 0이 되므로 `count > 0` 조건이 있긴 해야 합니다.

2024-11-19 01:42 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
RESPONSE가 0일 수도 있다는 의미죠?

2024-11-19 02:04 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
서버 측에서 0이 올 수 없을 것 입니다.

`count > 0` 으로 검사하는 이유는, 최초로 온 응답의 첫번째 라인을 읽을 때 Operation 객체 내부의 index, getExceptions().size(), count 필드 값들이 모두 0(초기값)이므로 `index + getExceptions().size() == count` 기준으로 검사 시 true가 나오는 것을 방지하기 위함입니다.

더 직관적으로 작성할 수 있다면 의견 부탁드립니다.

2024-11-19 02:27 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
If문의 순서를 아래로 내리면 count를 검사하지 않아도 되지 않나요?
그러면 항상 RESPONSE를 먼저 읽는다는 것이 보장이 될 것입니다.

2024-11-19 02:29 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
그렇게되면 만약 아래와 같이 pipe 연산에 대한 응답이 연달아왔을 때 `END|PIPE_ERROR`가 오지 않았다는 것을 검증하지 못하게 됩니다.
```
RESPONSE 3 # 첫번째 pipe연산
STORED
STORED
CLIENT_ERROR # 가장 마지막에 PIPE_ERROR가 나와야 하지만 나오지 않았고 바로 다음 Operation의 응답이 온다.
RESPONSE 5 # 두번째 pipe 연산
STORED
...
```

2024-11-19 02:44 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
제안하신 방법대로라면 `CLIENT_ERROR` 응답 직후 `RESPONSE 5` 라인이 올 때 RESPONSE 검증에 의해 읽혀지면서 Operation 객체에 대한 count 값이 변경되게 됩니다. 따라서 `END|PIPE_ERROR` 가 오지 않았지만 이를 처리할 수 없게 됩니다.
```java
// 현재
if (/*END|PIPE_ERROR 검증*/) {
} else if (/*count만큼 읽었는지 검증*/) {
} else if (/*RESPONSE 검증*/) {
} ...

// 제안하신 방법
if (/*END|PIPE_ERROR 검증*/) {
} else if (/*RESPONSE 검증*/) {
} else if (/*count만큼 읽었는지 검증*/) {
  // 여기에 도달하지 못함
} ...
```

2024-11-19 02:50 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
그러면 궁금한 점이, `index++;` 아래로 If문을 옮기면 어떻게 되나요?

2024-11-19 04:45 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
아래와 같은 형태를 이야기하시는 건가요? 이렇게 하더라도 `(index > 0 && index == count) || (count > 0 && index + getExceptions().size() == count)` 조건문을 사용해 count만큼 읽었는지 검증해야 할 것 같습니다.
```java
if (/*END|PIPE_ERROR 검증*/) {
} else if(/* STATUS 검증 */) {
} else if (/*count만큼 읽었는지 검증*/) {
} else if (/*RESPONSE 검증*/) {
}
```

2024-11-19 04:47 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
아래와 같은 형태를 의미하는 것입니다.

```java
if (/*END|PIPE_ERROR 검증*/) {
} else if (/*RESPONSE 검증*/) {
} else {
  /* STATUS 검증 */
  index++;

  if (/*count만큼 읽었는지 검증*/) {
  }
}
```

2024-11-19 04:51 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
위와 같이 작성하면 `END|PIPE_ERROR` 응답이 왔는지 여부를 판별할 수가 없습니다.

pipe 연산 응답의 가장 마지막 `<STATUS>` 또는 `CLIENT_ERROR|SERVER_ERROR` 다음에 오는 응답을 읽어 판별해야 하기 때문입니다.

2024-11-19 04:59 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
이해했습니다.
아래의 조건으로 충분하지 않나요?

`count > 0 && index + getExceptions().size() >= count`

2024-11-19 06:48 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +            (index == count || index + getExceptions().size() == count)) {
반영했습니다.

2024-11-19 07:10 UTC, uhm0311 requested changes
3차 리뷰 의견입니다.

2024-11-19 07:10 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
> +        throw getException();
현재 구현 상 getException()은 가장 처음에 받은 Exception입니다.
CompositeException으로 감싸서 모두 전파하려는 의도가 아닌가요?
CompositeException으로 감싸려는 의도라면 getException()의 구현이 아래와 같이 변경되어야 할 것 같습니다.
- exceptions.isEmpty() : return null
- exceptions.size() == 1 : return exceptions.get(0)
- else : return new CompositeException(exceptions)

2024-11-19 07:19 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
> +        throw getException();
여기서 예외를 던지는 이유는 사용자에게 전파하는 것이 아니라, MemcachedConnection의 I/O thread에서 이 예외를 catch하여 서버와 reconnect하기 위함입니다.

말씀하신대로 모든 예외를 감싼 예외를 던져야 정확한 reconnect 원인을 로그로 남길 수 있을 것 같습니다.

현재 CompositeException은 ExecutionException(아마 사용자에게 실행 중 오류가 발생했음을 알리기 위한 타입 같음)을 상속받고 있고, 내부적으로 MemcachedConnection에서 catch하기 위해서는 OperationException(내부적으로 오류가 발생했음을 알리기 위한 타입) 타입을 상속받아야 적절할 것 같은데 어떻게 하는게 좋을까요?

2024-11-19 07:23 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
> +        throw getException();
CompositeException은 릴리즈가 아직 되지 않았죠?
CompositeException이 OperationException을 상속받도록 만들고, 사용자가 Future.get()에서 CompositeException을 전파받아야 하는 상황에선 CompositeException을 ExecutionException으로 감싸서 전파하면 어떤가요?

2024-11-19 08:01 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
> +        throw getException();
좋은 방법 같습니다. 수정하겠습니다.

2024-11-19 08:41 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
> +        throw getException();
그럼 CompositeException 클래스에 대한 변경만 따로 PR로 먼저 반영하도록 합시다.

2024-11-25 07:06 UTC, jhpark816 commented
@oliviarla @uhm0311 
CompositeException의 printCallStack() 관련 PR은 merge 되었습니다.

2024-11-26 10:41 UTC, oliviarla commented
@uhm0311 @jhpark816 
현재 END/PIPE_ERROR가 오지 않아 예외가 발생한다면 아래와 같이 로깅이 되는데요, 이 때 어떤 에러가 어떤 연산에서 났는지 확인하기 어렵다는 단점이 있긴 합니다만, 별다른 해결 방안은 없는 것 같습니다. (pipe operation에서 내부적으로 사용하고 있는 index 정보를 같이 로깅하면 어떨까 생각해보았는데, 메서드 인자 등을 로그로 알기 어려우므로 index를 알더라도 쓸모없는 정보가 될 것 같습니다.)
```
OperationException: SERVER: Multiple exceptions (3) reported: SERVER_ERROR out of memory @ testnode 0.0.0.0/0.0.0.0:11211, CLIENT_ERROR too large value @ testnode 0.0.0.0/0.0.0.0:11211, END|PIPE_ERROR not received
```

2024-11-28 01:42 UTC, uhm0311 reviewed
4차 리뷰 의견입니다.

2024-11-28 01:42 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
> +              new CompositeException(new ArrayList<>(getExceptions())).getMessage());
getExceptions()를 ArrayList로 다시 감싸고 있는데, 감싸지 않으면 어떤 문제가 있나요?

2024-11-28 01:42 UTC, uhm0311 commented on src/test/java/net/spy/memcached/protocol/ascii/BaseOpTest.java
> +    assertThrows(OperationException.class, () -> op.readFromBuffer(b));
OperationException의 cause가 CompositeException인 것도 검증해야 할 것 같습니다.
CompositeException 내에 어떤 메세지가 있는지는 검증하지 않아도 됩니다.

2024-11-28 02:14 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
> +              new CompositeException(new ArrayList<>(getExceptions())).getMessage());
CompositeException 생성자에서는 현재 List<Exception>를 입력받고 있고, OperationImpl에서는 List<OperationException>를 필드로 관리하고 있어, List<OperationException>을 새로운 ArrayList로 감싸주어 List<Exception>로 변환하고 있습니다.

지금 형태로 사용하거나 CompositeException 생성자에서 OperationException 리스트를 입력하도록 할 수 있는데 어떤게 좋을까요?

2024-11-28 02:21 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
> +              new CompositeException(new ArrayList<>(getExceptions())).getMessage());
생성자의 리스트 타입을 `List<? extends Exception>`로 변경하면 어떤가요?

2024-11-28 02:53 UTC, oliviarla commented on src/test/java/net/spy/memcached/protocol/ascii/BaseOpTest.java
> +    assertThrows(OperationException.class, () -> op.readFromBuffer(b));
현재 OperationException에 cause 객체를 입력하고 있지 않아, 메시지만 검증이 가능합니다. 어떻게 할까요?

2024-11-28 02:56 UTC, uhm0311 commented on src/test/java/net/spy/memcached/protocol/ascii/BaseOpTest.java
> +    assertThrows(OperationException.class, () -> op.readFromBuffer(b));
CompositeException 객체 자체를 넣어주는 것이 아니고 메세지만 전달하는 것이었군요.
그러면 ExceptionMessageFactory.createCompositeMessage() 메소드를 호출해도 되지 않나요?

2024-11-28 03:11 UTC, oliviarla commented on src/test/java/net/spy/memcached/protocol/ascii/BaseOpTest.java
> +    assertThrows(OperationException.class, () -> op.readFromBuffer(b));
수정했습니다!

2024-11-28 04:08 UTC, uhm0311 approved these changes

2024-11-28 10:34 UTC, oliviarla commented
@jhpark816 리뷰 부탁드립니다.

2024-11-28 11:18 UTC, jhpark816 reviewed
일부 리뷰

2024-11-28 11:18 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +    }
`handleError()`에서 pipe 연산의 결과를 확인하는 것이 어색합니다.

OperationReadType이 현재 LINE, DATA만 존재합니다.
pipe 연산과 같이 multi line을 읽는 경우를 고려하여, LINE, NEXT, DATA로 확장하고, 아래와 같이 처리해야 하지 않나 생각합니다.
- LINE
   - readLineFromBuffer
   - Error 확인 후에 handleError() 또는 handleLine() 호출
- NEXT (LINE)
   - readLineFromBuffer
   - 무조건 handleLine() 호출
- DATA
   - 무조건 handleData() 호출

추가적으로, 5개의 연산을 pipelining 처리하는 데, 
ascii protocol error로 5회 CLIENT_ERROR가 리턴되는 경우는 어떻게 처리해야 할 지?

2024-11-28 12:33 UTC, jhpark816 reviewed
리뷰 완료,
복잡한 이슈네요.

2024-11-28 12:33 UTC, jhpark816 commented on src/main/java/net/spy/memcached/ops/Operation.java
> +  List<OperationException> getExceptions();
Operation에는 하나의 Exception만 있으면 될 것 같습니다.

proxy 서버에 pipe 연산을 요청하는 경우에는
그 결과에 CLIENT_ERROR 등이 존재하더라도 PIPE_ERROR가 아닌 END 응답이 와야 할 것 같고,
이 경우는 Error가 없는 것으로 처리해야 할 것 같습니다.

2024-11-28 12:33 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java
> +      transitionState(OperationState.COMPLETE);
아래와 같이 exception만 throw하면 되지 않는 지 ?

````
    } else if (index >= count) {
      // If END|PIPE_ERROR not received after reading all responses,
      // then throw exception to reconnect.
      throw OperationException(OperationErrorType.SERVER, "END|PIPE_ERROR not received");
```

2024-11-28 23:50 UTC, oliviarla commented on src/main/java/net/spy/memcached/ops/Operation.java
> +  List<OperationException> getExceptions();
이부분에 대해서는 @namsic 님과 함께 https://github.com/jam2in/arcus-works/issues/616 이슈에서 조금 더 논의하는게 좋아보입니다.

2024-11-28 23:52 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java
> +      transitionState(OperationState.COMPLETE);
handleLine은 OperationImpl 클래스의 추상 메서드를 구현하고 있으며, 이 메서드 시그니처에는 `throws OperationException` 이 포함되어 있지 않아 여기서 예외를 던지려면 모든 handleLine 메서드 정의를 수정해주어야 합니다.

2024-11-29 01:46 UTC, namsic commented on src/main/java/net/spy/memcached/ops/Operation.java
> +  List<OperationException> getExceptions();
> - https://github.com/jam2in/arcus-go/issues/93#issuecomment-2428089347
> 클라이언트에서는 프록시에 pipe 요청을 보내 응답을 받은 경우, server_error나 client_error가 있는 line을 읽은 후 바로 예외를 던지지 않고 PIPE_ERROR 혹은 END까지 읽은 후에 예외를 던지도록 구현할 것 같습니다.
어떤 문자를 반환하더라도 구현에 문제는 없을 것 같지만, 프로토콜 의미 상 ERROR가 하나라도 발생해있다면 PIPE_ERROR를 반환하는 것이 이해하기 쉬울 것 같습니다.

위 코멘트에서도 일부 논의했던 부분입니다.

2024-12-05 11:17 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +    }
@jhpark816 @uhm0311 
- 말씀하신 두 가지 요구사항 (1. 연산의 중간 쯤 `CLIENT_ERROR, SERVER_ERROR, ERROR` 응답이 오더라도 해당 응답 전OUT_OF_RANGE 등 삽입이 실패했는지 성공했는지 확인할 수 있어야 한다. 2. `END|PIPE_ERROR` 까지 읽어 redirect 가능하도록 한다.) 을 만족하려면 다음 방법대로 해야 할 것 같습니다.
  - `CLIENT_ERROR, SERVER_ERROR, ERROR` 응답이 오더라도 handleError 메서드가 아닌 handleLine 메서드에서 `NOT_FOUND, TYPE_MISMATCH, ...`와 같이 처리하는 대신 errored 플래그를 추가해 true로 설정합니다.
  - index 값이 count와 동일하거나 errored 플래그가 있을 때 `END|PIPE_ERROR`를 읽지 못했다면 protocol exception을 발생시킵니다. 이 exception은 내부에서 reconnect 하기 위한 용도로만 던져지며 사용자에게 알리려면 `NOT_FOUND, TYPE_MISMATCH, ...`와 같이 처리해야 합니다.

2024-12-05 12:10 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +    }
@oliviarla 
위 내용에서 아래 사항만 변경하면 될 것 같습니다.
```
index 값이 count와 동일하거나 errored 플래그가 있을 때 END|PIPE_ERROR를 읽지 못했다면 
=>
index 값이 count와 동일할 때 END|PIPE_ERROR를 읽지 못했거나 errored 플래그가 있을 때
```

2024-12-06 00:43 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +    }
그렇다면 "index 값이 count와 동일할 때 `END`를 읽지 못했을 때" 만 체크하면 될 것 같습니다.
index와 count가 동일하다면 모든 원소의 응답이 제대로 온 것이므로 PIPE_ERROR인지는 확인할 필요가 없습니다.

2024-12-06 01:25 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +    }
@oliviarla 
count 값이 pipelining으로 보낸 요청 수를 의미하나요?
아니면 pipelining 응답의 첫째 라인에 있는 count를 의미하나요?

만약 후자라면,
pipelining으로 10개 요청을 보내더라도 아래 응답이 올 수 있습니다.
- count : 5
- 마지막 문자열: PIPE_ERROR

2024-12-06 03:00 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +    }
후자를 의미합니다. 결국 여기서는 서버에서 보낸 값 만큼 응답을 읽었는지를 검증하게 됩니다.

RESPONSE count 값이 5이고 index(정상 응답)가 4이고 그 다음 SERVER_ERROR가 왔다면 errored 플래그가 true이므로 PIPE_ERROR가 왔는지 확인해야 할 것이고,
RESPONSE count 값이 5이고 index(정상 응답)가 5일 때 END가 왔는지 확인해야 할 것입니다.

2024-12-09 08:30 UTC, oliviarla commented
@jhpark816 @uhm0311 
현재 상황에서 수정할 부분을 대략 정리해봤습니다. 코드로 작성하기 전에 검토 먼저 부탁드립니다.
- `OperationImpl#readFromBuffer`의 로직 변경
  - isPipeOperation()가 true이면 classifyError()를 거치지 않고 handleLine()에서 CLIENT_ERROR, SERVER_ERROR, ERROR를 gotStatus 콜백 메서드에 넘긴다.
- `handleLine(String line)`의 로직 변경
  - `END`가 오면 리다이렉트한 후 Operation COMPLETE 상태로 변경
  - `PIPE_ERROR`가 오면 리다이렉트한 후 Operation COMPLETE 상태로 변경 , operation에 예외를 추가해 reconnect되고 hasErrored가 true를 반환하도록 한다.
- `get()`의 로직 변경
  - hasErrored 일 때에는 exception을 던지지 않는다.

2024-12-09 09:00 UTC, jhpark816 commented
@oliviarla 
> isPipeOperation()가 true이면 classifyError()를 거치지 않고 handleLine()에서 CLIENT_ERROR, SERVER_ERROR, ERROR를 gotStatus 콜백 메서드에 넘긴다.

- pipe 요청에 대해 `ERROR` 등이 바로 나올 수 있으며, 이 경우는 classifyError()를 수행해야 합니다.
- pipe 요청에 대해 `RESPONSE <count>\r\n` 응답이 온 이후에는 classifyError()를 거치지 않아야 합니다.

> END가 오면 리다이렉트한 후 Operation COMPLETE 상태로 변경
> PIPE_ERROR가 오면 리다이렉트한 후 Operation COMPLETE 상태로 변경 

리다이렉트한다는 것이 어떤 의미인가요?

> future.get()의 로직 변경
> hasErrored 일 때에는 exception을 던지지 않는다.

result가 있는 지에 따라 판단해야 할 지 ?  정도의 느낌이 듭니다.

2024-12-09 10:24 UTC, oliviarla commented
@jhpark816 
윗 코멘트를 수정했습니다.

2024-12-09 11:35 UTC, jhpark816 commented
> hasErrored로 인한 exception은 던지지 않는다. cancel에 대한 exception은 던진다. (이 때에는 어디까지 처리되었는지 여부는 알 수 없다.)

- exception, cancel, timeout 관련 처리는 동일해야 할 것 같습니다.
- `future.get()` 동작을 아래와 같이 수정하는 방안이 있습니다.
   - error, cancel, timeout 시에 exception throw 하지 않는 방식이 있습니다.
   - 이 경우, error, cacncel, timeout을 OperationStatus로 리턴해야 합니다.
- `future.get()` 동작을 그대로 유지하는 대신, `getSome()` 같은 별도의 메소드를 두는 방식이 있습니다.
   - `getSome()`은 error, cacncel, timeout을 OperationStatus로 리턴합니다.
   - `getSome()`은 getBulk에서 제공하는 메소드이고, storeBulk에 맞는 용어를 가진 메소드이어야 합니다.

2024-12-10 07:11 UTC, uhm0311 commented
> END가 왔을 때에는 Operation COMPLETE 상태로 변경

현재와 동일한 동작이란 거죠?

2024-12-16 06:32 UTC, oliviarla commented
@uhm0311 
> 현재와 동일한 동작이란 거죠?

네 맞습니다.

> getFailedResult() 메서드를 pipe 관련 Future에 추가 -> 해당 메소드의 리턴 타입은 어떻게 되나요?

failedResult 필드 타입과 동일하게 반환할 예정입니다.

---
@jhpark816 @uhm0311 
- 현재 failedResult과 관련 없이 일단 END|PIPE_ERROR까지 읽도록만 수정해두었습니다. (handleError에서 바로 throw하지 않도록 변경)
- failedResult는 다른 PR로 수정할 예정이며, 아마 PIPE 동기 방식 PR 이후에 적용해도 될 것 같습니다.
- handleLine, handleRead 일관성 문제는 https://github.com/jam2in/arcus-works/issues/659 이슈에서 별도로 다룰 예정입니다.

2024-12-18 01:37 UTC, jhpark816 reviewed
리뷰 완료

2024-12-18 01:37 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +    }
아래 경우도 있기 때문에 위의 변경은 적합하지 않습니다.
- 1개 연산으로 구성된 pipe 연산일 수 있습니다.
   이 경우, COMPLETE 처리하고 exception을 던져야 합니다.
- N개 연산으로 구성된 pipe 연산인 경우이더라도
   첫째 연산에서 ERROR가 발생할 수 있습니다.
   이 경우도 COMPLETE 처리가 필요할 것으로 보입니다.
   서버 쪽의 동작은 서버 담당 멤버에게 문의해 보세요.

2024-12-18 01:37 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
> +          }
readFromBuffer() 로직을 수정하지 않고,
pipe 연산의 로직을 수정하는 형태로 고려해 보니, 대략 아래와 같이 구현할 수 있을 것 같습니다.
검토해 보기 바랍니다.

```java
  private void handleState(String line)
  {
    /* ENABLE_REPLICATION if */
    if (hasSwitchedOver(line)) {
      this.insert.setNextOpIndex(index);
      receivedMoveOperations(line);
      return;
    }
    /* ENABLE_REPLICATION end */

    /* ENABLE_MIGRATION if */
    if (hasNotMyKey(line)) {
      // Only one NOT_MY_KEY is provided in response of single key piped operation when redirection.
      addRedirectSingleKeyOperation(line, key);
      if (insert.isNotPiped()) {
        transitionState(OperationState.REDIRECT);
      } else {
        insert.setNextOpIndex(index);
      }
      return;
    }
    /* ENABLE_MIGRATION end */

    if (insert.isNotPiped()) {
      OperationStatus status = matchStatus(line, STORED, CREATED_STORED,
              NOT_FOUND, ELEMENT_EXISTS, OVERFLOWED, OUT_OF_RANGE,
              TYPE_MISMATCH, BKEY_MISMATCH);
      if (status.isSuccess()) {
        cb.receivedStatus((successAll) ? END : FAILED_END);
      } else {
        cb.gotStatus(index, status);
        cb.receivedStatus(FAILED_END);
      }
      transitionState(OperationState.COMPLETE);
      return;
    }

    if (line.startsWith("END") || line.startsWith("PIPE_ERROR ")) {
      /* ENABLE_MIGRATION if */
      if (needRedirect()) {
        transitionState(OperationState.REDIRECT);
        return;
      }
      /* ENABLE_MIGRATION end */
      cb.receivedStatus((successAll) ? END : FAILED_END);
      transitionState(OperationState.COMPLETE);
      if (hasErrored()) {
        throw getException();
      }
    } eles {
      OperationStatus status = matchStatus(line, STORED, CREATED_STORED,
              NOT_FOUND, ELEMENT_EXISTS, OVERFLOWED, OUT_OF_RANGE,
              TYPE_MISMATCH, BKEY_MISMATCH);

      if (!status.isSuccess()) {
        cb.gotStatus(index, status);
        successAll = false;
      }
      index++;
    }
  }

  @Override
  public void handleLine(String line) {
    assert getState() == OperationState.READING
            : "Read ``" + line + "'' when in " + getState() + " state";
    /*
      RESPONSE <count>\r\n
      <status of the 1st pipelined command>\r\n
      [ ... ]
      <status of the last pipelined command>\r\n
      END|PIPE_ERROR <error_string>\r\n
    */
    if (line.startsWith("RESPONSE ")) {
      getLogger().debug("Got line %s", line);

      // TODO server should be fixed
      line = line.replace("   ", " ");
      line = line.replace("  ", " ");

      String[] stuff = line.split(" ");
      count = Integer.parseInt(stuff[1]);

      setReadType(OperationReadType.DATA);
    } else {
      handleState(line);
    }
  }

  @Override
  public void handleRead(ByteBuffer bb) {
    String line = getLineFromBuffer(bb);
    if (line != null) {
      OperationErrorType eType = classifyError(line);
      if (eType != null) {
        exception = new OperationException(eType, line + " @ " + handlingNode.getNodeName());
      }
      handleState(line);
    }
  }
```

2024-12-20 05:43 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
> +          }
이전에도 말씀드렸듯이, OperationException은 checked exception이므로 handleLine 내부에서 던져질 경우 반드시 `throws OperationException` 을 메서드 시그니처에 추가해주어야 합니다.

pipe 연산에서만 OperationException이 던져지는 상황에서 모든 Operation 구현체의 handleLine 메서드 시그니처를 변경하는 것은 바람직하지 않습니다.
따라서 OperationState가 COMPLETE이면서 hasErrored 상태일 때 예외를 던지는 것은 readFromBuffer 내부에서만 수행 가능합니다.

2024-12-20 05:49 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +    }
CollectionPipedInsertOperationImpl 등 파이프 관련 Operation 클래스의 isPipeOperation() 메서드에서 1개 연산 요청만 존재한다면 false를 반환하도록 변경하면 어떤가요?

실제로 pipe 연산을 보내는 것이 아닌데 isPipeOperation() 메서드에서 true를 반환하는 것도 이상한 것 같습니다.

2024-12-20 05:59 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +    }
@oliviarla
`isPipeOperation()` 메소드의 사용 의도를 확인 후에 그 의도가 문제 없다면 변경할 수 있을 것입니다.
예를 들어, 단순히 pipe API를 호출했는 지를 판단하기 위해 isPipeOperation() 사용되었다면,
단순히 변경하는 것이 맞지 않게 됩니다.

2024-12-20 07:59 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +    }
future에서 timeout 발생한 operation들에 대한 타임아웃 메시지를 만들기 위해 가장 첫 timeout operation에 대해서만 isPipeOperation 메서드가 사용되고 있습니다.

따라서, 단일 키 pipe 연산의 경우 윗 코멘트대로 변경해도 달라지는 것이 없습니다.

여러 키 pipe 연산의 경우(asyncXopInsertBulk만 해당) 윗 코멘트대로 변경하면 에러 메시지가 `bulk pipe LOP_INSERT operation timed out (.. >= 1 MILLISECONDS)` -> `bulk LOP_INSERT operation timed out (5 >= 1 MILLISECONDS)` 로 변경될 가능성이 있지만 문제는 없어보입니다.

2024-12-23 01:29 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
> +          }
아래 형태이면 어떤가요?
```
handleError -> throw exception + complete
handleLine -> response 읽은 후에는 OperationReadType.DATA로 변경하여 handleRead로 이동
handleRead -> error이면 exception 저장, status이면 receivedStatus 호출, end | pipe_error 이면 complete

readFromBuffer -> pipe 연산이고 exception 존재하고 complete 상태이면 throw excedtion
```

2024-12-23 01:42 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
> +          }
@oliviarla 
위에 적은 형태가 좋은 것 같습니다.

2024-12-24 06:20 UTC, oliviarla commented
@jhpark816 
일단 CollectionPipedInsertOperationImpl 만 수정해두었습니다. 해당 클래스에 대한 리뷰가 끝나면 CollectionPipedUpdateOperationImpl, CollectionPipedExistOperationImpl, CollectionBulkInsertOperationImpl 클래스에 동일하게 적용하겠습니다.

2024-12-24 06:28 UTC, jhpark816 commented
@uhm0311 리뷰 바랍니다.

2024-12-27 02:43 UTC, uhm0311 reviewed
변경 내역을 다 따라가지 못해서 질문 남깁니다.

2024-12-27 02:43 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +          this.exception = createException(eType, line);
예외 객체를 하나만 두는 것으로 의견이 바뀌었나요?

2024-12-27 02:43 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +          if (insert.isNotPiped()) {
여기에서 이 조건이 true일 수 있나요?

2024-12-27 02:57 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +          this.exception = createException(eType, line);
네, 일단은 proxy가 아닌 서버를 기준으로 PR 변경했습니다.

2024-12-27 04:36 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +          if (insert.isNotPiped()) {
검사하지 않도록 수정했습니다.

2024-12-27 05:09 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +          this.exception = createException(eType, line);
그러면 첫번째 코멘트의 PR 설명도 현재를 기준으로 업데이트 해주세요.

2024-12-27 07:55 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +          this.exception = createException(eType, line);
새로 업데이트해두었습니다.

2024-12-27 08:12 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +          throws OperationException {
이 메소드에서 여전히 에러가 발생하면 바로 전파하고 있습니다.
에러 발생 시에 어떤 원리로 PIPE_ERROR를 읽을 수 있게 되나요?

2024-12-27 08:12 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +        if (eType != null) {
PIPE_ERROR를 읽기 전까지 에러의 개수가 2개 이상이고, 서로 다른 에러일 가능성은 고려하지 않는 것인가요?

2024-12-27 08:54 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +        if (eType != null) {
네 현재는 그렇습니다.

2024-12-27 08:54 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +          throws OperationException {
handleError는 가장 첫 라인에 에러 발생 시에만 호출되어 전파되게 됩니다.
RESPONSE <count> 이후에 에러 발생 시 handleRead 를 계속 읽게 되는데, 이 때에는 exception 필드에 예외 객체를 저장만 해두다가 COMPLETE 상태가 되면 readFromBuffer 메서드에서 던져집니다.

2024-12-30 02:12 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +          throws OperationException {
중간에 에러가 발생하면 PIPE_ERROR를 받지 못할 수 있는 것은 서버 코드를 수정하여 더 이상 해당 사항이 없어졌나요?

2024-12-30 02:19 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +          throws OperationException {
서버에서 중간에 에러가 발생했을 때 PIPE_ERROR를 보내지 않는 상황을 이야기하시는 건가요?? 혹시 관련 코멘트 링크 첨부해주실 수 있나요? 기억이 안나서요...

2024-12-30 02:25 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +          throws OperationException {
> 서버에서 중간에 에러가 발생했을 때 PIPE_ERROR를 보내지 않는 상황을 이야기하시는 건가요??

맞습니다.
이 PR의 최초 변경분에서는 이러한 상황을 대비하기 위해 count 개수 만큼 읽어보고 END|PIP_ERROR가 오지 않으면 별도의 Exception을 생성하는 로직이 있었습니다.
첫번째 코멘트에도 처음에는 이러한 상황을 염두했다고 적혀져 있었으니 첫번째 코멘트의 수정 내역을 한 번 살펴보세요.

2024-12-30 02:29 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +          throws OperationException {
아, `END|PIPE_ERROR`가 오지 않는 경우는 별도 예외 처리를 하지 않기로 했습니다.

다른 모든 연산들에 대해서도 END가 오지 않는 경우를 처리하지 않고 있기 때문에, 나중에 `END|PIPE_ERROR`가 오지 않는 경우에 대해 처리가 필요하다고 판단되면 그때 일괄 처리하는 것이 좋아보입니다.

2025-01-02 05:26 UTC, oliviarla commented
@uhm0311 리뷰 완료되셨을까요?

2025-01-02 05:28 UTC, uhm0311 commented
@oliviarla 

진행 중입니다.

2025-01-02 06:02 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +        } else {
return이 있으면 else가 없어도 되지 않나요?

2025-01-02 07:11 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +        } else {
199라인까지 while문 내부이기 때문에, return 해주지 않으면 byte buffer로부터 다음 라인을 읽게 됩니다.

2025-01-02 07:26 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +        } else {
return이 있으니까 else는 없어도 되지 않나요?

2025-01-02 07:47 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +        } else {
수정했습니다.

2025-01-02 08:05 UTC, uhm0311 approved these changes

2025-01-04 11:56 UTC, jhpark816 reviewed
리뷰 완료

2025-01-06 06:56 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +        return;
handleError를 오버라이드하는 형태로 구현해봤습니다.
이를 통해 공통 Operation 처리 코드 중 readFromBuffer 쪽만 수정하도록 변경되었습니다.

2025-01-06 09:19 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +    if (count == 0 && index == 0) {
RESPONSE 응답을 받지 못한 경우에만 에러를 전파한다고 이해하면 되나요?
그리고 이 경우로 한정하는 이유는 PIPE_ERROR를 읽기 위함인가요?

2025-01-06 09:19 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +  }
```java
if (count == 0 && index == 0) {
  super.handleError(eType, line);
}
```

이 메소드의 구현을 위와 같이 3줄만으로 변경하면 의도하지 않게 동작하나요?

2025-01-06 12:42 UTC, jhpark816 reviewed
리뷰 완료

2025-01-06 12:42 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
> +      if (hasErrored() && isPipeOperation() && getState() == OperationState.COMPLETE) {
if 조건 순서를 아래와 같이 하는 것이 어떤 지 ?
```java
if (isPipeOperation() && getState() == OperationState.COMPLETE && hasErrored())
```

2025-01-06 12:42 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +    if (count == 0 && index == 0) {
CollectionPipedInsertOperationImpl 클래스에서
명시적으로 index를 0으로 초기화해 두는 것처럼
명시적으로 count도 0으로 초기화해 두면 좋겠습니다.

그리고, `count == 0` 조건만 있어야 하고, `index == 0` 조건은 빠져야 합니다.
아래 경우에 `index == 0`이기 때문입니다.

```
RESPONSE 1
CLIENT_ERROR ...
PIPE_ERROR
```

그리고, switchover와 redirect하는 경우를 고려한다면,
`count == 0` 조건만 있으면 충분한 지 간단히 설명해 주세요.

2025-01-07 10:52 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +    if (count == 0 && index == 0) {
switchover / redirect하는 경우 count 값이 초기화되도록 수정했습니다. (count 값은 현재 사용하고 있지 않기 때문에 최신 `RESPONSE <count>` 정보를 저장해두는 용도로만 사용해도 됩니다.)

2025-01-07 10:52 UTC, oliviarla commented
리뷰 모두 반영했습니다.

2025-01-08 02:38 UTC, uhm0311 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> -      return;
여기 return은 있어야 하지 않나요?

2025-01-08 02:41 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> -      return;
수정했습니다.

2025-01-08 03:03 UTC, uhm0311 submitted a review, later dismissed

2025-01-08 06:04 UTC, jhpark816 reviewed
리뷰 완료

2025-01-08 06:04 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +import static net.spy.memcached.ops.OperationErrorType.CLIENT;
질문입니다.
- `import static`에서 static은 어떤 의미가 되나요?
- 기존 코드에서도 CLIENT가 사용되고 있습니다. 이미 관련된 import가 존재하지 않는 지 ?

2025-01-08 06:04 UTC, jhpark816 commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      count = 0;
switchover 경우를 예로 들면,
이미 일부가 수행된 상태에서 나머지를 switchover한 후에 수행하면,
그 이후의 결과는 `원소` 결과로 처리해야 할 것 같습니다.

NOT_MY_KEY 경우도 함께 검토 바랍니다.

2025-01-08 08:24 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
> +      count = 0;
switchover, redirect 후 새로운 별도 요청을 보낸 후 응답을 받았을 때, `RESPONSE`가 올 수도 있고 하나의 라인이 올 수도 있습니다.
RESPONSE가 왔을 때에만 예외를 던지지 않도록 하여 PIPE_ERROR를 읽도록 합니다.

2025-01-08 08:30 UTC, oliviarla commented on src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
> +import static net.spy.memcached.ops.OperationErrorType.CLIENT;
static import를 하게 되면 해당 변수나 상수를 사용할 때 정의된 클래스 이름을 명시하지 않고 사용할 수 있습니다.
예를 들어 일반 import 시에는 `OperationErrorType.CLIENT`로 사용해야 하지만, static import 시에는 `CLIENT`로 사용할 수 있는데, 기존에는 switch문을 사용해서 static import할 필요가 없었습니다.

다만 `CLIENT`만 사용하는 것보단 `OperationErrorType.CLIENT` 사용하는 것이 더 이해가 쉬울 것 같아 static import를 제거했습니다.

2025-01-09 05:29 UTC, oliviarla commented
@jhpark816 
count 대신 readUntilLastLine 플래그를 두도록 변경하고 주석도 추가했습니다.

2025-01-09 08:43 UTC, merged