INTERNAL: stacktrace all exceptions
naver/arcus-java-client pull request #840
Opened 2024-11-20 10:48 UTC by oliviarla

### 🔗 Related Issue

- https://github.com/naver/arcus-java-client/pull/839#discussion_r1846040585

### ⌨️ What I did

- CompositeException 객체의 printStackTrace() 메서드를 통해 예외에 대한 스택을 확인할 때, 아래와 같이 각각의 예외들에 대한 stacktrace가 찍히도록 합니다.
- 구현은 https://github.com/ReactiveX/RxJava/blob/3.x/src/main/java/io/reactivex/rxjava3/exceptions/CompositeException.java 과 동일하게 했는데, 라이센스를 추가해야 할 것 같습니다.
```
net.spy.memcached.internal.CompositeException: Multiple exceptions (3) reported: msg1, msg2, msg3
	at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
        ...
Caused by: net.spy.memcached.internal.CompositeException$ExceptionOverview: Multiple exceptions (3)
|-- net.spy.memcached.ops.OperationException: msg1
    at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:17)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    ...
|-- net.spy.memcached.ops.OperationException: msg2
    at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:18)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
|-- net.spy.memcached.ops.OperationException: msg3
    at net.spy.memcached.internal.CompositeExceptionTest.throwError2(CompositeExceptionTest.java:34)
    at net.spy.memcached.internal.CompositeExceptionTest.throwError1(CompositeExceptionTest.java:31)
    at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:19)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
```

2024-11-20 10:58 UTC, uhm0311 commented
아래와 같이 단순하게 하면 어떻게 되나요?

```java
@Override
public synchronized Throwable getCause() {
  return !exceptions.isEmpty() ? exceptions.get(0) : null;
}

@Override
public StackTraceElement[] getStackTrace() {
  return exceptions.stream().map(Throwable::getStackTrace).flatMap(Arrays::stream).toArray(StackTraceElement[]::new);
}

@Override
public void printStackTrace(PrintStream s) {
  exceptions.forEach((e) -> e.printStackTrace(s));
}

@Override
public void printStackTrace(PrintWriter s) {
  exceptions.forEach((e) -> e.printStackTrace(s));
}
```

2024-11-20 12:43 UTC, jhpark816 commented
@oliviarla 
기존에는 stacktrace가 어떻게 출력되었나요?

2024-11-21 02:09 UTC, oliviarla commented
@uhm0311
아래와 같이 스택트레이스가 찍히게 됩니다. 현재 구현과 다른 점은 getCause() 메서드 호출 시에 반환되는 Throwable에 전체 예외에 대한 메시지를 담을지 말지 입니다. 저는 getCause 메서드 호출 시에 전체 예외에 대한 메시지가 담긴 throwable을 반환하는 것이 더 좋을 것 같습니다.
```
OperationException: msg1
    at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:17)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    ...
OperationException: msg2
    at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:18)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    ...
OperationException: msg3
    at net.spy.memcached.internal.CompositeExceptionTest.throwError2(CompositeExceptionTest.java:34)
    at net.spy.memcached.internal.CompositeExceptionTest.throwError1(CompositeExceptionTest.java:31)
    at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:19)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    ...
```

@jhpark816 

기존에는 내부에 담긴 Exception들의 스택트레이스가 없이 CompositeException 자체의 스택트레이스만 반환되었습니다.
```
net.spy.memcached.internal.CompositeException: Multiple exceptions (3) reported: msg1, msg2, msg3
	at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
        ...
```

2024-11-21 03:50 UTC, uhm0311 requested changes

2024-11-21 03:50 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CompositeException.java
> +  public synchronized Throwable getCause() {
https://github.com/naver/arcus-java-client/pull/840#issuecomment-2488267899 구현을 적용한 다음, 이 메소드 구현을 단순하게 가져갑시다.
- cause != null인 경우 cause 반환
- exceptions.size() == 1인 경우 첫번째 원소 반환
- 둘 다 아닌 경우 모든 메세지 종합하여 반환
  - `this.printStackTrace(new StringWriter())`를 이용해 문자열로 만들고 그 문자열을 Message로 하는 Exception 객체 생성하여 cause 필드로 대입

2024-11-21 05:29 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/CompositeException.java
> +  public synchronized Throwable getCause() {
`printStackTrace()` 메서드에는 PrintWriter, PrintStream 타입만 입력 가능하여 StringWriter를 인자로 넣을 수 없습니다.
모든 에러에 대한 스택트레이스를 합친 문자열을 만드려면 이 PR에서 한 방식처럼 모두 순회하여 직접 생성하는 수밖에 없을 것 같습니다.

2024-11-21 05:32 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CompositeException.java
> +  public synchronized Throwable getCause() {
`new PrintWriter(new StringWriter())`를 쓰면 됩니다.

2024-11-21 07:54 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/CompositeException.java
> +  public synchronized Throwable getCause() {
반영했습니다.

ExceptionOverview를 사용한 이유는, getCause에서 RuntimeException이나 Exception, Throwable 객체를 반환할 경우 해당 래핑하는 예외에 대한 스택트레이스까지 함께 반환되어 이를 없애기 위함입니다.

```
net.spy.memcached.internal.CompositeException: Multiple exceptions (3) reported: msg1, msg2, msg3
	at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:21)
...
Caused by: java.lang.Throwable: 
OperationException: SERVER: msg1
	at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
        ...
OperationException: CLIENT: msg2
	at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
        ...
OperationException: SERVER: msg3
	at net.spy.memcached.internal.CompositeExceptionTest.throwError2(CompositeExceptionTest.java:42)
	at net.spy.memcached.internal.CompositeExceptionTest.throwError1(CompositeExceptionTest.java:38)
	at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:19)
        ...

        // 아래 부분이 추가됨
	at net.spy.memcached.internal.CompositeException.<init>(CompositeException.java:30)
	... 71 more
```

2024-11-21 08:11 UTC, uhm0311 reviewed
2차, 질문입니다.

2024-11-21 08:11 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CompositeException.java
> +      }
여러 스택 트레이스를 나눠서 저장하고 있군요.
하나의 PrintWriter 객체만 사용하고, 반복문이 종료된 다음에 한 번만 sb.append(sw)를 하면 어떤 문제가 있나요?

2024-11-21 08:11 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CompositeException.java
> +  public synchronized Throwable getCause() {
다른 메소드들은 구현이 되어 있지 않은데, 구현하지 않아도 다음의 2가지 모두 스택 트레이스가 잘 출력되나요?
- e.printStackTrace()
- logger.error(..., e) (log4j 등을 사용)

2024-11-21 08:27 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/CompositeException.java
> +  public synchronized Throwable getCause() {
스택트레이스를 확인해볼 수 있는 메서드를 loggerTest에 추가했습니다.
내부적으로 printStackTrace를 사용하기 때문에 둘 모두 아래 정보들이 출력됩니다. (로거 사용할 경우 타임스탬프+로깅레벨 함께 출력됨)
```
net.spy.memcached.internal.CompositeException: Multiple exceptions (3) reported: msg1, msg2, msg3
	at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:21)
...
Caused by: java.lang.Throwable: 
OperationException: SERVER: msg1
	at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
        ...
OperationException: CLIENT: msg2
	at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
        ...
OperationException: SERVER: msg3
	at net.spy.memcached.internal.CompositeExceptionTest.throwError2(CompositeExceptionTest.java:42)
	at net.spy.memcached.internal.CompositeExceptionTest.throwError1(CompositeExceptionTest.java:38)
	at net.spy.memcached.internal.CompositeExceptionTest.printStackTraceOfAllExceptions(CompositeExceptionTest.java:19)
        ...
```

2024-11-21 08:27 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/CompositeException.java
> +      }
한 번만 사용하도록 변경했습니다.

2024-11-21 08:39 UTC, oliviarla commented on src/main/java/net/spy/memcached/internal/CompositeException.java
> +      }
StringBuilder 없이 pw만 사용하도록 변경했습니다.

2024-11-21 08:57 UTC, uhm0311 requested changes
3차 리뷰 의견입니다.

2024-11-21 08:57 UTC, uhm0311 commented on src/test/java/net/spy/memcached/compat/log/LoggingTest.java
> +    logger.error("failed to get", new CompositeException(exceptions));
이 로거는 자바 클라이언트 내부에 구현된 로거를 사용할 것입니다.
log4j 의존성은 이미 포함되어 있으니 log4j의 로거도 한 번 사용해봅시다.

2024-11-21 08:57 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CompositeException.java
> +    if (exceptions.size() > 1) {
사이에 Empty Line 추가

2024-11-21 08:57 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CompositeException.java
> +      try (PrintWriter pw = new PrintWriter(sw)) {
사이에 Empty Line 추가

2024-11-21 08:57 UTC, uhm0311 commented on src/main/java/net/spy/memcached/internal/CompositeException.java
>      this.exceptions.addAll(exceptions);
사이에 Empty Line 추가

2024-11-21 08:57 UTC, uhm0311 commented on src/test/java/net/spy/memcached/internal/CompositeExceptionTest.java
> +  @Test
사이에 Empty Line이 많습니다.

2024-11-21 10:52 UTC, uhm0311 approved these changes

2024-11-25 04:31 UTC, merged