FIX: Duplicated switchover event.
naver/arcus-java-client pull request #850
Opened 2024-12-10 06:04 UTC by brido4125

### 🔗 Related Issue

- https://github.com/jam2in/arcus-works/issues/638

### ⌨️ What I did

findChangedGroups 로직에서 swichover의 old 형상으로 되돌리는 문제를 해결했습니다.
로직은 대략 아래와 같이 구현되어있습니다.

1. 검사하려는 node의 그룹이 alreadySwitched인지 확인
2. master / slave 여부를 제외한 groupname, ip, port 정보들 중 변경 있는지 확인
3. master / slave 여부가 old 형상으로 되돌려졌는지 확인
4. flag 원복

우선 리뷰를 위해 한글로 주석을 달아두었습니다.
추후 리뷰 완료되면 제거 또는 영어로 변경할 예정입니다.

2024-12-10 06:33 UTC, uhm0311 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +        if (removed == null) {
조건이 잘못된 것 같습니다.
하나의 그룹 내에서 Master/Slave 역할을 제외한 캐시 노드의 구성이 변화가 전혀 없으면 반영하지 않는 것입니다.
`Map<String, InetSocketAddress>` 타입보단 아래 타입 중 하나가 맞는 것 같습니다.
- `Map<String, List<String>>`
- `Map<String, List<ArcusReplNodeAddress>>`
- `Map<String, List<...>>`

위 타입 후보 모두 Key는 그룹 이름입니다.

2024-12-10 08:42 UTC, brido4125 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +                  .orElse(null);
zk로부터 받아온 캐시 리스트에서 복제그룹 내에 master가 있다는게 보장되면 null이 발생되지 않습니다.
다만, 캐시 서버가 znode에 변경을 가할 때 이를 검증하는지는 아직 살펴보지 않았습니다.
알아보고 나서 의견 올리겠습니다. (혹시 아신다면 말씀해주세요)

이 외 사항들은 리뷰 부탁드립니다.

2024-12-10 09:06 UTC, brido4125 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +                  .orElse(null);
@uhm0311 

수정 끝나면 리뷰 요청 다시 노티드릴게요

2024-12-10 12:21 UTC, uhm0311 requested changes

2024-12-10 12:21 UTC, uhm0311 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +                  .collect(Collectors.toSet());
여기 Set 생성할 때 그룹 이름도 들어가야 합니다.
희박한 확률이지만 아래와 같은 경우를 처리하기 위함입니다.
- 노드 구성에는 변경이 없이 그룹이름만 변경됨
- 변경된 그룹 이름이 기존에도 존재하던 다른 그룹임

예를 들면 아래와 같은 캐시 클러스터가 있습니다.
- g001 : A, B
- g002 : C, D

아래와 같은 작업이 Switchover 작업과 함께 일어나는 경우를 상정하고자 하는 것입니다.
- g001에 새로운 노드 E, F를 추가 (g001 : A, B, E, F / g002 : C, D)
- 기존 g001에 있던 노드 A, B를 g002로 이동 (g001 : E, F / g002 : A, B, C, D)
- 기존 g002에 있던 노드 C, D를 제거 (g001 : E, F / g002 : A, B)

2024-12-10 12:21 UTC, uhm0311 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +                  oldRepl.containsAll(newRepl) && newRepl.containsAll(oldRepl)) {
`oldRepl.equals(newRepl)`로 간단하게 사용 가능한가요?

2024-12-10 12:21 UTC, uhm0311 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +                    .orElse(null);
여기서 `orElse(null)`을 호출하면 아직 `ArcusReplNodeAddress.validateGroup()` 호출 전이라서 정말 null이 할당될 수 있습니다.
그러니 이 아래 if문에서 null 처리가 필요합니다.

2024-12-10 12:21 UTC, uhm0311 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +    Map<String, List<ArcusReplNodeAddress>> groupMap = new HashMap<>();
비슷한 변수명이 자주 사용되어서 코드를 이해하기 어렵습니다.
메모리에 있는 기존 형상이면 old를 붙이고, ZK로 받은 형상이면 new를 붙이도록 합시다.

2024-12-11 02:38 UTC, uhm0311 submitted a review, later dismissed

2024-12-12 02:55 UTC, jhpark816 commented
@oliviarla @namsic 
본 PR에 대해 추가 리뷰어를 지정합니다.

2024-12-13 03:13 UTC, oliviarla commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +          changedGroupSet.add(oldGroup.getGroupName());
이부분은 `if (oldGroup.isAlreadySwitched())`에 대응되는 else 문에서 실행해야 할 것 같습니다.
이부분이 실행되려면 `!oldGroup.isAlreadySwitched()` 이거나 `changedGroupSet.add(oldGroup.getGroupName());`가 실행된 이후여야 하기 때문입니다.

2024-12-13 03:13 UTC, oliviarla commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +        }
현재 코드에서 아래 부분이 반영되어 있나요?
```
switchover 수행된 2개 캐시 노드 중 하나라도 존재하지 않으면,
현재 znodes 상태를 그대로 반영
alreadySwitched 플래그를 false로 설정
```

2024-12-13 07:36 UTC, uhm0311 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +        }
Indent가 더 들어가지 않도록 아래와 같은 형태로 합시다.

```java
if (oldGroup.isAlreadySwitched()) {
  ...
  continue;
}

List<ArcusReplNodeAddress> addrList = oldGroup.getArcusReplNodeAddressList();
...
```

아니면 상대적으로 짧은 부분을 if문 내로 넣는 것도 좋습니다.

```java
if (!oldGroup.isAlreadySwitched()) {
  List<ArcusReplNodeAddress> addrList = oldGroup.getArcusReplNodeAddressList();
  ...
  continue;
}

...
```

위 둘 중 더 읽기 편한 형태로 바꿔주세요.

2024-12-13 07:42 UTC, brido4125 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +        }
리뷰 반영하였습니다.

"alreadySwitched 플래그를 false로 설정"을 추가하였습니다.
의도하신 동작이 맞는지 확인부탁드려요

2024-12-13 07:42 UTC, brido4125 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +        }
스타일 문제는 어차피 @jhpark816 님 의견에 
맞출 예정이라 그 때 수정하겠습니다.

2024-12-13 07:56 UTC, oliviarla commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +                .map(addr -> addr.getIPPort() + addr.getGroupName())
`oldGroup.getGroupName()`으로 얻은 이름을 통해 새로운 그룹을 조회하므로 groupName은 newRepl set이든 oldRepl set이든 항상 동일합니다.
GroupName 말고 Role을 추가해야 하지 않나요?

2024-12-13 07:56 UTC, oliviarla commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +        }
415~416 라인이 수행되려면 alreadySwitched 이면서 해당 복제 그룹의 1. 노드 개수가 추가/감소했거나 2. 노드 개수는 같지만 구성하는 주소가 달라져야만 하는거죠?
위 상황마다 switchover를 어떻게 처리해야 하는지 설명해주시면 좋겠습니다.

2024-12-16 02:33 UTC, brido4125 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +                .map(addr -> addr.getIPPort() + addr.getGroupName())
newGroupMap에서 oldGroupName이 key로 없는 경우
기존에 groupName 구성에서 새로운 groupName 구성으로 변경이 생긴것을 의미합니다.

위와 같은 로직으로 groupName의 변경 감지 로직을 수정하였습니다.

2024-12-16 03:09 UTC, namsic reviewed
1. switchover 수행
   - `SWITCHOVER` 또는 `REPL_SLAVE` 응답 수신하여 `AlreadySwitched` 설정
2. 1에 대한 ZK event를 수신하지 못한 상태에서 switchover 재수행
   - master와 slave가 기존 상태로 원복
3. 이후 ZK event 수신하여 cache_list 조회해 보면 (클라이언트 입장에서) old 형상과 동일

위와 같은 시나리오에서 `alreadySwitched` flag가 언제 초기화되나요?

2024-12-16 03:25 UTC, brido4125 commented
> 1에 대한 ZK event를 수신하지 못한 상태에서 switchover 재수행

운영자가 switchover를 한번 더 수행하는 상황을 가정한건가요?

2024-12-16 03:38 UTC, namsic commented
> 운영자가 switchover를 한번 더 수행하는 상황을 가정한건가요?

기본적으로 그렇습니다.
또는 서버 내부 설계/구현 방향에 따라 switchover에 문제가 있다고 판단한 경우 자체적으로 원복시킬 수도 있을텐데,
수행하는 주체가 누구인지에 따라 동작이 달라지나요?

2024-12-16 03:58 UTC, brido4125 commented
우선 제 의견은 위 상황에 대해 고려하지 않아도 된다고 생각합니다.

1. 운영자가 직접 `1차 switchover <---> 1차 swtichover zk 이벤트 발생` 사이에 한번 더 switchover 명령을 실행할 확률은 극히 드물다고 생각됨
2. 자동화된 스크립트를 통해 swtichover를 수행한다해도 1차 switchover 이후 해당 동작이 완료되고 나서, 이상이 있을 경우 원복 로직을 구현하는것이 일반적이고 예상 가능한 형태라고 생각됨

2024-12-16 05:10 UTC, namsic commented
> - 운영자가 직접 1차 switchover <---> 1차 swtichover zk 이벤트 발생 사이에 한번 더 switchover 명령을 실행할 확률은 극히 드물다고 생각됨

- 극단적인 시나리오를 예시로 들고 있기는 하지만, 발생 확률이 낮으니 고려하지 않아도 된다는 논리는 적절하지 않아 보입니다.
- 당장 본 PR만 하더라도 실제 운영 환경에서 발생할 가능성이 아주 낮은 경우를 상정하여 처리하고 있습니다.

> - 자동화된 스크립트를 통해 swtichover를 수행한다해도 1차 switchover 이후 해당 동작이 완료되고 나서, 이상이 있을 경우 원복 로직을 구현하는것이 일반적이고 예상 가능한 형태라고 생각됨

- 클라이언트-ZK 간 네트워크에 단절 or 지연이 있는 상황에서는 운영자가 switchover 명령을 천천히 수행하더라도 문제가 생길 수 있습니다.
- 예를 들어, 클라이언트와 ZK가 통신할 수 없는 상태에서 운영자가 첫 switchover 수행 후
문제가 있는 것을 확인하고 다시 switchover 수행하여 원래대로 돌려놓을 수 있습니다.
  - 운영자는 서버/ZK 상태를 확인할 수 있겠지만, 클라이언트가 어떤 형상까지 반영한 상태인지는 알기 어렵습니다.

---

기존 구현에서는 어떤 상황에서도 (일시적으로 old 형상으로 되돌릴 수는 있지만) 결국에는 new 형상을 반영하는 것이 보장됩니다.
변경된 구현에서, `alreadySwitched`를 포함한 기타 변수들이 다양한 시나리오에서 일관된 상태로 수렴하는 것이 보장되는지가 궁금한 것입니다.

2024-12-16 05:37 UTC, brido4125 commented
> 극단적인 시나리오를 예시로 들고 있기는 하지만, 발생 확률이 낮으니 고려하지 않아도 된다는 논리는 적절하지 않아 보입니다.

@namsic 님의 제안해주신 의견이 너무 극단적이라 필요하지 않다라는 느낌의 코멘트는 아니니까 오해는 하지 말아주시고, 이렇게 이야기한 가장 큰 이유는 극단적인 case들에 대해 논의 때문에 원래 존재하는 PR의 목적을 잃는 경우가 잦아서 말씀드렸습니다.

> 변경된 구현에서, alreadySwitched를 포함한 기타 변수들이 다양한 시나리오에서 일관된 상태로 수렴하는 것이 보장되는지가 궁금한 것입니다.

동일한 그룹에 대해 위 시나리오에서 alreadySwitched는 아래와 같이 처리됩니다.

- 1차 스위치 오버(flag true로 변경) (M - S)
- 2차 스위치 오버(flag true로 변경) (S - M)
- 1차 스위치 오버에 대한 zk event 발생 -> old 형상(M - S)에 대한 zk 이벤트 발생 (true 값 및 현재 형상 유지) 
- 2차 스위치 오버에 대한 zk event 발생 -> 형상(S - M)이 같기에 false로 변경

2024-12-17 10:40 UTC, namsic commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +          if (oldRepl.size() == newRepl.size() && oldRepl.equals(newRepl)) {
`size()`와 `equals()` 각각 비교해야 하나요?

2024-12-17 10:40 UTC, namsic commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +        oldGroup.setAlreadySwitched(false);
노드 구성이 달라지면 switchover 이전의 old 형상으로 되돌아갈 수도 있나요?

2024-12-18 01:04 UTC, brido4125 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +          if (oldRepl.size() == newRepl.size() && oldRepl.equals(newRepl)) {
size는 노드 구성(갯수)를 확인하고 eqauls는 노드 내의 IP:PORT를 확인합니다.

2024-12-18 01:05 UTC, brido4125 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +        oldGroup.setAlreadySwitched(false);
> 노드 구성이 달라지면 switchover 이전의 old 형상으로 되돌아갈 수도 있나요?

넵, 현재 구현 상 노드 구성 / ip:port / groupname이 모두 같고 old 형상이 들어오는 경우만 무시하도록 구현되었습니다.

아마 말씀하신 코멘트의 예시가 이중화 상태에서 스위치 오버가 발생하고 나서
그룹 내의 노드 구성이 **삼중화로 구성된 캐시리스트**가 zk를 통해 들어왔는데, 
마침 해당 캐시리스트의 마스터-슬레이브가 old 형상인 경우를 말씀하신 것 같습니다.

이러한 경우는 해시링에 추가된 노드를 반영해야 하기에
changedSet에 변경 감지를 시켜줘야합니다.

old 형상으로 되돌아간 후의 처리에 대해 말씀드릴게요
만약 **삼중화로 구성된 캐시리스트**가 캐시 서버에 반영 되지 않았을 경우엔
`repl-slave`응답을 받아 한번 더 스위치 오버를 진행합니다.

이후 다시 요청을 보냈을 때, **삼중화로 구성된 zk이벤트**가 캐시 서버에 반영되면
해당 형상으로 스위치 오버를 진행합니다.
결국 eventually-consistency를 유지시켜줍니다.

2024-12-18 05:04 UTC, namsic submitted a review, later dismissed
제가 이해한 대로 정리하면,
1. switchover 이전 형상으로 되돌아가는 경우가 여전히 있을 수 있고
2. AlreadySwitched flag가 제 때 초기화되지 않을 수 있지만
3. 위와 같은 시나리오는 여러 극단적 상황이 겹치는 코너 케이스에 해당하여 실제 운영 환경에서 발생 가능성이 아주 작습니다.
4. 또한 그 경우에도 ZK event를 더 수신하다 보면 언젠가는 최신 형상으로 전이하게 됩니다.

2024-12-18 06:28 UTC, oliviarla reviewed
최종 리뷰 완료입니다.

2024-12-18 06:28 UTC, oliviarla commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +      if (oldGroup.isAlreadySwitched()) {
이 분기 내부에서 newAddrMap 관련된 처리가 필요할 것 같습니다.

2024-12-18 07:19 UTC, brido4125 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +      if (oldGroup.isAlreadySwitched()) {
isAlreadySwitched로 인해 변경 감지 되었지만 newAddrMap에 남아있어서 
중복으로 처리되는 경우를 해결하기 위한 변경 진행했습니다.

의도하신 변경이 맞는지 한번 검토 부탁드려요

2024-12-18 07:39 UTC, oliviarla approved these changes

2024-12-26 01:22 UTC, jhpark816 reviewed
리뷰 완료

2024-12-26 01:22 UTC, jhpark816 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +          }
삼중화에서 switchover 수행한 두 캐시 노드는 그대로 존재하고
나머지 1개 slave 노드가 다운된 경우, changed group으로 판별됩니다.
이 경우, 다운된 slave 노드를 제거하면서도
switchover를 원복하지 않나요?

2024-12-26 01:22 UTC, jhpark816 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +        }
전체적으로 복잡한 구현인 데, 더 단순한 구현은 없는 지 ?

2024-12-27 03:09 UTC, uhm0311 commented on src/main/java/net/spy/memcached/MemcachedConnection.java
> +          }
이 부분은 코드로 확인할 수 없는 부분입니다.
운영자가 정말로 삼중화를 이중화로 변경하고 싶어서 스위치오버 수행 후 슬레이브를 하나 내린 것인지, 스위치오버 직후에 슬레이브 하나에 장애가 발생한 것인지 알 수 없습니다.

2025-01-03 01:19 UTC, brido4125 commented
별도의 해결방안으로 처리중이기에 close하겠습니다.

2025-01-03 01:19 UTC, closed without merging